import type { FeatureComponents } from './entrant-appearance.mjs';
export type ActionConfig = { version: 2; appearance?: FeatureComponents | null; subscriberPolicy?: 'self_paid_v1'; repeatActorPolicy: 'skip' | 'accumulate'; award: { mode: 'fixed' | 'per_gift' | 'per_amount'; entriesPerUnit: number; unitCents: number } };
export const SELF_PAID_SUBSCRIBER_TYPE: string;
export const LEGACY_SUBSCRIBER_TYPE: string;
export const RAID_TYPE: string;
export const RAID_METHOD: string;
export const RAID_TEXT: string;
export const MAX_ENTRY_WEIGHT: number;
export const EVENT_TYPES: readonly string[];
export const CONDITION_FIELDS: Record<string, string[]>;
export function defaultAction(): ActionConfig;
export function ruleFieldErrors(input: unknown): Record<string, string>;
export function calculateAward(action: ActionConfig, eventType: string, evidence?: { totalGifts?: number; amountCents?: number }): { entries: number; reason: string | null; calculation: string };
