import type { ComponentProps, ReactNode } from 'react';
import { AdminIcon } from '../components/AdminIcon';
import type { CommerceLaunchPlan } from './client';
import './commerce-status-overview.css';

type Tone = 'ready' | 'attention' | 'blocked' | 'info' | 'neutral';
type Icon = ComponentProps<typeof AdminIcon>['name'];
function Status({ tone, children }: { tone: Tone; children: ReactNode }) {
  return <span className={`commerce-status-chip commerce-status-chip--${tone}`}><AdminIcon name={tone === 'ready' ? 'approved' : tone === 'blocked' ? 'rejected' : tone === 'attention' ? 'pending' : tone === 'info' ? 'shield' : 'collapse'} size={14}/>{children}</span>;
}
const title = (id: string) => id.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase()).replace(/\bPaypal\b/g, 'PayPal');

export function CommerceStatusHeader({ plan, status, blockers }: { plan: CommerceLaunchPlan | null; status: string; blockers: number }) {
  const tone: Tone = !plan ? 'neutral' : status.includes('DEGRADED') || status === 'ACTION REQUIRED' ? 'blocked' : status === 'PAUSED' ? 'attention' : 'ready';
  return <header className="commerce-status-hero"><div className="commerce-status-emblem"><AdminIcon name="commerce" size={34}/></div><div className="commerce-status-heading"><p className="eyebrow">Production commerce</p><h2 id="store-launch-title">Store status: {status}</h2><p>{plan?.business.tradingName || 'Your store operations'}<span>One view of checkout, fulfilment and delivery readiness.</span></p></div><div className="commerce-status-hero-state"><Status tone={tone}>{!plan ? 'Reading status' : status === 'LIVE / ACTIVE' ? 'Store live' : status === 'PAUSED' ? 'Store paused' : status.includes('DEGRADED') ? 'Action required' : status === 'READY TO ENABLE' ? 'Ready to enable' : 'Review required'}</Status>{plan && <span className="commerce-status-revision">Profile revision {plan.business.revision}</span>}</div>{plan && <div className="commerce-status-metrics"><div><AdminIcon name="shield"/><span><strong>{blockers}</strong>Hard blockers</span></div><div><AdminIcon name="products"/><span><strong>{plan.catalogue.eligibleSellableVariants}</strong>Eligible sellable variants</span></div><div><AdminIcon name="fulfillment"/><span><strong>{plan.shippingMarkets.filter(m => m.status === 'active').length}</strong>Active destinations</span></div><div><AdminIcon name={plan.settings.checkoutEnabled ? 'approved' : 'pending'}/><span><strong>{plan.settings.checkoutEnabled ? 'Enabled' : 'Paused'}</strong>Store checkout</span></div></div>}</header>;
}

export function CommerceServiceCards({ plan }: { plan: CommerceLaunchPlan }) {
  const ready = (id: string) => plan.hardGates.find(g => g.id === id)?.ready === true;
  const paymentReady = ['paypal_preferred', 'paypal_live_credential', 'paypal_live_account', 'paypal_live_webhook'].every(ready);
  const active = (enabled: boolean): [string, Tone] => enabled ? ['Active', 'ready'] : plan.state === 'active' ? ['Disabled', 'attention'] : ['Enabled with launch', 'neutral'];
  const cards: Array<{ title: string; icon: Icon; value: string; detail: string; status: [string, Tone]; href: string }> = [
    { title: 'Merchant facts', icon: 'business', value: plan.business.tradingName || 'Merchant identity', detail: 'Phone and address remain encrypted. Attestation is an operator confirmation.', status: plan.business.ownerConfirmed ? ['Operator attested', 'info'] : ready('merchant_identity') ? ['Configured', 'info'] : ['Action required', 'blocked'], href: '/commerce/business' },
    { title: 'Payment provider', icon: 'payments', value: 'PayPal Live', detail: 'Live account, credentials and webhook readiness are checked separately.', status: paymentReady ? ['Verified / ready', 'ready'] : ['Review connection', 'attention'], href: '/commerce/payments' },
    { title: 'Tax policy', icon: 'tax', value: ready('tax_policy') ? 'Not collecting' : 'Policy needs review', detail: 'Customer tax follows the configured server-side policy.', status: ready('tax_policy') ? ['Policy configured', 'info'] : ['Action required', 'blocked'], href: '/commerce/tax' },
    { title: 'Shipping & catalogue', icon: 'products', value: plan.settings.shippingStrategy === 'merchant_weight_bands' ? 'Merchant weight-band rates' : plan.settings.shippingStrategy === 'printful_dynamic' ? 'Automatic Printful rates' : 'Shipping policy review', detail: `${plan.catalogue.eligibleSellableVariants} eligible sellable variants. Destination service is checked when quoting.`, status: ready('shipping') && ready('catalogue') ? ['Ready for quotes', 'ready'] : ['Review readiness', 'attention'], href: '/commerce/fulfillment' },
    { title: 'Agreement & receipt', icon: 'orders', value: 'Transaction-only disclosure', detail: 'Accepted agreements and receipts stay attached to their transactions.', status: active(plan.settings.customerDocumentAccessEnabled), href: '/commerce/tax' },
    { title: 'Order confirmation', icon: 'emails', value: 'Resend', detail: 'Order-confirmation delivery follows the store’s transactional email setting.', status: active(plan.settings.transactionalEmailEnabled), href: '/commerce/emails' },
    { title: 'Fulfilment operations', icon: 'fulfillment', value: 'Draft → validate → confirm', detail: 'The existing payment and fulfilment safeguards remain authoritative.', status: active(plan.settings.fulfillmentEnabled), href: '/commerce/fulfillment' },
    { title: 'Delivery lifecycle', icon: 'signal', value: 'Authenticated reconciliation', detail: 'Scheduled operations reconcile provider delivery and fulfilment evidence.', status: ready('operations_worker') && plan.settings.fulfillmentEnabled ? ['Active', 'ready'] : ['Review operations', 'attention'], href: '/commerce/fulfillment' },
  ];
  return <><div className="commerce-services-heading"><div><p className="eyebrow">Connected operations</p><h3>Your store, at a glance</h3></div><span>Current configuration & readiness</span></div><dl className="store-launch-summary commerce-service-grid">{cards.map(card => <div className="commerce-service-card" key={card.title}><dt><span className="commerce-service-icon"><AdminIcon name={card.icon} size={21}/></span>{card.title}<a href={card.href} aria-label={`Review ${card.title.toLowerCase()}`}><AdminIcon name="external" size={15}/></a></dt><dd><Status tone={card.status[1]}>{card.status[0]}</Status><strong>{card.value}</strong><p>{card.detail}</p></dd></div>)}</dl><div className="commerce-optional-strip"><AdminIcon name="settings" size={19}/><strong>Optional services</strong><span>Stripe <Status tone="neutral">{ready('paypal_preferred') ? 'Not used / disabled' : 'Review provider policy'}</Status></span><span>Tax invoice <Status tone="neutral">{ready('tax_policy') ? 'Not applicable' : 'Review tax policy'}</Status></span></div></>;
}

export function CommerceReadinessDetails({ plan }: { plan: CommerceLaunchPlan }) {
  const passed = plan.hardGates.filter(g => g.ready).length;
  return <details className="commerce-readiness-details"><summary><span className="commerce-readiness-icon"><AdminIcon name="shield" size={23}/></span><span><strong>Non-blocking capabilities and readiness details</strong><small>Inspect the evidence behind each status.</small></span><Status tone={passed === plan.hardGates.length ? 'ready' : 'attention'}>{passed} / {plan.hardGates.length} required checks ready</Status><AdminIcon name="chevron" size={18}/></summary><div className="commerce-readiness-content">{([{ title: 'Required checks', subtitle: 'Dependencies that govern store readiness.', gates: plan.hardGates, required: true }, { title: 'Additional capabilities', subtitle: 'Optional evidence and post-purchase services.', gates: plan.advisories, required: false }]).map(group => <section key={group.title}><div className="commerce-readiness-group"><h4>{group.title}</h4><p>{group.subtitle}</p></div><div className="commerce-check-grid">{group.gates.map(gate => <article key={gate.id} className={`commerce-check ${!gate.ready && group.required ? 'commerce-check--blocked' : ''}`}><div><AdminIcon name={gate.ready ? 'approved' : group.required ? 'rejected' : 'pending'} size={19}/><h5>{title(gate.id)}</h5><Status tone={gate.ready ? 'ready' : group.required ? 'blocked' : 'neutral'}>{gate.ready ? group.required ? 'Ready' : 'Verified / ready' : group.required ? 'Action required' : gate.id.startsWith('printful') ? 'Optional / unverified' : 'Post-launch optional'}</Status></div><p>{gate.detail}</p>{gate.href && <a href={gate.href}>Review requirement<AdminIcon name="arrow" size={14}/></a>}</article>)}</div></section>)}</div></details>;
}
