import {useCallback,useEffect,useState} from 'react';
import {adminApi} from '../auth/client';
type Item={providerId:string;localId:string|null;title:string;image:string|null;state:string;selected:boolean;publish:boolean;errorCode:string|null;warnings:string[];variants:Array<{id:string;name:string;unitAmount:number;catalogueVariantId:string|null}>;result:{published?:boolean}};
type Sync={shippingStrategy:string;policy:{revision:number;interval_minutes:number;auto_import:number;publish_new:number;last_success_at:string|null;next_run_at:string|null};job:null|{id:string;state:string;phase:string;errorCode:string|null;retryAt:string|null};items:Item[]};
export function PrintfulSync({csrfToken,canManage,onChanged}:{csrfToken:string|null;canManage:boolean;onChanged:()=>void}){
 const [data,setData]=useState<Sync|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('title'),[page,setPage]=useState(1),[size,setSize]=useState(20),[interval,setIntervalMinutes]=useState(0),[automatic,setAutomatic]=useState(false),[publishNew,setPublishNew]=useState(true);
 const endpoint='/api/admin/commerce/products/sync';
 useEffect(()=>{void adminApi<Sync>(endpoint).then(s=>{setData(s);setIntervalMinutes(s.policy.interval_minutes);setAutomatic(!!s.policy.auto_import);setPublishNew(!!s.policy.publish_new);}).catch(e=>setError(e.message));},[]);
 const action=useCallback(async(action:string,extra:Record<string,unknown>={})=>{if(!csrfToken)return;setBusy(true);setError('');try{const s=await adminApi<Sync>(endpoint,{method:'POST',headers:{'X-CSRF-Token':csrfToken},body:JSON.stringify({action,jobId:data?.job?.id,...extra})});setData(s);if(['completed','partial'].includes(s.job?.state||''))onChanged();}catch(e){setError(e instanceof Error?e.message:'Sync failed');}finally{setBusy(false);}},[csrfToken,data?.job?.id,onChanged]);
 useEffect(()=>{if(!busy&&data?.job&&['reading','applying'].includes(data.job.state)){const timer=window.setTimeout(()=>{void action('step');},Math.max(1500,Date.parse(data.job.retryAt||'')-Date.now()||0));return()=>window.clearTimeout(timer);}},[data,busy,action]); // One bounded checkpoint per request; reload resumes persisted progress.
 const change=(id:string,patch:Partial<Item>)=>setData(s=>s?{...s,items:s.items.map(i=>i.providerId===id?{...i,...patch}:i)}:s);
 const rows=(data?.items||[]).filter(i=>i.title.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='new'&&!i.localId||filter==='attention'&&(i.errorCode||i.warnings.length)||filter==='draft'&&!i.publish)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):a.state.localeCompare(b.state));
 return <section className="commerce-section" aria-label="Sync Printful"><div className="commerce-section-heading-actions"><div><p className="eyebrow">Native store 18668025</p><h2>Sync Printful</h2></div><button className="button-link" type="button" disabled={!canManage||busy||['reading','review','applying'].includes(data?.job?.state||'')} onClick={()=>void action('start')}>Sync Printful</button></div><p>Read designed products from Printful, review changes, then import and publish eligible selections.</p>{error&&<p role="alert">{error}</p>}
 <details><summary>Automatic sync settings</summary><div className="workspace-tools"><label>Schedule<select value={interval} onChange={e=>setIntervalMinutes(Number(e.target.value))}>{[0,15,30,60].map(n=><option value={n} key={n}>{n?`Every ${n} minutes`:'Off'}</option>)}</select></label><label><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/>Automatically import reviewed eligible products</label><label><input type="checkbox" checked={publishNew} onChange={e=>setPublishNew(e.target.checked)}/>Publish new eligible products to storefront</label><button type="button" disabled={!canManage||busy||!data} onClick={()=>void action('policy',{policy:{revision:data?.policy.revision,intervalMinutes:interval,autoImport:automatic,publishNew}})}>Save sync policy</button></div><p>Existing drafts retain their publication choice. Last success: {data?.policy.last_success_at||'None'} · Next run: {data?.policy.next_run_at||'Off'}</p></details>
 {data?.job&&<><p role="status">{data.job.state} · {data.job.phase} · {data.items.filter(i=>['review','completed','failed','skipped'].includes(i.state)).length} / {data.items.length} products {data.job.retryAt&&`· Retry ${data.job.retryAt}`}</p>{data.job.errorCode&&<p role="alert">{data.job.errorCode}</p>}{['reading','applying','review'].includes(data.job.state)&&<button type="button" disabled={busy} onClick={()=>void action('cancel')}>Cancel sync</button>}{['failed','partial'].includes(data.job.state)&&<button type="button" disabled={busy} onClick={()=>void action('retry')}>Retry failed items</button>}
 <div className="workspace-tools"><input aria-label="Search sync review" type="search" value={query} placeholder="Search products" onChange={e=>{setQuery(e.target.value);setPage(1);}}/><select aria-label="Sync status filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">All products</option><option value="new">New products</option><option value="attention">Needs attention</option><option value="draft">Keep draft</option></select><select aria-label="Sort sync review" value={sort} onChange={e=>setSort(e.target.value)}><option value="title">Product name</option><option value="state">Status</option></select>{data.job.state==='review'&&<><button type="button" onClick={()=>rows.forEach(i=>change(i.providerId,{publish:true}))}>Publish matching</button><button type="button" onClick={()=>rows.forEach(i=>change(i.providerId,{publish:false}))}>Keep matching draft</button></>}</div>
 <div className="workspace-table"><table data-resizable-key="printful-sync-review"><thead><tr>{['Select','Product','Change','Variants','Price','Publication','Shipping','Media','Issues / action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((page-1)*size,page*size).map(i=><tr key={i.providerId}><td><input aria-label={`Import ${i.title}`} type="checkbox" disabled={data.job?.state!=='review'} checked={i.selected} onChange={e=>change(i.providerId,{selected:e.target.checked})}/></td><td>{i.image&&<img src={i.image} alt=""/>}{i.title}</td><td>{i.localId?'Refresh':'New'}</td><td><details><summary>{i.variants.length} variants</summary>{i.variants.map(v=><p key={v.id}>{v.name} · {v.unitAmount} CAD cents {!v.catalogueVariantId&&'· Missing Catalog mapping'}</p>)}</details></td><td>{i.localId?'Manual prices preserved':'Provider CAD prices'}</td><td><label><input type="checkbox" checked={i.publish} disabled={data.job?.state!=='review'} onChange={e=>change(i.providerId,{publish:e.target.checked})}/>Publish</label></td><td>{data.shippingStrategy==='printful_dynamic'?'Automatic Printful rates; local weight optional':'Merchant weight bands; effective weight required'}</td><td>{i.state==='completed'?'Staged to CDN':i.image?'Download pending':'Image required'}</td><td>{[...i.warnings,i.errorCode].filter(Boolean).join(', ')||i.state}{i.localId&&<a href={`/products?productId=${encodeURIComponent(i.localId)}`}>Open product</a>}</td></tr>)}</tbody></table></div><div className="workspace-tools"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {Math.max(1,Math.ceil(rows.length/size))}</span><button type="button" disabled={page*size>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</button><select aria-label="Sync products per page" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[20,50,75,100].map(n=><option key={n}>{n}</option>)}</select></div>{data.job.state==='review'&&<button type="button" className="button-link" disabled={busy||!canManage} onClick={()=>void action('apply',{items:data.items.map(({providerId,selected,publish})=>({providerId,selected,publish}))})}>Import &amp; publish eligible products</button>}</>}
 </section>;
}
