import {displayCommerceMedia} from './displayMedia';
import {Fragment,useCallback,useEffect,useState} from 'react';
import {AdminIcon} from '../components/AdminIcon';
import './printful-sync.css';
import {adminApi} from '../auth/client';
type Item={providerId:string;localId:string|null;title:string;image:string|null;state:string;selected:boolean;publish:boolean;errorCode:string|null;warnings:string[];variants:Array<{id:string;name:string;unitAmount:number;catalogueVariantId:string|null}>;result:{published?:boolean}};
type Sync={shippingStrategy:string;policy:{revision:number;interval_minutes:number;auto_import:number;publish_new:number;last_success_at:string|null;next_run_at:string|null};job:null|{id:string;state:string;phase:string;errorCode:string|null;retryAt:string|null};items:Item[]};
export function PrintfulSync({csrfToken,canManage,onChanged}:{csrfToken:string|null;canManage:boolean;onChanged:()=>void}){
 const [data,setData]=useState<Sync|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('title'),[page,setPage]=useState(1),[size,setSize]=useState(20),[interval,setIntervalMinutes]=useState(0),[automatic,setAutomatic]=useState(false),[publishNew,setPublishNew]=useState(true);
 const [expanded,setExpanded]=useState<string[]>([]);
 const endpoint='/api/admin/commerce/products/sync';
 useEffect(()=>{void adminApi<Sync>(endpoint).then(s=>{setData(s);setIntervalMinutes(s.policy.interval_minutes);setAutomatic(!!s.policy.auto_import);setPublishNew(!!s.policy.publish_new);}).catch(e=>setError(e.message));},[]);
 const action=useCallback(async(action:string,extra:Record<string,unknown>={})=>{if(!csrfToken)return;setBusy(true);setError('');try{const s=await adminApi<Sync>(endpoint,{method:'POST',headers:{'X-CSRF-Token':csrfToken},body:JSON.stringify({action,jobId:data?.job?.id,...extra})});setData(s);if(['completed','partial'].includes(s.job?.state||''))onChanged();}catch(e){setError(e instanceof Error?e.message:'Sync failed');}finally{setBusy(false);}},[csrfToken,data?.job?.id,onChanged]);
 useEffect(()=>{if(!busy&&data?.job&&['reading','applying'].includes(data.job.state)){const timer=window.setTimeout(()=>{void action('step');},Math.max(1500,Date.parse(data.job.retryAt||'')-Date.now()||0));return()=>window.clearTimeout(timer);}},[data,busy,action]); // One bounded checkpoint per request; reload resumes persisted progress.
 const change=(id:string,patch:Partial<Item>)=>setData(s=>s?{...s,items:s.items.map(i=>i.providerId===id?{...i,...patch}:i)}:s);
 const rows=(data?.items||[]).filter(i=>i.title.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='new'&&!i.localId||filter==='attention'&&(i.errorCode||i.warnings.length)||filter==='draft'&&!i.publish)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):a.state.localeCompare(b.state));
 const job=data?.job,review=job?.state==='review',running=!!job&&['reading','applying'].includes(job.state);
 const items=data?.items||[],selected=items.filter(i=>i.selected),attention=items.filter(i=>i.errorCode||i.warnings.length),completed=items.filter(i=>i.state==='completed').length;
 const policyDirty=!!data&&(interval!==data.policy.interval_minutes||automatic!==!!data.policy.auto_import||publishNew!==!!data.policy.publish_new);
 const time=(value:string|null|undefined)=>value?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Not yet';
 const stage=job?.state==='reading'?0:job?.state==='review'?1:job?2:-1;
 const toggleExpanded=(id:string)=>setExpanded(ids=>ids.includes(id)?ids.filter(v=>v!==id):[...ids,id]);
 return <section className="commerce-section printful-sync" aria-label="Sync Printful">
   <header className="sync-hero">
     <div className="sync-hero__identity"><span className="sync-icon-tile"><AdminIcon name="products" size={28}/></span><div><p className="eyebrow">Printful / native store 18668025</p><h2>Sync Printful</h2><p>Your designs. One considered review. Ready for the storefront.</p></div></div>
     <button className="button-link sync-primary" type="button" disabled={!canManage||busy||running||review} onClick={()=>void action('start')}><AdminIcon name="integrations" size={18}/>Sync Printful<AdminIcon name="arrow" size={16}/></button>
   </header>
   <ol className="sync-journey" aria-label="Sync stages">{['Read the catalogue','Review your products','Import & publish'].map((label,index)=><li key={label} className={stage===index?'is-current':stage>index?'is-complete':''}><span>{stage>index?<AdminIcon name="approved" size={17}/>:String(index+1).padStart(2,'0')}</span>{label}{index<2&&<i aria-hidden="true"/>}</li>)}</ol>
   {error&&<div className="sync-notice is-error" role="alert"><AdminIcon name="rejected"/><span>{error}</span></div>}
   <details className="sync-settings">
     <summary><span className="sync-settings__icon"><AdminIcon name="automations" size={23}/></span><span className="sync-settings__heading"><strong>Automatic sync settings</strong><small>Choose when to check Printful and how new products arrive.</small></span><span className="sync-badge">{data?.policy.interval_minutes?`${data.policy.interval_minutes} min`:'Manual only'}</span><span className="sync-settings__chevron"><AdminIcon name="chevron" size={18}/></span></summary>
     <div className="sync-settings__body">
       <div className="sync-settings__schedule"><p className="eyebrow">01 / cadence</p><h3>A rhythm that suits your store</h3><p>Each run resumes safely. Your existing drafts and merchant edits stay protected.</p><div className="sync-cadence" role="group" aria-label="Sync frequency">{[0,15,30,60].map(n=><button type="button" key={n} aria-pressed={interval===n} disabled={!canManage||busy} onClick={()=>setIntervalMinutes(n)}><strong>{n||'Off'}</strong><span>{n?'minutes':'Manual sync'}</span></button>)}</div><div className="sync-schedule-times"><span><AdminIcon name="approved" size={16}/><span>Last successful sync<strong>{time(data?.policy.last_success_at)}</strong></span></span><span><AdminIcon name="pending" size={16}/><span>Next scheduled run<strong>{data?.policy.next_run_at?time(data.policy.next_run_at):'Schedule is off'}</strong></span></span></div></div>
       <div className="sync-settings__choices"><p className="eyebrow">02 / import preferences</p><label className="sync-choice"><span className="sync-choice__copy"><strong>Automatically import eligible products</strong><small>Apply completed scheduled reads. Items with blockers stay in review.</small></span><input type="checkbox" role="switch" checked={automatic} disabled={!canManage||busy} onChange={e=>setAutomatic(e.target.checked)}/></label><label className="sync-choice"><span className="sync-choice__copy"><strong>Publish new eligible products to storefront</strong><small>New designs arrive ready to buy when their dependencies are valid. Existing hidden choices stay hidden.</small></span><input type="checkbox" role="switch" checked={publishNew} disabled={!canManage||busy} onChange={e=>setPublishNew(e.target.checked)}/></label><p className="sync-protection"><AdminIcon name="shield" size={17}/>Your prices, images and shipping policy are preserved.</p></div>
     </div>
     <footer className="sync-settings__footer"><span className={policyDirty?'is-dirty':''}>{policyDirty?'Unsaved sync preferences':'Preferences are up to date'}</span><button type="button" className="button-link" disabled={!canManage||busy||!data||!policyDirty} onClick={()=>void action('policy',{policy:{revision:data?.policy.revision,intervalMinutes:interval,autoImport:automatic,publishNew}})}>Save sync policy<AdminIcon name="arrow" size={16}/></button></footer>
   </details>
   {job?<>
     <div className="sync-review-heading"><div><p className="eyebrow">Catalogue review</p><h3>{review?'Make room for your next release':job.state==='completed'?'Your catalogue is up to date':job.state==='partial'?'Imported, with a few items to revisit':running?'Bringing your catalogue together':'Your latest sync'}</h3><p role="status">{job.state} / {job.phase} / {items.filter(i=>['review','completed','failed','skipped'].includes(i.state)).length} / {items.length} products{job.retryAt&&` / Retry ${time(job.retryAt)}`}</p></div><div>{(running||review)&&<button type="button" className="sync-quiet-button" disabled={busy} onClick={()=>void action('cancel')}><AdminIcon name="close" size={16}/>Cancel sync</button>}{['failed','partial'].includes(job.state)&&<button type="button" disabled={busy} onClick={()=>void action('retry')}>Retry failed items</button>}</div></div>
     {job.errorCode&&<p role="alert" className="sync-notice is-error">{job.errorCode}</p>}
     <div className="sync-metrics"><div><span><AdminIcon name="products" size={17}/>In this review</span><strong>{items.length}<small>products</small></strong></div><div><span><AdminIcon name="eye" size={17}/>Selected to publish</span><strong>{selected.filter(i=>i.publish).length}<small>of {selected.length} selected</small></strong></div><div className={attention.length?'has-attention':''}><span><AdminIcon name={attention.length?'pending':'approved'} size={17}/>Needs attention</span><strong>{attention.length}<small>{attention.length?'review the details':'looking good'}</small></strong></div><div><span><AdminIcon name="approved" size={17}/>Imported</span><strong>{completed}<small>products saved</small></strong></div></div>
     <div className="sync-filterbar"><label className="sync-search"><AdminIcon name="products" size={17}/><input aria-label="Search sync review" type="search" value={query} placeholder="Find a product in this sync..." onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label><span>Status</span><select aria-label="Sync status filter" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">All products</option><option value="new">New products</option><option value="attention">Needs attention</option><option value="draft">Keep draft</option></select></label><label><span>Sort by</span><select aria-label="Sort sync review" value={sort} onChange={e=>setSort(e.target.value)}><option value="title">Product name</option><option value="state">Status</option></select></label></div>
     {review&&<div className="sync-bulkbar"><span>{selected.length} selected <small>/ {rows.length} matching your filters</small></span><div><button type="button" onClick={()=>rows.forEach(i=>change(i.providerId,{publish:true}))}><AdminIcon name="eye" size={16}/>Publish matching</button><button type="button" onClick={()=>rows.forEach(i=>change(i.providerId,{publish:false}))}><AdminIcon name="eyeOff" size={16}/>Keep matching draft</button></div></div>}
     <div className="workspace-table sync-review-table"><table data-resizable-key="printful-sync-review"><thead><tr>{['Select','Product / design','Change','Variants','Price','Publication','Shipping','Media','Review'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((page-1)*size,page*size).map(i=><Fragment key={i.providerId}><tr className={expanded.includes(i.providerId)?'is-expanded':''}>
       <td><input aria-label={`Import ${i.title}`} type="checkbox" disabled={!review} checked={i.selected} onChange={e=>change(i.providerId,{selected:e.target.checked})}/></td>
       <td><div className="sync-product"><span className="sync-product__image">{i.image?<img src={displayCommerceMedia(i.image)} alt=""/>:<AdminIcon name="media" size={26}/>}</span><span><strong>{i.title}</strong><small>Printful #{i.providerId}</small></span></div></td>
       <td><span className={`sync-badge ${i.localId?'':'is-gold'}`}>{i.localId?'Refresh':'New product'}</span></td>
       <td><button type="button" className="sync-expand" aria-label={`Review variants for ${i.title}`} aria-expanded={expanded.includes(i.providerId)} onClick={()=>toggleExpanded(i.providerId)}>{i.variants.length}<AdminIcon name="chevron" size={14}/></button></td>
       <td><strong className="sync-cell-title">{i.localId?'Prices protected':'Provider prices'}</strong><small className="sync-cell-note">{i.localId?'Merchant edits kept':'CAD / from Printful'}</small></td>
       <td><label className="sync-publish"><input type="checkbox" role="switch" checked={i.publish} disabled={!review} onChange={e=>change(i.providerId,{publish:e.target.checked})}/><span>{i.publish?'Publish':'Keep draft'}</span></label></td>
       <td><span className="sync-cell-icon"><AdminIcon name="fulfillment" size={16}/>{data?.shippingStrategy==='printful_dynamic'?'Automatic rates':'Weight bands'}</span><small className="sync-cell-note">{data?.shippingStrategy==='printful_dynamic'?'Local weight optional':'Effective weight required'}</small></td>
       <td><span className={`sync-badge ${i.state==='completed'?'is-ready':''}`}><AdminIcon name={i.state==='completed'?'approved':'media'} size={14}/>{i.state==='completed'?'On CDN':i.image?'Ready to ingest':'Image needed'}</span></td>
       <td><button type="button" className={`sync-issue-button ${i.warnings.length||i.errorCode?'has-attention':''}`} aria-expanded={expanded.includes(i.providerId)} onClick={()=>toggleExpanded(i.providerId)}><AdminIcon name={i.warnings.length||i.errorCode?'pending':'approved'} size={16}/>{i.warnings.length||i.errorCode?`${i.warnings.length+(i.errorCode?1:0)} issues`:'View details'}</button></td>
     </tr>{expanded.includes(i.providerId)&&<tr className="sync-detail-row"><td colSpan={9}><div className="sync-detail"><header><div><p className="eyebrow">Variant review</p><h4>{i.title}</h4><p>Exact Catalog mapping, provider price and the effective shipping requirement.</p></div>{i.localId&&<a className="sync-editor-link" href={`/products?productId=${encodeURIComponent(i.localId)}`}>Open product workspace<AdminIcon name="arrow" size={16}/></a>}</header><div className="sync-variant-grid">{i.variants.map(v=><article key={v.id}><div><AdminIcon name="products" size={18}/><strong>{v.name||`Variant ${v.id}`}</strong></div><dl><div><dt>Provider price</dt><dd>{new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(v.unitAmount/100)}</dd></div><div><dt>Catalog mapping</dt><dd className={v.catalogueVariantId?'':'has-attention'}>{v.catalogueVariantId?`#${v.catalogueVariantId}`:'Missing / blocks purchase'}</dd></div></dl><span className="sync-variant-note">{data?.shippingStrategy==='printful_dynamic'?'Automatic shipping / weight optional':'Merchant shipping / check effective weight'}</span></article>)}</div>{!!(i.warnings.length||i.errorCode)&&<div className="sync-issues"><h5><AdminIcon name="pending" size={17}/>Before this product is ready</h5>{[...i.warnings,i.errorCode].filter(Boolean).map((message,index)=><p key={index}>{message}</p>)}</div>}<p className="sync-detail-footnote"><AdminIcon name="shield" size={16}/>Publication requires valid dependencies. Destination availability is checked when a shopper requests a quote.</p></div></td></tr>}</Fragment>)}</tbody></table>{!rows.length&&<div className="sync-empty"><AdminIcon name="products" size={30}/><h4>No matching products</h4><p>Try a different search or status filter.</p></div>}</div>
     <div className="sync-pagination"><span>Showing {rows.length?((page-1)*size)+1:0} to {Math.min(page*size,rows.length)} of {rows.length}</span><div><label>Per page<select aria-label="Sync products per page" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[20,50,75,100].map(n=><option key={n}>{n}</option>)}</select></label><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {Math.max(1,Math.ceil(rows.length/size))}</span><button type="button" disabled={page*size>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>
     {review&&<footer className="sync-confirm"><div><strong>{selected.length} products selected</strong><p>{selected.filter(i=>i.publish).length} set to publish / {selected.filter(i=>!i.publish).length} kept as draft. Blocked variants stay draft.</p></div><button type="button" className="button-link sync-primary" disabled={busy||!canManage||!selected.length} onClick={()=>void action('apply',{items:items.map(({providerId,selected,publish})=>({providerId,selected,publish}))})}>Import &amp; publish eligible products<AdminIcon name="arrow" size={18}/></button></footer>}
   </>:<div className="sync-welcome"><AdminIcon name="integrations" size={20}/><p>Ready when you are. Start a sync to review your latest Printful designs.</p><span className="sync-badge">Merchant edits protected</span></div>}
 </section>;
}
