import {displayCommerceMedia} from './displayMedia';
import {useEffect,useRef,useState} from 'react';
import {adminApi} from '../auth/client';
import {uploadMerchandisingProductMedia,type MerchandisingProduct,type CommerceCollection} from './client';
import './product-workspace.css';
type Image={url:string;alt:string};
type VariantEdit={variantId:string;displayLabel:string;size:string;color:string;options:Record<string,string>;unitAmount:number;currencyCode:string;status:string;visibility:string;sellable:boolean;availability:string};
type Workspace={product:MerchandisingProduct;revision:string;providerValues:Array<{variantId:string;unitAmount?:number}>;shippingStrategy:string;weights:Array<{variant_id:string|null;weight_mg:number|null;provenance:string}>;mediaAssignments:Array<{variantId:string;images:Image[];providerImage:string|null}>;readiness:{purchasable:boolean;publicationIntent:string;productReasons:string[];variants:Array<{id:string;publicationIntent:string;reasons:string[];localReasons:string[];shipping:{ready:boolean;reasons:string[];weightMg:number|null;source:string}}>};saveResult?:{message:string}};
const tabs=['Overview','Variants','Media','Shipping','Sync history and Issues'];
export function ProductWorkspace({product,collections,csrfToken,canManage,onClose,onSaved,onError}:{product:MerchandisingProduct;collections:CommerceCollection[];csrfToken:string|null;canManage:boolean;onClose:()=>void;onSaved:(p:MerchandisingProduct,message:string)=>void;onError:(message:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState<Workspace|null>(null),[tab,setTab]=useState(tabs[0]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false);
 const [edit,setEdit]=useState(product),[publish,setPublish]=useState(product.visibility==='public'),[variants,setVariants]=useState<VariantEdit[]>([]),[assignments,setAssignments]=useState<Workspace['mediaAssignments']>([]),[weights,setWeights]=useState<Array<{variantId:string|null;value:string|null;unit:string}>>([]);
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[mediaUrl,setMediaUrl]=useState(''),[alt,setAlt]=useState(''),[weightValue,setWeightValue]=useState(''),[unit,setUnit]=useState('g');
 const path=`/api/admin/commerce/products/${encodeURIComponent(product.id)}/workspace`;
 const load=(w:Workspace)=>{setData(w);setEdit(w.product);setPublish(w.readiness.publicationIntent==='operator_publish'||w.product.visibility==='public');setVariants(w.product.variants.map(v=>({variantId:v.id,displayLabel:v.displayLabel,size:v.size||'',color:v.color||'',options:v.options,unitAmount:v.unitAmount,currencyCode:'CAD',status:w.readiness.variants.find(r=>r.id===v.id)?.publicationIntent==='operator_publish'?'active':v.status,visibility:w.readiness.variants.find(r=>r.id===v.id)?.publicationIntent==='operator_publish'?'public':v.visibility,sellable:v.sellable||w.readiness.variants.find(r=>r.id===v.id)?.publicationIntent==='operator_publish',availability:v.availability})));setAssignments(w.mediaAssignments);setWeights([]);setDirty(false);};
 useEffect(()=>{dialog.current?.showModal();void adminApi<Workspace>(path).then(load).catch(e=>setError(e.message));},[path]);
 const close=()=>{if(!dirty||window.confirm('Discard unsaved product changes?'))onClose();};
 const change=(patch:Partial<MerchandisingProduct>)=>{setEdit(p=>({...p,...patch}));setDirty(true);};
 const variantChange=(id:string,patch:Partial<VariantEdit>)=>{setVariants(rows=>rows.map(v=>v.variantId===id?{...v,...patch}:v));setDirty(true);};
 const save=async()=>{if(!csrfToken||!data)return;setBusy(true);setError('');try{const next=await adminApi<Workspace>(path,{method:'POST',headers:{'X-CSRF-Token':csrfToken},body:JSON.stringify({revision:data.revision,publish,product:{title:edit.title,slug:edit.slug,description:edit.description,primaryImageUrl:edit.primaryImageUrl,additionalImages:edit.additionalImages,categories:edit.categories,tags:edit.tags,featured:edit.featured,visibility:edit.visibility,status:edit.status,displayOrder:edit.displayOrder,maxQuantity:edit.maxQuantity,unitAmount:edit.unitAmount,currencyCode:'CAD',saleRestriction:edit.saleRestriction},variants,mediaAssignments:assignments.filter(a=>JSON.stringify(a.images)!==JSON.stringify(data.mediaAssignments.find(b=>b.variantId===a.variantId)?.images||[])).map(({variantId,images})=>({variantId,images})),weights})});load(next);onSaved(next.product,next.saveResult?.message||'Product saved.');}catch(e){const message=e instanceof Error?e.message:'Save failed.';setError(message);onError(message);}finally{setBusy(false);}};
 const addImage=(url:string)=>{if(!url)return;change({additionalImages:[...new Set([...edit.additionalImages,url])]});setMediaUrl('');};
 const upload=async(file:File)=>{if(!csrfToken)return;setBusy(true);try{const result=await uploadMerchandisingProductMedia(csrfToken,product.id,file);addImage(result.asset.url);}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}};
 const assign=(url:string)=>{setAssignments(rows=>rows.map(a=>selected.includes(a.variantId)?{...a,images:[{url,alt},...a.images.filter(i=>i.url!==url)]}:a));setDirty(true);};
 const filtered=variants.filter(v=>[v.displayLabel,v.size,v.color].join(' ').toLowerCase().includes(query.toLowerCase()));const visible=filtered.slice((page-1)*pageSize,page*pageSize);
 const stageWeight=(ids:Array<string|null>,value:string|null)=>{setWeights(current=>[...current.filter(w=>!ids.includes(w.variantId)),...ids.map(variantId=>({variantId,value,unit}))]);setDirty(true);};
 return <dialog ref={dialog} className="product-workspace" aria-labelledby="workspace-title" onCancel={e=>{e.preventDefault();close();}}><header><div><p className="eyebrow">Product workspace</p><h2 id="workspace-title">{edit.title}</h2><p>{data?.readiness.purchasable?'Ready for production checkout':data?'Needs review':'Loading…'} · {dirty?'Unsaved changes':'Saved'}</p></div><button type="button" onClick={close} aria-label="Close editor">Close editor</button></header>
 <nav aria-label="Product sections">{tabs.map(name=><button key={name} type="button" aria-current={tab===name?'page':undefined} onClick={()=>setTab(name)}>{name}</button>)}</nav>
 <div className="product-workspace__body">{error&&<p role="alert">{error}</p>}{!data?<p>Loading canonical product…</p>:<fieldset disabled={busy||!canManage}>
 {tab==='Overview'&&<section><div className="workspace-preview">{edit.primaryImageUrl&&<img src={displayCommerceMedia(edit.primaryImageUrl)} alt={edit.title}/>}<div><label className="commerce-toggle"><input type="checkbox" checked={publish} onChange={e=>{setPublish(e.target.checked);setDirty(true);}}/>Publish to storefront</label><p>Save includes publication of eligible variants. Blocked variants remain draft with their reasons.</p></div></div><div className="workspace-fields"><label>Title<input value={edit.title} onChange={e=>change({title:e.target.value})}/></label><label>Stable product URL<input value={edit.slug} readOnly/></label><label className="workspace-wide">Description<textarea rows={5} value={edit.description} onChange={e=>change({description:e.target.value})}/></label><label>Tags<input value={edit.tags.join(', ')} onChange={e=>change({tags:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/></label><label><input type="checkbox" checked={edit.featured} onChange={e=>change({featured:e.target.checked})}/>Featured product</label><label><input type="checkbox" checked={edit.saleRestriction?.enabled||false} onChange={e=>change({saleRestriction:{enabled:e.target.checked,reason:edit.saleRestriction?.reason||'display_only'}})}/>Display only / not for sale</label><label>Display order<input type="number" min={0} value={edit.displayOrder} onChange={e=>change({displayOrder:Number(e.target.value)})}/></label><label>Maximum quantity<input type="number" min={1} max={20} value={edit.maxQuantity} onChange={e=>change({maxQuantity:Number(e.target.value)})}/></label></div><fieldset><legend>Collections</legend>{collections.map(c=><label key={c.id}><input type="checkbox" checked={edit.categories.includes(c.title)} onChange={e=>change({categories:e.target.checked?[...edit.categories,c.title]:edit.categories.filter(v=>v!==c.title)})}/>{c.title}</label>)}</fieldset></section>}
 {['Variants','Media','Shipping'].includes(tab)&&<div className="workspace-tools"><input type="search" aria-label="Search variants" placeholder="Search variants" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/><button type="button" onClick={()=>setSelected(filtered.map(v=>v.variantId))}>Select matching variants</button><button type="button" onClick={()=>setSelected([])}>Clear selection</button><span>{selected.length} selected</span><select aria-label="Select colour group" value="" onChange={e=>setSelected(variants.filter(v=>v.color===e.target.value).map(v=>v.variantId))}><option value="">Select all of a colour</option>{[...new Set(variants.map(v=>v.color))].filter(Boolean).map(c=><option key={c}>{c}</option>)}</select></div>}
 {tab==='Variants'&&<section><div className="workspace-tools"><button type="button" disabled={!selected.length} onClick={()=>{for(const id of selected)variantChange(id,{sellable:true,status:'active',visibility:'public'});}}>Include selected</button><button type="button" disabled={!selected.length} onClick={()=>{for(const id of selected)variantChange(id,{sellable:false,visibility:'private'});}}>Keep selected draft</button></div><div className="workspace-table"><table data-resizable-key="product-workspace-variants"><thead><tr>{['Select','Preview / options','CAD cents','Availability','Publication','Effective shipping'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(v=>{const r=data.readiness.variants.find(r=>r.id===v.variantId),a=assignments.find(a=>a.variantId===v.variantId);return <tr key={v.variantId}><td><input aria-label={`Select ${v.displayLabel}`} type="checkbox" checked={selected.includes(v.variantId)} onChange={e=>setSelected(s=>e.target.checked?[...s,v.variantId]:s.filter(id=>id!==v.variantId))}/></td><td>{(a?.images[0]?.url||a?.providerImage)&&<img src={displayCommerceMedia(a?.images[0]?.url||a?.providerImage||'')} alt=""/>}<strong>{v.displayLabel}</strong><small>{v.size} / {v.color}</small></td><td><input aria-label={`Price ${v.displayLabel}`} type="number" min={1} step={1} value={v.unitAmount} onChange={e=>variantChange(v.variantId,{unitAmount:Number(e.target.value)})}/></td><td>{v.availability}<button type="button" disabled={!data.providerValues.find(p=>p.variantId===v.variantId)?.unitAmount} onClick={()=>{const value=data.providerValues.find(p=>p.variantId===v.variantId)?.unitAmount;if(value)variantChange(v.variantId,{unitAmount:value});}}>Restore provider price</button></td><td><label><input type="checkbox" checked={v.sellable} onChange={e=>variantChange(v.variantId,{sellable:e.target.checked,status:e.target.checked?'active':'disabled',visibility:e.target.checked?'public':'private'})}/>Include</label>{r?.reasons.map(s=><small key={s}>{s}</small>)}</td><td>{data.shippingStrategy==='printful_dynamic'?'Automatic Printful rates':r?.shipping.weightMg?`${r.shipping.weightMg/1000} g · ${r.shipping.source}`:'Weight required'}</td></tr>})}</tbody></table></div><div className="workspace-tools"><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(filtered.length/pageSize))}</span><button type="button" disabled={page*pageSize>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button><select aria-label="Variants per page" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[20,50,75,100].map(n=><option key={n}>{n}</option>)}</select></div></section>}
 {tab==='Media'&&<section><h3>General images and variant assignments</h3><p>Choose variants above, then assign an image. Assignments survive provider sync. General images remain accessible.</p><div className="workspace-fields"><label>Upload designed image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/></label><label>Image URL<input type="url" value={mediaUrl} onChange={e=>setMediaUrl(e.target.value)}/></label><button type="button" onClick={()=>addImage(mediaUrl)}>Add image URL</button><label>Alt text<input maxLength={240} value={alt} onChange={e=>setAlt(e.target.value)}/></label></div><div className="workspace-media">{[...new Set([edit.primaryImageUrl,...edit.additionalImages].filter((v):v is string=>!!v))].map((url,index)=><article key={url}><img src={displayCommerceMedia(url)} alt={alt||edit.title}/><p>{index===0?'Primary image':`Image ${index+1}`}</p><button type="button" onClick={()=>change({primaryImageUrl:url,additionalImages:[...new Set([edit.primaryImageUrl,...edit.additionalImages].filter((u):u is string=>!!u&&u!==url))]})}>Make primary</button><button type="button" disabled={!selected.length} onClick={()=>assign(url)}>Assign to selected variants</button><button type="button" onClick={()=>change({primaryImageUrl:edit.primaryImageUrl===url?null:edit.primaryImageUrl,additionalImages:edit.additionalImages.filter(i=>i!==url)})}>Remove general association</button></article>)}</div>{assignments.filter(a=>selected.includes(a.variantId)).map(a=><p key={a.variantId}>{variants.find(v=>v.variantId===a.variantId)?.displayLabel}: {a.images.length} explicit images <button type="button" onClick={()=>{setAssignments(rows=>rows.map(r=>r.variantId===a.variantId?{...r,images:[]}:r));setDirty(true);}}>Use general media</button></p>)}</section>}
 {tab==='Shipping'&&<section><h3>{data.shippingStrategy==='printful_dynamic'?'Automatic Printful rates':'Merchant weight-based rates'}</h3><p>{data.shippingStrategy==='printful_dynamic'?'Printful calculates service and cost for the selected destination. Local shipping mass is optional and is not a purchase blocker.':'Customer charges use the published merchant ratebook. Each physical variant needs an effective weight.'}</p><p>Customer prices change only through the Shipping policy preview and save.</p><a href="/commerce/fulfillment#shipping-rates">Review shipping policy</a><details open={data.shippingStrategy==='merchant_weight_bands'}><summary>Weights and inheritance</summary><p>Variant override → product default → unknown. Existing values are operator-entered, not provider-verified.</p><div className="workspace-fields"><label>Weight<input inputMode="decimal" value={weightValue} onChange={e=>setWeightValue(e.target.value)}/></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}>{['mg','g','kg'].map(u=><option key={u}>{u}</option>)}</select></label></div><button type="button" disabled={!weightValue} onClick={()=>stageWeight([null],weightValue)}>Stage product default</button><button type="button" disabled={!weightValue||!selected.length} onClick={()=>stageWeight(selected,weightValue)}>Stage selected weights</button><button type="button" disabled={!selected.length} onClick={()=>stageWeight(selected,null)}>Reset selected to inheritance</button><p>{weights.length} staged changes</p>{data.weights.map(w=><p key={w.variant_id||'default'}>{w.variant_id?variants.find(v=>v.variantId===w.variant_id)?.displayLabel:'Product default'}: {w.weight_mg===null?'Unknown':`${w.weight_mg/1000} g`} · {w.provenance}</p>)}</details></section>}
 {tab==='Sync history and Issues'&&<section><h3>Provider and publication evidence</h3><p>Last provider read: {product.provider.lastSeenAt||'Unknown'}</p><p>Last saved: {data.product.updatedAt}</p>{data.readiness.productReasons.map(r=><p key={r}>{r}</p>)}{data.readiness.variants.map(v=><div key={v.id}><strong>{variants.find(r=>r.variantId===v.id)?.displayLabel}</strong>{[...v.reasons,...v.shipping.reasons].map(r=><p key={r}>{r} <button type="button" onClick={()=>setTab(r.startsWith('shipping')?'Shipping':'Variants')}>Repair field</button></p>)}</div>)}<details><summary>Advanced provider IDs</summary><pre>{JSON.stringify(product.integration,null,2)}</pre></details></section>}
 </fieldset>}</div><footer><p role="status">{busy?'Saving product and staging media…':dirty?'Unsaved changes':data?.saveResult?.message||'Product is up to date'}</p><button className="button-link" type="button" onClick={()=>void save()} disabled={busy||!data||!canManage||!csrfToken||!dirty}>Save product</button></footer></dialog>;
}
