import { useRef, useState, type CSSProperties } from 'react';
import { opponents, descendants, type Match } from './model.mjs';
import type { Bracket } from './types';
import './brackets.css';
import { statusLabel } from './status';


export function BracketCanvas({ bracket, onSelect, selected, mediaBase = '/api/brackets/media/' }: { bracket: Bracket; onSelect?: (m: Match) => void; selected?: string; mediaBase?: string }) {
  const { graph, decisions, sources, needsReview = [] } = bracket;
  const [zoom, setZoom] = useState(1), [round, setRound] = useState(0), [query, setQuery] = useState('');
  const viewport = useRef<HTMLDivElement>(null), shell = useRef<HTMLElement>(null), pan = useRef<{ x: number; y: number; left: number; top: number } | null>(null);
  const rounds = Array.from({ length: Math.log2(graph.size) }, (_, i) => i), path = selected ? [selected, ...descendants(graph, selected)] : [];
  const focus = () => { const c = graph.contenders.find(x => x.name.toLowerCase().includes(query.toLowerCase())); const m = graph.matches.find(x => opponents(graph, x, decisions).some(o => o?.id === c?.id)); if (m) { setRound(m.round); shell.current?.querySelector<HTMLElement>(`[data-match="${m.id}"]`)?.scrollIntoView({ block: 'center', inline: 'center', behavior: 'instant' }); onSelect?.(m); } };
  return <section ref={shell} className="bracket-canvas-shell" style={{ '--bracket-accent': graph.presentation.accent } as CSSProperties} aria-label="Season bracket">
    <div className="bracket-toolbar"><div><button onClick={() => setZoom(z => Math.max(.5, z - .1))} aria-label="Zoom out">−</button><output>{Math.round(zoom * 100)}%</output><button onClick={() => setZoom(z => Math.min(1.5, z + .1))} aria-label="Zoom in">+</button><button onClick={() => setZoom(Math.max(.5, Math.min(1, (viewport.current?.clientWidth || 1000) / (rounds.length * 280))))}>Fit view</button><button onClick={() => { setZoom(1); viewport.current?.scrollTo(0, 0); }}>Reset view</button><button onClick={() => { if (document.fullscreenElement) void document.exitFullscreen(); else void shell.current?.requestFullscreen(); }}>Fullscreen</button><button onClick={() => window.print()}>Print</button></div><div><input aria-label="Find contender" placeholder="Find a contender" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') focus(); }} /><button onClick={focus}>Focus</button></div></div>
    <div className="bracket-round-tabs" role="tablist" aria-label="Choose round">{rounds.map(r => <button key={r} role="tab" aria-selected={round === r} onClick={() => setRound(r)}>{r === rounds.length - 1 ? 'Final' : `Round ${r + 1}`}</button>)}</div>
    <div ref={viewport} className="bracket-viewport" tabIndex={0} aria-label="Bracket canvas. Scroll or drag empty space to pan." onPointerDown={e => { if ((e.target as HTMLElement).closest('button,input,a')) return; pan.current = { x: e.clientX, y: e.clientY, left: e.currentTarget.scrollLeft, top: e.currentTarget.scrollTop }; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (pan.current) { e.currentTarget.scrollLeft = pan.current.left + pan.current.x - e.clientX; e.currentTarget.scrollTop = pan.current.top + pan.current.y - e.clientY; } }} onPointerUp={() => { pan.current = null; }} onPointerCancel={() => { pan.current = null; }}>
      <div className="bracket-tree" style={{ zoom } as CSSProperties}>{rounds.map(r => <div key={r} className={`bracket-round ${round === r ? 'is-mobile-round' : ''}`}><h3>{r === rounds.length - 1 ? 'The final' : `Round ${r + 1}`}</h3><div className="bracket-round-matches">{graph.matches.filter(m => m.round === r).sort((a,b) => a.position - b.position).map(m => {
        const pair = opponents(graph, m, decisions), d = decisions.find(x => x.matchId === m.id), source = sources[m.id], review = needsReview.includes(m.id);
        return <div className="bracket-match-space" key={m.id}><button data-match={m.id} className={`bracket-match ${path.includes(m.id) ? 'is-path' : ''} ${review ? 'needs-review' : ''}`} onClick={() => onSelect?.(m)}><span className="bracket-match-kicker">Match {m.position + 1} <span>{review ? 'Needs review' : d ? d.source === 'poll' ? 'Confirmed result' : d.source === 'bye' ? 'Bye' : 'Manual result' : statusLabel(source?.state)}</span></span>{pair.map((c, i) => { const winner = d?.winnerId === c?.id && !!c && !review; return <span key={m.slots[i].id} className={`bracket-opponent ${winner ? 'is-winner' : d && c && !review ? 'is-eliminated' : ''}`}><span className="bracket-seed">{c?.seed ?? '·'}</span>{c?.image ? <img src={mediaBase + c.image} alt="" /> : <span className="bracket-monogram" aria-hidden="true">{c?.name.slice(0,1) || '?'}</span>}<span className="bracket-name">{c?.name || (m.slots[i].kind === 'bye' ? 'Bye' : m.slots[i].kind === 'winner' ? `Winner of match ${(graph.matches.find(x => x.id === m.slots[i].ref)?.position || 0) + 1}` : 'Unassigned')} {winner ? <small>WINNER</small> : null}</span><strong>{source?.scores && c ? source.scores[c.id] ?? '—' : d?.scores[i] ?? '—'}</strong></span>; })}</button></div>;
      })}</div></div>)}</div>
    </div>
  </section>;
}
