import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createCommerceDatabases, commerceEnvironment } from './commerce-test-helpers.mjs';
import { applyMigration } from './auth-test-helpers.mjs';
import { generate, referenceTemplate, duplicate, validate, uid, protectedMatchIds } from '../src/brackets/model.mjs';
import { createBracket, mutateBracket, publicBrackets, createMatchPoll, adminBracket, pollPicker, uploadBracketMedia, bracketMedia, importBracketImage } from '../functions/_shared/brackets-core.js';
import { createPoll, mutatePollCreatorGrant, changePollLifecycle, changePollVisibility, submitWebVote, updatePoll } from '../functions/_shared/polls-core.js';
import { createSession } from '../functions/_shared/auth-core.js';
import { onRequest as handler } from '../functions/api/admin/brackets/[[path]].js';
import sharp from 'sharp';
import { reconcilePollCredit } from '../functions/_shared/poll-credits.js';

test('reference seed order, historical results, graph validation and safe fresh import', () => {
  const { graph, historical } = referenceTemplate();
  assert.deepEqual(graph.contenders.map(c => c.seed), [1,16,9,8,5,12,13,4,3,14,11,6,7,10,15,2]);
  assert.equal(historical.length, 7); assert.deepEqual(historical[1].scores, [102,99]);
  assert.equal(historical[5].winnerId, graph.contenders[11].id);
  const copy = duplicate(graph); assert.equal(copy.matches.length, 15); assert.notEqual(copy.matches[0].id, graph.matches[0].id);
  for (const n of [4,8,16,32,64]) assert.equal(validate(generate(n)).matches.length, n - 1);
  const bad = structuredClone(graph); bad.matches[8].slots[0].ref = bad.matches[8].id; assert.throws(() => validate(bad));
  const placed = structuredClone(graph); placed.matches[0].slots[1].ref = placed.matches[0].slots[0].ref; assert.throws(() => validate(placed));
});

test('HTTP permission boundaries, reversed mappings, downstream protection, media retention and final correction', { timeout:120000 }, async t => {
  const h = await createCommerceDatabases({withMedia:true}); t.after(h.dispose);
  const env = commerceEnvironment(h,{THIRDRAILIFY_PROFILE_MEDIA:h.media});
  const at = new Date().toISOString(), actor='boundary-admin';
  for(const [id,role,level] of [[actor,'admin','full'],['ordinary','user','none'],['creator','user','none']]) await h.authDb.prepare("INSERT INTO accounts(id,email_normalized,display_name,role,admin_level,status,email_verified_at,created_at,updated_at,source) VALUES (?,?,?,?,?,'active',?,?,?,'test')").bind(id,`${id}@example.test`,id,role,level,at,at,at).run();
  await assert.rejects(createBracket(env,actor,{id:uid('bracket')}),/0043/);
  assert.equal((await h.commerceDb.prepare('SELECT COUNT(*) n FROM polls').first()).n,0);
  await applyMigration(h.commerceDb, await readFile(new URL('../commerce-migrations/0043_aboot_matchup_studio.sql',import.meta.url),'utf8'));
  await mutatePollCreatorGrant(env,actor,{accountId:'creator',action:'approve'}); const origin=env.THIRDRAILIFY_ADMIN_ORIGIN;
  assert.equal((await handler({env,request:new Request(origin+'/api/admin/brackets')})).status,401);
  for(const id of ['ordinary','creator']) {
    const account=await h.authDb.prepare('SELECT * FROM accounts WHERE id=?').bind(id).first(), session=await createSession(env,new Request(origin),account,origin);
    const response=await handler({env,request:new Request(origin+'/api/admin/brackets',{headers:{Cookie:session.cookie.split(';')[0]}})});assert.equal(response.status,403);
  }
  let b=(await createBracket(env,actor,{id:uid('bracket'),size:4,title:'Bounded acceptance'})).bracket;
  const action=async(name,extra={})=>{b=(await mutateBracket(env,b.id,actor,{action:name,revision:b.revision,requestId:uid('request'),...extra})).bracket;};
  const graph=structuredClone(b.graph); graph.contenders=['Alpha','Beta','Gamma'].map(name=>({id:uid('contender'),name,seed:null,description:'',notes:'',tags:'',image:null}));
  graph.matches[0].slots.forEach((s,i)=>{s.kind='contender';s.ref=graph.contenders[i].id;});graph.matches[1].slots[0].kind='contender';graph.matches[1].slots[0].ref=graph.contenders[2].id;graph.matches[1].slots[1].kind='bye';
  await action('save',{graph});
  const asset=await uploadBracketMedia(env,b.id,actor,await sharp({create:{width:32,height:32,channels:4,background:'#dfbd6a'}}).png().toBuffer(),'image/png');
  await assert.rejects(bracketMedia(env,asset.assetId),/not published/);
  graph.contenders[0].image=asset.assetId;await action('save',{graph});
  await action('publish',{presentation:{...graph.presentation,title:'Boundary roadmap',slug:'boundary-roadmap',feature:asset.assetId}});
  assert.equal((await bracketMedia(env,asset.assetId)).status,200);
  const working=structuredClone(b.graph);working.contenders[0].image=null;working.presentation.feature=null;working.contenders.push({id:uid('contender'),name:'PRIVATE ALTERNATE',seed:null,description:'DO NOT PUBLISH',notes:'secret',tags:'secret',image:null});await action('save',{graph:working});
  assert.equal((await bracketMedia(env,asset.assetId)).status,200);assert.ok(!JSON.stringify(await publicBrackets(env,'boundary-roadmap')).includes('PRIVATE'));
  const p=(await createPoll(env,actor,{title:'Beta versus Alpha',presentationType:'abootnothing',options:[{label:'Beta',trigger:'beta'},{label:'Alpha',trigger:'alpha'}]})).poll;
  await action('link',{matchId:graph.matches[0].id,pollId:p.id,mapping:{[graph.contenders[0].id]:p.options[1].id,[graph.contenders[1].id]:p.options[0].id}});
  await assert.rejects(updatePoll(env,actor,p.slug,{revision:p.revision,title:p.title,presentationType:'abootnothing',options:p.options.map(o=>({...o,label:'Replacement'}))}),/canonical bracket/);
  let p2=(await changePollLifecycle(env,actor,p.slug,{action:'open',revision:p.revision})).poll;
  await submitWebVote(env,{namespace:'web_anonymous',key:'boundary-viewer'},p.slug,{optionId:p.options[1].id});
  p2=(await changePollLifecycle(env,actor,p.slug,{action:'close',revision:p2.revision})).poll;
  b=(await adminBracket(env,b.id,actor)).bracket;await action('advance',{matchId:graph.matches[0].id,source:'poll',fingerprint:b.sources[graph.matches[0].id].fingerprint});
  await action('advance',{matchId:graph.matches[1].id,source:'bye'});
  const withArtwork=structuredClone(b.graph);withArtwork.contenders[0].image=asset.assetId;await action('save',{graph:withArtwork});
  b=(await createMatchPoll(env,b.id,actor,{matchId:graph.matches[2].id,revision:b.revision,requestId:uid('request')})).bracket;
  assert.equal((await h.commerceDb.prepare('SELECT COUNT(*) n FROM poll_media_assets').first()).n,1);
  await assert.rejects(mutateBracket(env,b.id,actor,{action:'rollback',matchId:graph.matches[0].id,reason:'Review changed result',revision:b.revision,requestId:uid('request')}),/downstream Poll is protected/);
  const down=b.sources[graph.matches[2].id];let dp=(await changePollLifecycle(env,actor,down.slug,{action:'open',revision:down.revision})).poll;
  dp=(await changePollLifecycle(env,actor,down.slug,{action:'close',revision:dp.revision})).poll;
  b=(await adminBracket(env,b.id,actor)).bracket;
  assert.equal(b.sources[graph.matches[2].id].state,'no_votes');
  await assert.rejects(mutateBracket(env,b.id,actor,{action:'advance',matchId:graph.matches[2].id,source:'poll',fingerprint:b.sources[graph.matches[2].id].fingerprint,revision:b.revision,requestId:uid('request')}),/closed, settled/);
  await action('advance',{matchId:graph.matches[2].id,source:'override',winnerId:graph.contenders[0].id,reason:'Explicit acceptance tie-break with no Poll votes',fingerprint:b.sources[graph.matches[2].id].fingerprint});
  await action('finalize');assert.equal(b.finalized,true);
  await assert.rejects(mutateBracket(env,b.id,actor,{action:'save',graph:b.graph,revision:b.revision,requestId:uid('request')}),/Reopen/);
  p2=(await changePollVisibility(env,actor,p.slug,{revision:p2.revision,public:false})).poll;
  const hidden=await publicBrackets(env,'boundary-roadmap');assert.equal(hidden.bracket.finalized,false);assert.equal(hidden.bracket.decisions.some(d=>d.matchId===graph.matches[0].id),false);assert.equal(hidden.bracket.sources[graph.matches[0].id].slug,undefined);
  await action('reopen',{reason:'Audited acceptance correction'});await action('detach',{matchId:graph.matches[2].id,reason:'Preserve original downstream Poll'});await action('rollback',{matchId:graph.matches[0].id,reason:'Recheck the upstream outcome'});
  assert.equal((await h.commerceDb.prepare('SELECT COUNT(*) n FROM poll_votes').first()).n,1);
  assert.ok((await h.commerceDb.prepare('SELECT COUNT(*) n FROM aboot_decisions WHERE superseded=1').first()).n>=2);
  await action('unpublish');await assert.rejects(bracketMedia(env,asset.assetId),/not published/);
  assert.equal((await h.commerceDb.prepare('PRAGMA foreign_key_check').all()).results.length,0);
});

test('real D1 private/public isolation, idempotent Poll linkage, settlement and revision safety', { timeout: 120000 }, async t => {
  const h = await createCommerceDatabases({ withMedia: true }); t.after(h.dispose);
  await applyMigration(h.commerceDb, await readFile(new URL('../commerce-migrations/0043_aboot_matchup_studio.sql', import.meta.url), 'utf8'));
  const env = commerceEnvironment(h, { THIRDRAILIFY_PROFILE_MEDIA: h.media });
  const at = new Date().toISOString();
  await h.authDb.prepare("INSERT INTO accounts(id,email_normalized,display_name,role,admin_level,status,email_verified_at,created_at,updated_at,source) VALUES ('studio-admin','studio@example.test','Studio Admin','admin','full','active',?,?,?,'test')").bind(at,at,at).run();
  const actor = 'studio-admin';
  let b = (await createBracket(env, actor, { id: uid('bracket'), template: 'reference' })).bracket;
  assert.equal(b.decisions.length, 7); assert.equal(b.published, false); assert.equal((await publicBrackets(env)).items.length, 0);
  const request = (action, extra = {}) => ({ action, revision: b.revision, requestId: uid('request'), ...extra });
  const old = request('save', { graph: b.graph });
  const p = { ...b.graph.presentation, title: 'Acceptance roadmap', slug: 'acceptance-roadmap' };
  b = (await mutateBracket(env, b.id, actor, request('publish', { presentation: p }))).bracket;
  await assert.rejects(mutateBracket(env, b.id, actor, old), /Another administrator/);
  const graph = structuredClone(b.graph); graph.contenders[0].notes = 'PRIVATE NOTE'; graph.presentation.intro = 'PRIVATE EDIT';
  b = (await mutateBracket(env, b.id, actor, request('save', { graph }))).bracket;
  const publicBefore = JSON.stringify(await publicBrackets(env, 'acceptance-roadmap'));
  assert.ok(!publicBefore.includes('PRIVATE')); assert.ok(!publicBefore.includes('historical manual result'));
  const mid = b.graph.matches.find(m => m.round === 0 && m.position === 7).id;
  const create = { ...request('create_poll'), matchId: mid };
  b = (await createMatchPoll(env, b.id, actor, create)).bracket;
  await createMatchPoll(env, b.id, actor, create);
  assert.equal((await h.commerceDb.prepare('SELECT COUNT(*) n FROM polls').first()).n, 1);
  const source = b.sources[mid], link = b.links.find(l => l.matchId === mid);
  assert.equal(source.state, 'scheduled');
  assert.equal((await pollPicker(env, actor)).items.length, 1);
  await assert.rejects(mutateBracket(env, b.id, actor, request('advance', { matchId: mid, source: 'poll', fingerprint: source.fingerprint })), /closed, settled/);
  let poll = (await changePollLifecycle(env, actor, source.slug, { revision: source.revision, action: 'open' })).poll;
  await submitWebVote(env, { namespace: 'web_anonymous', key: 'test-studio-viewer', label: null }, source.slug, { optionId: Object.values(link.mapping)[0] });
  poll = (await changePollLifecycle(env, actor, source.slug, { revision: poll.revision, action: 'close' })).poll;
  b = (await adminBracket(env, b.id, actor)).bracket;
  // Local D1 fixture: earned but unresolved gift credit. Reconcile through the real ledger.
  const windowId=uid('window'),lotId=uid('lot');
  await h.commerceDb.prepare("INSERT INTO poll_voting_windows(id,poll_id,source_scope,opened_at,ended_at,policy_revision,policy_json,options_json,stream_mode,created_at) VALUES (?,?,'user:local-studio',?,?,1,'{}',?,'automatic',?)").bind(windowId,source.pollId,at,at,JSON.stringify(poll.options),at).run();
  await h.commerceDb.prepare("INSERT INTO poll_credit_lots(id,event_fingerprint,poll_id,window_id,kind,source_scope,provider_event_at,evidence_json,policy_json,earned,unreconciled,max_messages,expires_at,created_at,updated_at) VALUES (?,?,?,?,'gift','user:local-studio',?,'{}','{}',5,5,3,?,?,?)").bind(lotId,uid('event'),source.pollId,windowId,at,at,at,at).run();
  b=(await adminBracket(env,b.id,actor)).bracket;
  assert.equal(b.sources[mid].state,'unsettled');
  await assert.rejects(mutateBracket(env,b.id,actor,request('advance',{matchId:mid,source:'poll',fingerprint:b.sources[mid].fingerprint})),/closed, settled/);
  await reconcilePollCredit(env,actor,{lotId,revision:1,requestId:uid('request'),action:'allocate',amount:5,optionId:Object.values(link.mapping)[0],reason:'Local ledger integration acceptance'});
  b=(await adminBracket(env,b.id,actor)).bracket;assert.equal(b.sources[mid].totalVotes,6);
  const advance = request('advance', { matchId: mid, source: 'poll', fingerprint: b.sources[mid].fingerprint });
  b = (await mutateBracket(env, b.id, actor, advance)).bracket;
  await mutateBracket(env, b.id, actor, advance); assert.equal(b.decisions.length, 8);
  await changePollLifecycle(env, actor, source.slug, { revision: poll.revision, action: 'open' });
  b = (await adminBracket(env, b.id, actor)).bracket; assert.ok(b.needsReview.includes(mid));
  b = (await mutateBracket(env, b.id, actor, request('unpublish'))).bracket;
  await assert.rejects(publicBrackets(env, 'acceptance-roadmap'), /not published/);
  assert.equal((await h.commerceDb.prepare('SELECT COUNT(*) n FROM poll_votes').first()).n, 1);
});


test('partial seasons allow unrelated placement and names while protecting result inputs and tree identity', { timeout:120000 }, async t => {
  const h=await createCommerceDatabases({withMedia:true});t.after(h.dispose);const env=commerceEnvironment(h,{THIRDRAILIFY_PROFILE_MEDIA:h.media});
  await applyMigration(h.commerceDb,await readFile(new URL('../commerce-migrations/0043_aboot_matchup_studio.sql',import.meta.url),'utf8'));
  const actor='partial-admin',at=new Date().toISOString();await h.authDb.prepare("INSERT INTO accounts(id,email_normalized,display_name,role,admin_level,status,email_verified_at,created_at,updated_at,source) VALUES (?,?,'Partial Admin','admin','full','active',?,?,?,'test')").bind(actor,actor+'@example.test',at,at,at).run();
  let b=(await createBracket(env,actor,{id:uid('bracket'),size:8,title:'Partial field'})).bracket;
  const act=async(action,extra={})=>{b=(await mutateBracket(env,b.id,actor,{action,revision:b.revision,requestId:uid('request'),...extra})).bracket;};
  const g=structuredClone(b.graph);g.contenders=['Alpha','Beta','Gamma','Delta','Epsilon','Zeta','Eta','Theta','Alternate'].map(name=>({id:uid('contender'),name,seed:null,description:'',image:null}));g.matches.filter(m=>m.round===0).forEach((m,i)=>m.slots.forEach((s,j)=>{s.kind='contender';s.ref=g.contenders[i*2+j].id;}));await act('save',{graph:g});
  await act('advance',{matchId:g.matches[0].id,source:'historical',winnerId:g.contenders[0].id,scores:[3,2],reason:'Recorded first match'});
  assert.deepEqual(protectedMatchIds(b.graph,b.decisions),[g.matches[0].id]);
  const edited=structuredClone(b.graph);edited.matches[2].slots[0].ref=edited.contenders[8].id;edited.contenders[5].name='Zeta revised';edited.contenders.push({id:uid('contender'),name:'New idea',seed:null,description:'',image:null});await act('save',{graph:edited});assert.equal(b.decisions.length,1);assert.equal(b.graph.matches[2].slots[0].ref,edited.contenders[8].id);
  const rejected=async(graph)=>assert.rejects(mutateBracket(env,b.id,actor,{action:'save',graph,revision:b.revision,requestId:uid('request')}),/protect contender identity/);
  const renamed=structuredClone(b.graph);renamed.contenders[0].name='Changed winner';await rejected(renamed);
  const swapped=structuredClone(b.graph);[swapped.matches[0].slots[0].ref,swapped.matches[1].slots[0].ref]=[swapped.matches[1].slots[0].ref,swapped.matches[0].slots[0].ref];await rejected(swapped);
  const rewired=structuredClone(b.graph);rewired.matches[3].id=uid('match');rewired.matches[5].slots[1].ref=rewired.matches[3].id;await rejected(rewired);
  const ancestry=protectedMatchIds(b.graph,[{matchId:g.matches[4].id}]);assert.deepEqual(new Set(ancestry),new Set([g.matches[4].id,g.matches[0].id,g.matches[1].id]));assert.ok(!ancestry.includes(g.matches[2].id));
  b=(await createMatchPoll(env,b.id,actor,{matchId:g.matches[2].id,revision:b.revision,requestId:uid('request')})).bracket;
  const linkedEdit=structuredClone(b.graph);linkedEdit.contenders[8].name='Changed linked opponent';await rejected(linkedEdit);
  const otherEdit=structuredClone(b.graph);otherEdit.contenders[6].name='Editable other branch';await act('save',{graph:otherEdit});assert.equal(b.graph.contenders[6].name,'Editable other branch');
  const png=await sharp({create:{width:32,height:24,channels:4,background:'#cfaa35'}}).png().toBuffer();let fetched=0;
  const fetchImage=async(url,init)=>{fetched++;assert.equal(url,'https://images.example.com/item.png');assert.equal(init.redirect,'manual');assert.deepEqual(Object.keys(init.headers),['Accept']);return new Response(png,{headers:{'content-type':'image/png'}});};
  for(const url of ['http://example.com/image.png','https://127.0.0.1/a.png','https://[::1]/a.png','https://localhost/a.png','https://files.internal/a.png','https://user:password@example.com/a.png','https://example.com:8443/a.png']) await assert.rejects(importBracketImage(env,b.id,actor,url,fetchImage),/HTTPS/);
  assert.equal(fetched,0);const image=await importBracketImage(env,b.id,actor,'https://images.example.com/item.png',fetchImage);assert.ok(image.assetId);assert.equal((await bracketMedia(env,image.assetId,true)).status,200);await assert.rejects(bracketMedia(env,image.assetId),/not published/);
  const count=(await h.commerceDb.prepare('SELECT COUNT(*) n FROM aboot_media').first()).n;
  await assert.rejects(importBracketImage(env,b.id,actor,'https://images.example.com/item.png',async()=>new Response(null,{status:302,headers:{Location:'https://127.0.0.1/a.png'}})),/direct image URL/);
  await assert.rejects(importBracketImage(env,b.id,actor,'https://images.example.com/item.png',async()=>new Response('<html/>',{headers:{'content-type':'text/html'}})),/directly/);
  await assert.rejects(importBracketImage(env,b.id,actor,'https://images.example.com/item.png',async()=>new Response(new Uint8Array(8*1024*1024+1),{headers:{'content-type':'image/png'}})),/8 MB/);
  await assert.rejects(importBracketImage(env,b.id,actor,'https://images.example.com/item.png',async()=>new Response('<html/>',{headers:{'content-type':'image/png'}})));
  assert.equal((await h.commerceDb.prepare('SELECT COUNT(*) n FROM aboot_media').first()).n,count);

});
