import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4199";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const RESULTS = join(tmpdir(), "thirdrailify-admin-commerce-browser");
const IMAGE = "https://static.wixstatic.com/media/admin-shop-v2-fixture.svg";

test("Admin Products and Collections render real imagery, scoped dirty rails, nested navigation, and assignment controls responsively", async (t) => {
  await mkdir(RESULTS, { recursive: true }); const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "4199"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForServer();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const [width, height] of [[1440,900],[1024,768],[768,1024],[390,844]]) {
    const { context, page, errors, imageResponses } = await fixturePage(browser, width, height); await page.goto(`${ORIGIN}/products`); await page.getByRole("heading", { level: 1, name: "Shop / Products" }).waitFor();
    if (width <= 768) await page.getByRole("button", { name: "Open navigation" }).click();
    const nav = page.locator("#admin-sidebar"); assert.equal(await nav.getByRole("link", { name: "Products" }).count(), 1); assert.equal(await nav.getByRole("link", { name: "Collections" }).count(), 1); assert.equal(await nav.getByRole("link", { name: "Orders" }).count(), 1); assert.equal(await nav.getByRole("link", { name: "Orders" }).allTextContents().then((items) => items.length), 1);
    if (width <= 768) await page.keyboard.press("Escape");
    await page.locator(".commerce-product-row img").first().waitFor(); const dimensions = await page.locator(".commerce-product-row img").evaluateAll((images) => images.map((image) => ({ width: image.naturalWidth, height: image.naturalHeight }))); assert.ok(dimensions.length === 3 && dimensions.every((item) => item.width > 0 && item.height > 0)); assert.ok(imageResponses.length >= 1);
    assert.equal(await page.getByText("Featured order changed", { exact: true }).count(), 0); await page.getByRole("button", { name: "Move BLEH | Unisex classic tee down" }).click(); assert.equal(await page.getByText("Featured order changed", { exact: true }).count(), 1); await page.getByRole("button", { name: "Discard changes" }).click(); assert.equal(await page.getByText("Featured order changed", { exact: true }).count(), 0);
    const editButton = page.getByRole("button", { name: "Edit product" }).first(); await editButton.click(); const productDialog = page.getByRole("dialog", { name: "BLEH | Unisex classic tee" }); await productDialog.waitFor(); assert.equal(await page.evaluate(() => document.body.style.overflow), "hidden"); assert.equal(await productDialog.locator(".commerce-product-editor").count(), 1); assert.equal(await productDialog.evaluate((dialog) => dialog.parentElement?.parentElement === document.body), true); assert.equal(await productDialog.getByRole("button", { name: "Close editor" }).evaluate((button) => getComputedStyle(button).color !== "rgb(128, 128, 128)"), true); const box = await productDialog.boundingBox(); assert.ok(box && box.y >= 0 && box.y + box.height <= height + 1); if (width === 1440 || width === 390) await page.screenshot({ path: `${RESULTS}/product-editor-${width}x${height}.png` }); await page.keyboard.press("Escape"); assert.equal(await productDialog.count(), 0); assert.equal(await editButton.evaluate((button) => document.activeElement === button), true);
    assert.equal(await noOverflow(page), true); assert.deepEqual(errors, []); if (width === 1440 || width === 390) await page.screenshot({ path: `${RESULTS}/products-${width}x${height}.png`, fullPage: true }); await context.close();
  }
  for (const [width, height] of [[1440,900],[1024,768],[768,1024],[390,844]]) {
    const { context, page, errors } = await fixturePage(browser, width, height); await page.goto(`${ORIGIN}/collections`); await page.getByRole("heading", { level: 1, name: "Shop / Collections" }).waitFor();
    assert.equal(await page.getByText("All Products", { exact: true }).count() >= 1, true); assert.equal(await page.getByText("Apparel", { exact: true }).count() >= 1, true); assert.equal(await page.getByText("Headwear", { exact: true }).count() >= 1, true);
    const manageButton = page.getByRole("button", { name: "Manage" }).first(); assert.equal(await manageButton.evaluate((button) => getComputedStyle(button).backgroundColor === "rgb(243, 201, 40)"), true); await manageButton.click(); const collectionDialog = page.getByRole("dialog", { name: "Apparel" }); await collectionDialog.waitFor(); assert.equal(await page.evaluate(() => document.body.style.overflow), "hidden"); assert.equal(await collectionDialog.evaluate((dialog) => dialog.parentElement?.parentElement === document.body), true); assert.equal(await page.getByLabel("Search products for assignment").count(), 1); assert.equal(await page.getByLabel("Filter product assignments").count(), 1); assert.equal(await page.getByRole("group", { name: "Product assignments" }).locator("img").count(), 3); const box = await collectionDialog.boundingBox(); assert.ok(box && box.y >= 0 && box.y + box.height <= height + 1);
    await page.getByLabel("Search products for assignment").fill("BLEH"); assert.equal(await page.getByRole("group", { name: "Product assignments" }).locator("label").count(), 1); assert.equal(await noOverflow(page), true); assert.deepEqual(errors, []); if (width === 1440 || width === 390) await page.screenshot({ path: `${RESULTS}/collections-${width}x${height}.png` }); await page.getByRole("button", { name: "Close editor" }).click(); assert.equal(await collectionDialog.count(), 0); assert.equal(await manageButton.evaluate((button) => document.activeElement === button), true); await context.close();
  }
});

async function fixturePage(browser, width, height) { const context = await browser.newContext({ viewport: { width, height }, reducedMotion: "reduce" }); const page = await context.newPage(); const errors = []; const imageResponses = []; page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); page.on("pageerror", (error) => errors.push(error.message)); page.on("response", (response) => { if (response.url() === IMAGE && response.ok()) imageResponses.push(response.status()); });
  await page.route(IMAGE, (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="750"><rect width="100%" height="100%" fill="#161616"/><path d="M80 375h440" stroke="#f2c94c" stroke-width="44"/><text x="300" y="330" fill="white" text-anchor="middle" font-size="58">TR SHOP</text></svg>` }));
  await page.route("**/api/**", async (route) => { const path = new URL(route.request().url()).pathname;
    if (path === "/api/auth/config") return json(route, authConfig()); if (path === "/api/auth/session") return json(route, session());
    if (path === "/api/admin/commerce/products") return json(route, productsPayload()); if (path === "/api/admin/commerce/collections") return json(route, collectionsPayload());
    if (path === "/api/admin/commerce/products/featured" && route.request().method() === "POST") { const ids = JSON.parse(route.request().postData() || "{}").featuredIds || []; const payload = productsPayload(); payload.featured = ids.map((id, index) => ({ ...payload.products.find((product) => product.id === id), featured: true, featuredOrder: (index + 1) * 10 })); payload.products = payload.products.map((product) => { const index = ids.indexOf(product.id); return { ...product, featured: index >= 0, featuredOrder: index >= 0 ? (index + 1) * 10 : null }; }); return json(route, payload); }
    return json(route, { ok: false, error: "not_found" }, 404);
  }); return { context, page, errors, imageResponses }; }
function baseProduct(id, slug, title, collectionIds, featured, featuredOrder, displayOrder) { return { id, slug, title, description: "Fixture product", primaryImageUrl: IMAGE, additionalImages: [], categories: collectionIds.includes("collection-apparel") ? ["Apparel"] : ["Headwear"], collectionIds, tags: [], status: "active", visibility: "public", currencyCode: "CAD", unitAmount: 3050, price: { minimum: 3050, maximum: 3050, label: "CA$30.50" }, maxQuantity: 5, requiresShipping: true, featured, featuredOrder, displayOrder, migrationStatus: "target_verified", sourceProvider: "commerce-d1", integration: {}, variantCount: 1, activeVariantCount: 1, sellableVariantCount: 0, readiness: { displayable: true, checkout: false, fulfillment: "mapped" }, variants: [{ id: `${id}-v1`, productId: id, localVariantKey: "M/Black", displayLabel: "M / Black", status: "active", visibility: "public", sellable: false, availability: "active", unitAmount: 3050, currencyCode: "CAD", sku: null, size: "M", color: "Black", options: { Size: "M", Color: "Black" }, fulfillmentProvider: "printful", fulfillmentMappingStatus: "mapped", migrationStatus: "target_verified", integration: {}, updatedAt: "2026-08-29T00:00:00.000Z" }], displayData: { hasImage: true, hasPrice: true, ready: true }, updatedAt: "2026-08-29T00:00:00.000Z" }; }
function productList() { return [baseProduct("p1", "bleh-tee", "BLEH | Unisex classic tee", ["collection-apparel"], true, 10, 10), baseProduct("p2", "icon-hat", "Third Railify Icon | Dad hat", ["collection-headwear"], true, 20, 20), baseProduct("p3", "logo-v2-tee", "Third Railify Logo V2 | Unisex classic tee", ["collection-apparel"], false, null, 30)]; }
function access() { return { isMasterAdmin: true, capabilities: ["commerce.view", "commerce.business.manage"] }; } function productsPayload() { const products = productList(); return { ok: true, databaseConfigured: true, access: access(), products, featured: products.filter((product) => product.featured), updatedAt: "2026-08-29T00:00:00.000Z" }; }
function collectionsPayload() { const products = productList(); return { ok: true, databaseConfigured: true, access: access(), collections: [{ id: "collection-apparel", slug: "apparel", title: "Apparel", description: "Wear the signal.", visibility: "public", status: "active", displayOrder: 10, revision: 1, assignedProductCount: 2, publicProductCount: 2, productIds: ["p1", "p3"], createdAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }, { id: "collection-headwear", slug: "headwear", title: "Headwear", description: "Top the line.", visibility: "public", status: "active", displayOrder: 20, revision: 1, assignedProductCount: 1, publicProductCount: 1, productIds: ["p2"], createdAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }], products, updatedAt: "2026-08-29T00:00:00.000Z" }; }
function session() { return { ok: true, authenticated: true, csrfToken: "browser-fixture-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master Admin", username: null, avatarUrl: null, providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", lastLoginAt: null, source: "test", locked: true } }; }
function authConfig() { return { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); } function noOverflow(page) { return page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth); }
async function waitForServer() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Admin commerce test server did not start."); }
