import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4199";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const RESULTS = join(tmpdir(), "thirdrailify-admin-commerce-browser");
const IMAGE = "https://static.wixstatic.com/media/admin-shop-v2-fixture.svg";
const IMAGE_TWO = "https://static.wixstatic.com/media/admin-shop-v2-back.svg";
const IMAGE_THREE = "https://static.wixstatic.com/media/admin-shop-v2-detail.svg";
const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");

test("Admin Products and Collections render real imagery, scoped dirty rails, nested navigation, and assignment controls responsively", async (t) => {
  await mkdir(RESULTS, { recursive: true }); const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "4199"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForServer();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const [width, height] of [[1920,1080],[1440,900],[768,1024],[390,844]]) {
    const { context, page, errors, imageResponses, savedBodies } = await fixturePage(browser, width, height); await page.goto(`${ORIGIN}/products`); try { await page.getByRole("heading", { level: 1, name: "Shop / Products" }).waitFor({ timeout: 10_000 }); } catch (reason) { throw new Error("Products page did not render: " + errors.join(" | "), { cause: reason }); }
    await page.getByRole("heading", { level: 2, name: "Printful catalogue reconciliation" }).waitFor(); assert.equal(await page.getByText(/Configured store 18668025/).count(), 1); assert.equal(await page.getByRole("button", { name: "Preview reconciliation" }).isEnabled(), true);
    if (width <= 768) await page.getByRole("button", { name: "Open navigation" }).click();
    const nav = page.locator("#admin-sidebar"); assert.equal(await nav.getByRole("link", { name: "Products" }).count(), 1); assert.equal(await nav.getByRole("link", { name: "Collections" }).count(), 1); assert.equal(await nav.getByRole("link", { name: "Orders" }).count(), 1); assert.equal(await nav.getByRole("link", { name: "Orders" }).allTextContents().then((items) => items.length), 1);
    if (width <= 768) await page.keyboard.press("Escape");
    await page.locator(".commerce-product-row img").first().waitFor(); const dimensions = await page.locator(".commerce-product-row img").evaluateAll((images) => images.map((image) => ({ width: image.naturalWidth, height: image.naturalHeight }))); assert.ok(dimensions.length === 3 && dimensions.every((item) => item.width > 0 && item.height > 0)); assert.ok(imageResponses.length >= 1);
    const visibilityButton = page.getByRole("button", { name: "Hide BLEH | Unisex classic tee from store" }); await visibilityButton.click(); await page.getByRole("button", { name: "Show BLEH | Unisex classic tee in store" }).waitFor();
    await page.getByRole("button", { name: "Bulk edit" }).click(); await page.getByRole("button", { name: "Select current page" }).click(); assert.equal(await page.getByText("3 selected", { exact: true }).count(), 1); await page.getByRole("button", { name: "Hide from store", exact: true }).click(); await page.getByText(/Hide from store completed/).waitFor();
    assert.equal(await page.getByText("Featured order changed", { exact: true }).count(), 0); await page.getByRole("button", { name: "Move BLEH | Unisex classic tee down" }).click(); assert.equal(await page.getByText("Featured order changed", { exact: true }).count(), 1); await page.getByRole("button", { name: "Discard", exact: true }).click(); assert.equal(await page.getByText("Featured order changed", { exact: true }).count(), 0);
    const featuredButton = page.getByRole("button", { name: "Remove BLEH | Unisex classic tee from featured products" }).first();
    const unfeaturedButton = page.getByRole("button", { name: "Add Third Railify Logo V2 | Unisex classic tee to featured products" }).first();
    assert.notEqual(await featuredButton.locator("svg").evaluate((icon) => getComputedStyle(icon).fill), "none", `featured star is filled at ${width}x${height}`);
    assert.equal(await unfeaturedButton.locator("svg").evaluate((icon) => getComputedStyle(icon).fill), "none", `unfeatured star remains outlined at ${width}x${height}`);
    await unfeaturedButton.click(); await page.getByText("3 featured", { exact: true }).waitFor();
    const newlyFeaturedButton = page.getByRole("button", { name: "Remove Third Railify Logo V2 | Unisex classic tee from featured products" }).first();
    assert.notEqual(await newlyFeaturedButton.locator("svg").evaluate((icon) => getComputedStyle(icon).fill), "none", `newly featured star becomes filled at ${width}x${height}`);
    const editButton = page.getByRole("button", { name: "Edit product" }).first(); await editButton.click(); const productDialog = page.getByRole("dialog", { name: "BLEH | Unisex classic tee" }); await productDialog.waitFor(); assert.equal(await page.evaluate(() => document.body.style.overflow), "hidden"); assert.equal(await productDialog.locator(".commerce-product-editor").count(), 1); assert.equal(await productDialog.evaluate((dialog) => dialog.parentElement?.parentElement === document.body), true); assert.equal(await productDialog.getByRole("button", { name: "Close editor" }).evaluate((button) => getComputedStyle(button).color !== "rgb(128, 128, 128)"), true);
    assert.equal(await productDialog.getByRole("group", { name: "Product media" }).count(), 1); assert.equal(await productDialog.getByRole("button", { name: "Use image URL" }).count(), 1); assert.equal(await productDialog.getByRole("button", { name: "Add by URL" }).count(), 1); assert.equal(await productDialog.getByLabel("Upload / replace image").count(), 1); assert.equal(await productDialog.getByLabel("Add images").getAttribute("multiple"), ""); assert.equal(await productDialog.locator(".product-media-gallery > li").count(), 2); assert.equal(await productDialog.getByText("Preview unavailable", { exact: true }).count(), 1);
    const collectionCard = productDialog.locator('label[for="product-collection-collection-headwear"]'); const collectionCheckbox = productDialog.locator("#product-collection-collection-headwear"); const collectionCardBox = await collectionCard.boundingBox(); assert.ok(collectionCardBox); assert.equal(await collectionCheckbox.isChecked(), false); assert.equal(await collectionCard.evaluate((label) => getComputedStyle(label).cursor), "pointer"); await collectionCard.click({ position: { x: collectionCardBox.width - 10, y: collectionCardBox.height / 2 } }); assert.equal(await collectionCheckbox.isChecked(), true, `the collection card toggles its checkbox at ${width}x${height}`); if (width === 1440 || width === 390) await productDialog.locator(".commerce-collection-picker").screenshot({ path: `${RESULTS}/product-collection-picker-${width}x${height}.png` }); await collectionCard.click({ position: { x: collectionCardBox.width - 10, y: collectionCardBox.height / 2 } }); assert.equal(await collectionCheckbox.isChecked(), false);
    const primaryBadgeStar = productDialog.locator(".product-media-primary-badge svg");
    const setPrimaryButton = productDialog.getByRole("button", { name: "Set additional image 1 as primary" });
    assert.notEqual(await primaryBadgeStar.evaluate((icon) => getComputedStyle(icon).fill), "none", `current primary star is filled at ${width}x${height}`);
    assert.equal(await setPrimaryButton.locator("svg").evaluate((icon) => getComputedStyle(icon).fill), "none", `Set as primary star remains outlined at ${width}x${height}`);
    await setPrimaryButton.click(); assert.equal(await productDialog.locator(".product-media-primary img").getAttribute("src"), IMAGE_TWO);
    assert.notEqual(await primaryBadgeStar.evaluate((icon) => getComputedStyle(icon).fill), "none", `promoted primary star is filled at ${width}x${height}`);
    assert.equal(await productDialog.getByRole("button", { name: "Set additional image 1 as primary" }).locator("svg").evaluate((icon) => getComputedStyle(icon).fill), "none", `former primary returns to an outlined action at ${width}x${height}`);
    await productDialog.getByRole("button", { name: "Move additional image 2 earlier" }).click(); await productDialog.getByRole("button", { name: "Remove additional image 2" }).click(); assert.equal(await productDialog.locator(".product-media-gallery > li").count(), 1);
    await productDialog.getByLabel("Title").fill("BLEH edited but unsaved"); await productDialog.getByLabel("Upload / replace image").setInputFiles({ name: "new-primary.png", mimeType: "image/png", buffer: PNG }); await productDialog.getByText("new-primary.png").waitFor(); await productDialog.getByText(/Uploaded .* save product to publish/).waitFor();
    await productDialog.getByLabel("Add images").setInputFiles([{ name: "gallery-ok.png", mimeType: "image/png", buffer: PNG }, { name: "gallery-bad.svg", mimeType: "image/svg+xml", buffer: Buffer.from("<svg/>") }]); await productDialog.getByText("gallery-ok.png").waitFor(); await productDialog.getByText("gallery-bad.svg").waitFor(); await productDialog.getByText("The file must be a valid JPG, PNG, or WebP image.").waitFor(); assert.equal(await productDialog.getByLabel("Title").inputValue(), "BLEH edited but unsaved"); assert.equal(await productDialog.locator(".product-media-gallery > li").count(), 2); const expectedUploadFailure = errors.findIndex((message) => message.includes("415 (Unsupported Media Type)") && message.includes("/media/ingest")); assert.notEqual(expectedUploadFailure, -1); errors.splice(expectedUploadFailure, 1);
    const featuredSwitch = productDialog.getByRole("switch", { name: /Featured product/ }); assert.equal(await featuredSwitch.isChecked(), true); await productDialog.getByRole("button", { name: "Save product" }).click(); await page.getByText("Merchandising saved", { exact: true }).waitFor(); assert.equal(savedBodies.length, 1); assert.equal(savedBodies[0].title, "BLEH edited but unsaved"); assert.match(savedBodies[0].primaryImageUrl, new RegExp(`^${ORIGIN.replaceAll("/", "\\/")}\/commerce-media\/[a-f0-9]{64}\\.png$`)); assert.equal(savedBodies[0].additionalImages.length, 2); assert.ok(savedBodies[0].additionalImages.every((url) => /\/commerce-media\/[a-f0-9]{64}\.png$/.test(url)));
    const savedDialog = page.getByRole("dialog", { name: "BLEH edited but unsaved" }); const mediaSection = savedDialog.locator(".product-media-editor"); await mediaSection.evaluate((element) => element.scrollIntoView({ block: "start" })); if ([1440,768,390].includes(width)) await page.screenshot({ path: `${RESULTS}/product-media-editor-${width}x${height}.png` }); await savedDialog.locator(".commerce-featured-switch").evaluate((element) => element.scrollIntoView({ block: "center" })); const box = await savedDialog.boundingBox(); assert.ok(box && box.y >= 0 && box.y + box.height <= height + 1); assert.equal(await noOverflow(page), true); await page.keyboard.press("Escape"); await savedDialog.waitFor({ state: "detached" }); assert.equal(await editButton.evaluate((button) => document.activeElement === button), true);
    assert.equal(await noOverflow(page), true); assert.deepEqual(errors, []); if ([1920,1440,390].includes(width)) await page.screenshot({ path: `${RESULTS}/products-${width}x${height}.png`, fullPage: true }); await context.close();
  }
  for (const [width, height] of [[1440,900],[768,1024],[390,844]]) {
    const { context, page, errors } = await fixturePage(browser, width, height); await page.goto(`${ORIGIN}/collections`); await page.getByRole("heading", { level: 1, name: "Shop / Collections" }).waitFor();
    await page.getByText("Apparel", { exact: true }).first().waitFor(); assert.equal(await page.getByText("Headwear", { exact: true }).count() >= 1, true); assert.equal(await page.getByLabel("Search title, slug, description").count(), 1); assert.equal(await page.getByLabel("Rows per page").inputValue(), "20"); await page.screenshot({ path: `${RESULTS}/collections-list-${width}x${height}.png`, fullPage: true });
    const eye = page.getByRole("button", { name: "Hide Apparel from storefront" }); await eye.click(); await page.getByRole("button", { name: "Show Apparel on storefront" }).waitFor();
    await page.getByRole("button", { name: "Bulk edit" }).click(); await page.getByRole("button", { name: "Select current page" }).click(); assert.equal(await page.getByText("2 selected", { exact: true }).count(), 1); await page.getByRole("button", { name: "Show on storefront", exact: true }).click(); await page.getByText(/Show on storefront completed/).waitFor();
    const editButton = page.getByRole("button", { name: "Edit collection" }).first(); assert.equal(await editButton.evaluate((button) => getComputedStyle(button).backgroundColor === "rgb(243, 201, 40)"), true); await editButton.click(); const collectionDialog = page.getByRole("dialog", { name: "Apparel" }); await collectionDialog.waitFor(); assert.equal(await page.evaluate(() => document.body.style.overflow), "hidden"); assert.equal(await collectionDialog.evaluate((dialog) => dialog.parentElement?.parentElement === document.body), true); assert.equal(await collectionDialog.getByRole("switch", { name: "Show collection on storefront" }).count(), 1); assert.equal(await collectionDialog.getByText("No standalone collection image field exists.", { exact: false }).count(), 1); assert.equal(await collectionDialog.getByRole("heading", { name: "Assigned to this collection" }).count(), 1); assert.equal(await collectionDialog.getByRole("heading", { name: "Catalogue finder" }).count(), 1); assert.equal(await collectionDialog.getByLabel("Search products to add").count(), 1); const box = await collectionDialog.boundingBox(); assert.ok(box && box.y >= 0 && box.y + box.height <= height + 1);
    await collectionDialog.getByLabel("Search products to add").fill("Icon"); const addCheckbox = collectionDialog.getByRole("checkbox", { name: /Third Railify Icon/ }); await addCheckbox.check(); await collectionDialog.getByRole("button", { name: "Add selected (1)" }).click(); await page.getByText("1 product added to the collection.", { exact: true }).waitFor(); await collectionDialog.getByRole("button", { name: "Remove Third Railify Icon | Dad hat from collection" }).waitFor();
    await collectionDialog.getByLabel("Title").fill("Apparel unsaved"); assert.equal(await collectionDialog.getByText("Unsaved collection details.", { exact: false }).count(), 1); await collectionDialog.locator(".merchandising-savebar").evaluate((element) => element.scrollIntoView({ block: "end" })); assert.equal(await noOverflow(page), true); assert.deepEqual(errors, []); await page.screenshot({ path: `${RESULTS}/collections-${width}x${height}.png` }); page.once("dialog", (dialog) => void dialog.accept()); await page.getByRole("button", { name: "Close editor" }).click(); assert.equal(await collectionDialog.count(), 0); assert.equal(await editButton.evaluate((button) => document.activeElement === button), true); await context.close();
  }
});

test("rapid Featured changes stay targeted, preserve list state, and never multiply account or catalogue requests", async (t) => {
  await mkdir(RESULTS, { recursive: true }); const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "4199"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForServer();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  const { context, page, requestCounts, responseStatuses, errors } = await fixturePage(browser, 1440, 900, { products: stressProductList(50), featuredDelay: 75 }); t.after(() => context.close());
  await page.goto(`${ORIGIN}/products`); await page.getByRole("heading", { level: 1, name: "Shop / Products" }).waitFor();
  const search = page.locator(".commerce-product-filters input[type='search']"); await search.fill("Stress Product"); await page.getByText("Showing 1–20 of 50 products", { exact: true }).waitFor();
  const rows = page.locator(".commerce-product-table .commerce-product-row"); const initial = [];
  for (let index = 0; index < 10; index += 1) initial.push(await rows.nth(index).locator("button[aria-pressed]").nth(1).getAttribute("aria-pressed"));
  await page.evaluate(() => window.scrollTo(0, 520)); const scrollBefore = await page.evaluate(() => window.scrollY);
  const baseline = { ...requestCounts };
  for (let index = 0; index < 10; index += 1) await rows.nth(index).locator("button[aria-pressed]").nth(1).evaluate((button) => button.click());
  assert.equal(await rows.nth(15).getByRole("button", { name: "Edit product" }).isEnabled(), true, "unrelated rows remain interactive while Featured writes settle");
  await page.waitForFunction(() => !document.querySelector(".commerce-product-table .commerce-icon-action__pending"));
  for (let index = 0; index < 10; index += 1) await rows.nth(index).locator("button[aria-pressed]").nth(1).evaluate((button) => button.click());
  await page.waitForFunction(() => !document.querySelector(".commerce-product-table .commerce-icon-action__pending"));
  for (let index = 0; index < 10; index += 1) assert.equal(await rows.nth(index).locator("button[aria-pressed]").nth(1).getAttribute("aria-pressed"), initial[index]);
  assert.equal(requestCounts.featuredMutation - baseline.featuredMutation, 20); assert.equal(requestCounts.productList, baseline.productList); assert.equal(requestCounts.authSession, baseline.authSession); assert.equal(requestCounts.authConfig, baseline.authConfig);
  assert.equal(responseStatuses.includes(429), false); assert.equal(await page.getByText(/account service is unavailable/i).count(), 0); assert.equal(await search.inputValue(), "Stress Product"); assert.equal(await page.getByLabel("Rows per page").inputValue(), "20"); assert.equal(await page.locator('section[aria-labelledby="catalogue-products-title"]').getByText("Page 1 of 3", { exact: true }).count(), 1); assert.equal(await page.evaluate(() => window.scrollY), scrollBefore);

  const sameProduct = rows.nth(0).locator("button[aria-pressed]").nth(1); const sameBefore = requestCounts.featuredMutation; await sameProduct.evaluate((button) => { button.click(); button.click(); }); await page.waitForFunction(() => !document.querySelector(".commerce-product-table .commerce-icon-action__pending")); assert.equal(requestCounts.featuredMutation, sameBefore + 1, "same-product double intent is synchronously locked to one write"); await sameProduct.click(); await page.waitForFunction(() => !document.querySelector(".commerce-product-table .commerce-icon-action__pending")); assert.equal(await sameProduct.getAttribute("aria-pressed"), initial[0]);
  assert.equal(await page.getByText("The commerce catalogue could not be loaded.", { exact: true }).count(), 0); assert.deepEqual(errors, []);
});

test("Featured 409, 429, 500, and network failures roll back only the affected row", async (t) => {
  await mkdir(RESULTS, { recursive: true }); const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "4199"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForServer();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  const products = [...productList(), baseProduct("p4", "network-product", "Network Product", ["collection-apparel"], false, null, 40), baseProduct("p5", "healthy-product", "Healthy Product", ["collection-apparel"], false, null, 50)];
  const failures = { p1: { status: 409 }, p2: { status: 429, nonJson: true }, p3: { status: 500 }, p4: { abort: true } };
  const { context, page, requestCounts, responseStatuses } = await fixturePage(browser, 390, 844, { products, featuredResponse: ({ id }) => failures[id] || null }); t.after(() => context.close());
  await page.goto(`${ORIGIN}/products`); await page.getByRole("heading", { level: 1, name: "Shop / Products" }).waitFor(); const baseline = requestCounts.featuredMutation;
  for (const [title, initialPressed] of [["BLEH | Unisex classic tee", "true"], ["Third Railify Icon | Dad hat", "true"], ["Third Railify Logo V2 | Unisex classic tee", "false"], ["Network Product", "false"]]) {
    const row = page.locator(".commerce-product-table .commerce-product-row").filter({ hasText: title }); const star = row.locator("button[aria-pressed]").nth(1); await star.click(); await row.getByText("Could not update Featured status. Try again.", { exact: true }).waitFor(); assert.equal(await star.getAttribute("aria-pressed"), initialPressed); assert.equal(await row.getByRole("button", { name: "Edit product" }).isEnabled(), true);
  }
  assert.equal(requestCounts.featuredMutation, baseline + 4); assert.deepEqual(responseStatuses.filter((status) => status >= 400).sort((a, b) => a - b), [409, 429, 500]);
  const healthy = page.locator(".commerce-product-table .commerce-product-row").filter({ hasText: "Healthy Product" }); await healthy.locator("button[aria-pressed]").nth(1).click(); await healthy.getByRole("button", { name: /Remove Healthy Product from featured products/ }).waitFor(); assert.equal(requestCounts.featuredMutation, baseline + 5);
  assert.equal(await page.locator(".commerce-product-table .commerce-product-row").count(), 5); assert.equal(await page.getByText(/account service is unavailable/i).count(), 0); assert.equal(await page.getByText("The commerce catalogue could not be loaded.", { exact: true }).count(), 0); assert.equal(await noOverflow(page), true);
});

async function fixturePage(browser, width, height, options = {}) { const context = await browser.newContext({ viewport: { width, height }, reducedMotion: "reduce" }); const page = await context.newPage(); const errors = []; const imageResponses = []; let products = options.products || productList(); let collections = collectionList(products); const requestCounts = { authConfig: 0, authSession: 0, productList: 0, featuredMutation: 0 }; const featuredAttempts = new Map(); const responseStatuses = []; page.on("console", (message) => { if (message.type() === "error") errors.push(message.text() + (message.location().url ? ` (${message.location().url})` : "")); }); page.on("pageerror", (error) => errors.push(error.message)); page.on("response", (response) => { if (response.url() === IMAGE && response.ok()) imageResponses.push(response.status()); if (response.url().includes("/featured")) responseStatuses.push(response.status()); });
  const savedBodies = []; let uploadCount = 0;
  await page.route("**/commerce-media/**", (route) => route.fulfill({ status: 200, contentType: "image/png", body: PNG }));
  for (const imageUrl of [IMAGE, IMAGE_TWO, IMAGE_THREE]) await page.route(imageUrl, (route) => route.fulfill({ status: 200, contentType: "image/svg+xml", body: imageUrl === IMAGE_THREE ? "not an image" : `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="750"><rect width="100%" height="100%" fill="#161616"/><path d="M80 375h440" stroke="#f2c94c" stroke-width="44"/><text x="300" y="330" fill="white" text-anchor="middle" font-size="58">TR SHOP</text></svg>` }));
  await page.route("**/api/**", async (route) => { const path = new URL(route.request().url()).pathname;
    if (path === "/api/auth/config") { requestCounts.authConfig += 1; return json(route, authConfig()); } if (path === "/api/auth/session") { requestCounts.authSession += 1; return json(route, session()); }
    if (path === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { submissions: 0, comments: 0, emailFailures: 0, total: 0 }, total: 0 }, latest: [] });
    if (path === "/api/admin/commerce/products/reconciliation") return json(route, { ok: true, access: access(), authority: { provider: "Printful", contract: "printful-v1-sync-products", configuredStoreId: "18668025", configurationState: "configured", storeVerified: true, store: { id: "18668025", name: "Third Railify API", type: "native" } }, counts: { totalProducts: products.length, currentProducts: products.length, publicProducts: products.length, archivedProducts: 0, needsReviewProducts: 0, currentVariants: products.length }, latest: { id: "ccr_fixture", state: "applied", store: { id: "18668025", name: "Third Railify API", type: "native" }, snapshotFingerprint: "a".repeat(64), providerProducts: products.length, providerVariants: products.length, unusualReduction: false, previewedAt: "2026-09-01T00:00:00.000Z", appliedAt: "2026-09-01T00:01:00.000Z", updatedAt: "2026-09-01T00:01:00.000Z" } });
    if (path === "/api/admin/commerce/products/list") { requestCounts.productList += 1; return json(route, productListPayload(products, new URL(route.request().url()))); }
    if (path === "/api/admin/commerce/products") return json(route, productsPayload(products));
    if (path === "/api/admin/commerce/collections/options") return json(route, collectionOptionsPayload(collections));
    if (path === "/api/admin/commerce/collections/list") return json(route, collectionListPayload(collections, new URL(route.request().url())));
    if (/\/api\/admin\/commerce\/collections\/[^/]+\/products\/list$/.test(path)) { const id = decodeURIComponent(path.split("/")[5]); return json(route, collectionProductPayload(products, id, new URL(route.request().url()))); }
    if (path === "/api/admin/commerce/collections/bulk" && route.request().method() === "POST") { const body = JSON.parse(route.request().postData() || "{}"); const ids = body.collectionIds || collectionListFiltered(collections, body.matching || {}).map((collection) => collection.id); let updated = 0; collections = collections.map((collection) => { if (!ids.includes(collection.id)) return collection; const visibility = body.operation === "show" ? "public" : "hidden"; if (collection.visibility === visibility) return collection; updated += 1; return { ...collection, visibility, revision: collection.revision + 1 }; }); return json(route, { ok: true, operation: body.operation, selection: body.matching ? "matching" : "explicit", matched: ids.length, requested: ids.length, updated, unchanged: ids.length - updated, rejected: 0, errors: [], updatedIds: ids }); }
    if (/\/api\/admin\/commerce\/collections\/[^/]+\/products\/bulk$/.test(path) && route.request().method() === "POST") { const id = decodeURIComponent(path.split("/")[5]); const body = JSON.parse(route.request().postData() || "{}"); let updated = 0; products = products.map((product) => { if (!body.productIds.includes(product.id)) return product; const assigned = product.collectionIds.includes(id); if ((body.operation === "add" && assigned) || (body.operation === "remove" && !assigned)) return product; updated += 1; return { ...product, collectionIds: body.operation === "add" ? [...product.collectionIds, id] : product.collectionIds.filter((collectionId) => collectionId !== id) }; }); collections = collectionListFromCurrent(collections, products).map((collection) => collection.id === id ? { ...collection, revision: body.revision + 1 } : collection); return json(route, { ok: true, collectionId: id, revision: body.revision + 1, operation: body.operation, requested: body.productIds.length, updated, unchanged: body.productIds.length - updated, updatedIds: body.productIds }); }
    if (/\/api\/admin\/commerce\/collections\/[^/]+$/.test(path) && route.request().method() === "GET") { const id = decodeURIComponent(path.split("/")[5]); return json(route, { ok: true, databaseConfigured: true, access: access(), collection: collections.find((collection) => collection.id === id) }); }
    if (path === "/api/admin/commerce/collections/order" && route.request().method() === "POST") { const ids = JSON.parse(route.request().postData() || "{}").collectionIds || []; collections = ids.map((id, index) => ({ ...collections.find((collection) => collection.id === id), displayOrder: (index + 1) * 10, revision: collections.find((collection) => collection.id === id).revision + 1 })); return json(route, collectionOptionsPayload(collections)); }
    if (path === "/api/admin/commerce/media/config") return json(route, { ok: true, limits: mediaLimits() });
    if (/\/api\/admin\/commerce\/products\/[^/]+\/media\/ingest$/.test(path) && route.request().method() === "POST") { if ((route.request().headers()["content-type"] || "").startsWith("multipart/form-data")) { uploadCount += 1; if (uploadCount === 3) return json(route, { ok: false, error: "commerce_media_format_invalid", message: "The file must be a valid JPG, PNG, or WebP image." }, 415); const url = `${ORIGIN}/commerce-media/${String(uploadCount).padStart(64, "a")}.png`; return json(route, { ok: true, productId: "p1", asset: { url, sha256: String(uploadCount).padStart(64, "a"), contentType: "image/png", bytes: PNG.length }, limits: mediaLimits(), uploadedAt: new Date().toISOString() }); } const body = JSON.parse(route.request().postData() || "{}"); return json(route, { ok: true, productId: "p1", primaryImageUrl: body.imageUrls?.[0] || null, additionalImages: (body.imageUrls || []).slice(1), assets: (body.imageUrls || []).map((url, index) => ({ url: /\/commerce-media\//.test(url) ? url : `${ORIGIN}/commerce-media/${String(index + 20).padStart(64, "b")}.png`, sha256: String(index + 20).padStart(64, "b"), contentType: "image/png", bytes: PNG.length })) }); }
    if (/^\/api\/admin\/commerce\/products\/[^/]+\/featured$/.test(path) && route.request().method() === "POST") { const id = decodeURIComponent(path.split("/")[5]); const body = JSON.parse(route.request().postData() || "{}"); const attempt = (featuredAttempts.get(id) || 0) + 1; featuredAttempts.set(id, attempt); requestCounts.featuredMutation += 1; const override = await options.featuredResponse?.({ id, body, attempt }); if (override?.delay) await new Promise((resolve) => setTimeout(resolve, override.delay)); else if (options.featuredDelay) await new Promise((resolve) => setTimeout(resolve, options.featuredDelay)); if (override?.abort) return route.abort("failed"); if (override?.status && override.nonJson) return route.fulfill({ status: override.status, contentType: "text/html", body: "upstream rate limit" }); if (override?.status) return json(route, { ok: false, error: override.error || "featured_rejected", message: override.message || "Featured update rejected." }, override.status); const current = products.find((product) => product.id === id); if (!current || typeof body.featured !== "boolean") return json(route, { ok: false, error: "invalid" }, 400); const nextOrder = body.featured && !current.featured ? products.reduce((maximum, product) => Math.max(maximum, product.featuredOrder || 0), 0) + 10 : body.featured ? current.featuredOrder : null; const changed = current.featured !== body.featured; const updatedAt = new Date().toISOString(); products = products.map((product) => product.id === id ? { ...product, featured: body.featured, featuredOrder: nextOrder, updatedAt } : product); return json(route, { ok: true, changed, product: { id, featured: body.featured, featuredOrder: nextOrder, updatedAt } }); }
    if (path === "/api/admin/commerce/products/p1" && route.request().method() === "POST") { const body = JSON.parse(route.request().postData() || "{}"); savedBodies.push(body); products = products.map((product) => product.id === "p1" ? { ...product, ...body, price: product.price, variants: product.variants, readiness: product.readiness, displayData: { ...product.displayData, hasImage: Boolean(body.primaryImageUrl) } } : product); return json(route, { ok: true, databaseConfigured: true, access: access(), product: products.find((product) => product.id === "p1") }); }
    if (path === "/api/admin/commerce/products/bulk" && route.request().method() === "POST") { const body = JSON.parse(route.request().postData() || "{}"); const ids = body.productIds || productListFiltered(products, body.matching || {}).map((product) => product.id); let updated = 0; let nextFeaturedOrder = products.reduce((maximum, product) => Math.max(maximum, product.featuredOrder || 0), 0); products = products.map((product) => { if (!ids.includes(product.id)) return product; if (body.operation === "show" || body.operation === "hide") { const visibility = body.operation === "show" ? "public" : "private"; if (product.visibility === visibility) return product; updated += 1; return { ...product, visibility }; } if (body.operation === "feature") { if (product.featured) return product; updated += 1; nextFeaturedOrder += 10; return { ...product, featured: true, featuredOrder: nextFeaturedOrder }; } if (!product.featured) return product; updated += 1; return { ...product, featured: false, featuredOrder: null }; }); return json(route, { ok: true, operation: body.operation, selection: body.matching ? "matching" : "explicit", matched: ids.length, requested: ids.length, updated, unchanged: ids.length - updated, rejected: 0, errors: [], updatedIds: ids }); }
    if (path === "/api/admin/commerce/products/featured" && route.request().method() === "POST") { const ids = JSON.parse(route.request().postData() || "{}").featuredIds || []; products = products.map((product) => { const index = ids.indexOf(product.id); return { ...product, featured: index >= 0, featuredOrder: index >= 0 ? (index + 1) * 10 : null }; }); return json(route, productsPayload(products)); }
    return json(route, { ok: false, error: "not_found" }, 404);
  }); return { context, page, errors, imageResponses, savedBodies, requestCounts, responseStatuses }; }
function baseProduct(id, slug, title, collectionIds, featured, featuredOrder, displayOrder) { const provider = { storeId: "18668025", presence: "current", reconciliationStatus: "current", lastSeenAt: "2026-09-01T00:00:00.000Z", reconciledAt: "2026-09-01T00:00:00.000Z", snapshotFingerprint: "a".repeat(64), archivedAt: null, archivedReason: null }; return { id, slug, title, description: "Fixture product", primaryImageUrl: IMAGE, additionalImages: id === "p1" ? [IMAGE_TWO, IMAGE_THREE] : [], categories: collectionIds.includes("collection-apparel") ? ["Apparel"] : ["Headwear"], collectionIds, tags: [], status: "active", visibility: "public", currencyCode: "CAD", unitAmount: 3050, price: { minimum: 3050, maximum: 3050, label: "CA$30.50" }, maxQuantity: 5, requiresShipping: true, featured, featuredOrder, displayOrder, migrationStatus: "target_verified", sourceProvider: "commerce-d1", integration: {}, provider, variantCount: 1, activeVariantCount: 1, sellableVariantCount: 0, readiness: { displayable: true, checkout: false, fulfillment: "mapped" }, variants: [{ id: `${id}-v1`, productId: id, localVariantKey: "M/Black", displayLabel: "M / Black", status: "active", visibility: "public", sellable: false, availability: "active", unitAmount: 3050, currencyCode: "CAD", sku: null, size: "M", color: "Black", options: { Size: "M", Color: "Black" }, fulfillmentProvider: "printful", fulfillmentMappingStatus: "mapped", migrationStatus: "target_verified", integration: {}, provider: { ...provider, reconciliationStatus: undefined, archivedReason: undefined }, updatedAt: "2026-08-29T00:00:00.000Z" }], displayData: { hasImage: true, hasPrice: true, ready: true }, updatedAt: "2026-08-29T00:00:00.000Z" }; }
function productList() { return [baseProduct("p1", "bleh-tee", "BLEH | Unisex classic tee", ["collection-apparel"], true, 10, 10), baseProduct("p2", "icon-hat", "Third Railify Icon | Dad hat", ["collection-headwear"], true, 20, 20), baseProduct("p3", "logo-v2-tee", "Third Railify Logo V2 | Unisex classic tee", ["collection-apparel"], false, null, 30)]; }
function stressProductList(count) { return Array.from({ length: count }, (_, index) => { const featured = index < 8; const number = String(index + 1).padStart(2, "0"); return baseProduct(`stress-${number}`, `stress-product-${number}`, `Stress Product ${number}`, [index % 2 ? "collection-headwear" : "collection-apparel"], featured, featured ? (index + 1) * 10 : null, (index + 1) * 10); }); }
function access() { return { isMasterAdmin: true, capabilities: ["commerce.view", "commerce.catalogue.manage", "commerce.business.manage"] }; }
function productsPayload(products = productList()) { const ordered = [...products].sort((a, b) => (a.featuredOrder ?? Infinity) - (b.featuredOrder ?? Infinity)); return { ok: true, databaseConfigured: true, access: access(), products, featured: ordered.filter((product) => product.featured), updatedAt: "2026-08-29T00:00:00.000Z" }; }
function productListFiltered(products, filters) { const query = String(filters?.query || "").toLowerCase(); return products.filter((product) => (!query || (product.title + " " + product.slug).toLowerCase().includes(query)) && (!filters?.featured || filters.featured === "all" || (filters.featured === "featured" ? product.featured : !product.featured)) && (!filters?.visibility || filters.visibility === "all" || product.visibility === filters.visibility)); }
function productListPayload(products, url) { const filters = { query: url.searchParams.get("query") || "", featured: url.searchParams.get("featured") || "all", visibility: url.searchParams.get("visibility") || "all" }; const matching = productListFiltered(products, filters); const pageSize = [20, 50, 75, 100].includes(Number(url.searchParams.get("pageSize"))) ? Number(url.searchParams.get("pageSize")) : 20; const requestedPage = Math.max(1, Number(url.searchParams.get("page")) || 1); const totalPages = matching.length ? Math.ceil(matching.length / pageSize) : 0; const page = totalPages ? Math.min(requestedPage, totalPages) : 1; const payload = productsPayload(products); return { ok: true, databaseConfigured: true, access: access(), items: matching.slice((page - 1) * pageSize, page * pageSize), featured: payload.featured, page, pageSize, totalItems: matching.length, totalPages, filters: { query: filters.query, visibility: filters.visibility, status: "all", migration: "all", category: "all", featured: filters.featured, catalogue: "current", sort: "display" }, facets: { categories: ["Apparel", "Headwear"], migrationStatuses: ["target_verified"] }, totals: { products: products.length, totalProducts: products.length, currentProducts: products.length, archivedProducts: 0, providerMissingProducts: 0, wrongStoreProducts: 0, needsReviewProducts: 0, publicProducts: products.filter((product) => product.visibility === "public").length, variants: products.length, featuredProducts: payload.featured.length }, updatedAt: payload.updatedAt }; }
function collectionList(products = productList()) { return collectionListFromCurrent([{ id: "collection-apparel", slug: "apparel", title: "Apparel", description: "Wear the signal.", visibility: "public", status: "active", displayOrder: 10, revision: 1, createdAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }, { id: "collection-headwear", slug: "headwear", title: "Headwear", description: "Top the line.", visibility: "public", status: "active", displayOrder: 20, revision: 1, createdAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }], products); }
function collectionListFromCurrent(collections, products) { return collections.map((collection) => { const assigned = products.filter((product) => product.collectionIds.includes(collection.id)); return { ...collection, assignedProductCount: assigned.length, publicProductCount: assigned.filter((product) => product.visibility === "public" && product.status === "active").length, thumbnailUrl: assigned[0]?.primaryImageUrl || null }; }); }
function collectionOptionsPayload(collections) { return { ok: true, databaseConfigured: true, access: access(), collections, updatedAt: "2026-08-29T00:00:00.000Z" }; }
function collectionListFiltered(collections, filters) { const query = String(filters.query || "").toLowerCase(); return [...collections].filter((collection) => (!query || `${collection.title} ${collection.slug} ${collection.description}`.toLowerCase().includes(query)) && (!filters.visibility || filters.visibility === "all" || collection.visibility === filters.visibility) && (!filters.contents || filters.contents === "all" || (filters.contents === "empty" ? collection.assignedProductCount === 0 : collection.assignedProductCount > 0))).sort((a, b) => filters.sort === "title_desc" ? b.title.localeCompare(a.title) : filters.sort === "title_asc" ? a.title.localeCompare(b.title) : filters.sort === "product_count" ? b.assignedProductCount - a.assignedProductCount || a.title.localeCompare(b.title) : a.displayOrder - b.displayOrder || a.slug.localeCompare(b.slug)); }
function collectionListPayload(collections, url) { const filters = { query: url.searchParams.get("query") || "", visibility: url.searchParams.get("visibility") || "all", contents: url.searchParams.get("contents") || "all", sort: url.searchParams.get("sort") || "display" }; const matching = collectionListFiltered(collections, filters); const pageSize = [20,50,75,100].includes(Number(url.searchParams.get("pageSize"))) ? Number(url.searchParams.get("pageSize")) : 20; const totalPages = matching.length ? Math.ceil(matching.length / pageSize) : 0; const page = totalPages ? Math.min(Math.max(1, Number(url.searchParams.get("page")) || 1), totalPages) : 1; const start = (page - 1) * pageSize; const items = matching.slice(start, start + pageSize); return { ok: true, databaseConfigured: true, access: access(), items, page, pageSize, totalItems: matching.length, totalPages, startIndex: matching.length ? start + 1 : 0, endIndex: matching.length ? start + items.length : 0, filters, totals: { collections: collections.length, publicCollections: collections.filter((collection) => collection.visibility === "public").length, hiddenCollections: collections.filter((collection) => collection.visibility === "hidden").length, emptyCollections: collections.filter((collection) => !collection.assignedProductCount).length }, updatedAt: "2026-08-29T00:00:00.000Z" }; }
function collectionProductPayload(products, collectionId, url) { const query = (url.searchParams.get("query") || "").toLowerCase(); const membership = url.searchParams.get("membership") || "all"; const visibility = url.searchParams.get("visibility") || "all"; const matching = products.filter((product) => { const assigned = product.collectionIds.includes(collectionId); return (!query || `${product.title} ${product.slug}`.toLowerCase().includes(query)) && (membership === "all" || (membership === "assigned" ? assigned : !assigned)) && (visibility === "all" || (visibility === "public" ? product.visibility === "public" && product.status === "active" : product.visibility !== "public" || product.status !== "active")); }); return { ok: true, databaseConfigured: true, access: access(), collectionId, items: matching.map((product) => ({ id: product.id, slug: product.slug, title: product.title, primaryImageUrl: product.primaryImageUrl, status: product.status, visibility: product.visibility, assigned: product.collectionIds.includes(collectionId), priceLabel: product.price.label, updatedAt: product.updatedAt })), page: 1, pageSize: 20, totalItems: matching.length, totalPages: matching.length ? 1 : 0, startIndex: matching.length ? 1 : 0, endIndex: matching.length, filters: { query, visibility, membership } }; }
function session() { return { ok: true, authenticated: true, csrfToken: "browser-fixture-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master Admin", username: null, avatarUrl: null, providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", lastLoginAt: null, source: "test", locked: true } }; }
function authConfig() { return { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }; }
function mediaLimits() { return { maxBytes: 10 * 1024 * 1024, maxProductImages: 25, maxAdditionalImages: 24, acceptedTypes: ["image/jpeg", "image/png", "image/webp"] }; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); } function noOverflow(page) { return page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth); }
async function waitForServer() { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Admin commerce test server did not start."); }
