import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";

const PREVIEW_ORIGIN = "http://127.0.0.1:4174";
const CHROME_PATH = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

test("Fulfillment & Shipping is a responsive, truthful, non-mutating operations workspace", async (t) => {
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4174"], { stdio: "ignore" });
  t.after(() => server.kill()); await waitForPreview();
  const browser = await chromium.launch({ executablePath: CHROME_PATH, headless: true }); t.after(() => browser.close());
  for (const [width, fixture] of [[390, "empty"], [768, "evidence"], [1440, "evidence"]]) {
    const context = await browser.newContext({ viewport: { width, height: width === 390 ? 844 : 1000 } });
    const page = await context.newPage(); const consoleErrors = []; const requests = [];
    page.on("console", (message) => { if (message.type() === "error") consoleErrors.push(message.text()); }); page.on("pageerror", (error) => consoleErrors.push(error.message));
    await page.route("**/api/**", async (route) => {
      const request = route.request(); const path = new URL(request.url()).pathname; requests.push({ path, method: request.method() });
      if (path === "/api/auth/config") return json(route, authConfig());
      if (path === "/api/auth/session") return json(route, session());
      if (path === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { submissions: 0, comments: 0, emailFailures: 0, total: 0 }, total: 0 }, latest: [] });
      if (path === "/api/admin/commerce/fulfillment") return json(route, fulfillmentPayload(fixture));
      return json(route, { ok: false, error: "not_found" }, 404);
    });
    await page.goto(`${PREVIEW_ORIGIN}/COMMERCE/FULFILLMENT`); await page.waitForURL(`${PREVIEW_ORIGIN}/commerce/fulfillment`);
    await page.getByRole("heading", { level: 1, name: "Fulfillment & Shipping" }).waitFor();
    assert.equal(await page.getByText("Read only / locked", { exact: true }).count(), 1);
    assert.equal(await page.getByText("Draft Only", { exact: true }).count() >= 1, true);
    assert.equal(await page.getByText("Encrypted customer delivery snapshots", { exact: true }).count(), 1);
    assert.equal(await page.getByText("The quote adapter is implemented, but the canonical strategy remains unconfigured and fail-closed.", { exact: true }).count(), 1);
    assert.equal(await page.getByText("Printful quote adapter", { exact: true }).count(), 1);
    assert.equal(await page.getByRole("heading", { level: 2, name: "Lifecycle capabilities" }).count(), 1);
    assert.equal(await page.getByRole("heading", { level: 2, name: "Provider orders" }).count(), 1);
    assert.equal(await page.getByRole("heading", { level: 2, name: "Order fulfillment pipeline" }).count(), 1);
    assert.equal(await page.getByRole("heading", { level: 2, name: "Product & variant mapping health" }).count(), 1);
    for (const text of ["DRAFT PREVIEW", "NO PROVIDER REQUEST", "NOT SUBMITTED"]) assert.equal(await page.getByText(text, { exact: true }).count(), 1);
    assert.equal(await page.getByRole("button", { name: "Submit to Printful — worker only" }).isDisabled(), true);
    assert.equal(await page.getByText("shipping_strategy_missing", { exact: true }).count(), 1); assert.equal(await page.getByText("shipping_method_missing", { exact: true }).count(), 1); assert.equal(await page.getByText("fulfillment_disabled", { exact: true }).count(), 1);
    assert.equal(await page.getByRole("link", { name: /Manage Products/ }).getAttribute("href"), "/products");
    for (const link of ["Business Information", "Tax & Documents", "Customer Emails", "Payments & Payouts", "Orders"]) assert.equal(await page.getByRole("link", { name: new RegExp(link) }).count() >= 1, true, link);
    if (fixture === "empty") { assert.equal(await page.getByText("No fulfillment evidence", { exact: true }).count(), 1); assert.equal(await page.getByText("No provider orders", { exact: true }).count(), 1); }
    else { assert.equal(await page.getByText("ord-test-fulfillment", { exact: true }).count() >= 1, true); assert.equal(await page.getByText("ord-live-fulfillment", { exact: true }).count() >= 1, true); for (const state of ["Draft", "Processing", "Partial", "Shipped", "Returned"]) assert.equal(await page.getByText(state, { exact: true }).count() >= 1, true, state); }
    await page.getByText("Advanced / technical", { exact: true }).click(); assert.equal(await page.getByText("printful-draft-preview-v1", { exact: true }).count(), 1);
    assert.equal(await page.getByText(/printful-server-secret|authorization|bearer|customer@example|100 Preview Street/i).count(), 0);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true); assert.deepEqual(consoleErrors, []);
    assert.deepEqual(requests.filter((entry) => entry.path === "/api/admin/commerce/fulfillment"), [{ path: "/api/admin/commerce/fulfillment", method: "GET" }]);
    assert.equal(requests.some((entry) => /printful|stripe|paypal|wix|resend/i.test(entry.path) && entry.path !== "/api/admin/commerce/fulfillment"), false);
    await context.close();
  }
});

async function waitForPreview() { for (let attempt = 0; attempt < 50; attempt += 1) { try { if ((await fetch(PREVIEW_ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Vite preview did not start."); }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
function authConfig() { return { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: "https://thirdrailify-admin.pages.dev", environment: "test", cookieMode: "host-only" }; }
function session() { return { ok: true, authenticated: true, csrfToken: "browser-fixture-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master Admin", providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-28T00:00:00Z", source: "test", locked: true } }; }
function fulfillmentPayload(fixture) {
  const evidence = fixture === "empty" ? [] : [
    { id: "ord-test-fulfillment", environment: "test", paymentStatus: "paid", fulfillmentStatus: "draft", providerOrderRecorded: false, createdAt: "2026-08-28T00:00:00Z", updatedAt: "2026-08-28T00:01:00Z" },
    { id: "ord-live-fulfillment", environment: "live", paymentStatus: "paid", fulfillmentStatus: "submitted", providerOrderRecorded: true, createdAt: "2026-08-28T01:00:00Z", updatedAt: "2026-08-28T01:01:00Z" },
  ];
  const operationRows = fixture === "empty" ? [] : [
    ["fl-test-draft","ord-test-fulfillment","test","700001","draft","draft",0,false],
    ["fl-live-processing","ord-live-fulfillment","live","700002","processing","processing",0,false],
    ["fl-live-partial","ord-live-partial","live","700003","partial","partial",1,true],
    ["fl-live-shipped","ord-live-shipped","live","700004","complete","shipped",1,true],
    ["fl-live-returned","ord-live-returned","live","700005","complete","returned",1,true],
  ].map(([id,orderId,environment,providerOrderId,providerState,fulfillmentState,shipmentCount,trackingAvailable]) => ({ id,orderId,environment,paymentStatus:"paid",provider:"printful",providerOrderId,confirmationState:providerState === "draft" ? "unconfirmed" : "submitted",providerState,providerStatus:providerState,fulfillmentState,shipmentCount,trackingAvailable,lastProviderEvidenceAt:"2026-08-29T01:00:00Z" }));
  const status = (state, detail) => ({ state, detail });
  return {
    ok: true, databaseConfigured: true, authority: "Commerce D1 + server runtime configured-state projection", access: { isMasterAdmin: true, capabilities: ["commerce.view"] },
    readiness: { provider: status("configured", "Persisted Printful configuration is internally consistent."), catalogue: status("partial", "238 variants meet the mapping contract."), customerShippingData: status(fixture === "empty" ? "implemented_no_evidence" : "available", "Encrypted order delivery snapshots are implemented; customer PII is not projected here."), paymentAuthority: status("test_evidence_only", "One preserved signed-webhook TEST payment exists."), printfulOrderMode: status("draft_only", "Canonical mode: draft_only."), fulfillment: status("disabled", "Fulfillment is intentionally disabled until production activation."), tracking: status(fixture === "empty" ? "implemented_no_evidence" : "available", "Normalized encrypted tracking authority is implemented."), production: status("blocked", "Canonical production commerce remains blocked.") },
    provider: { name: "Printful", state: "connected", configured: true, targetStoreConfigured: true, storeType: "native", credentialConfigured: true, configurationEvidence: "persisted_prior_verification", scopes: { products: true, files: true, orders: true, webhooks: true, evidenceRecorded: true }, orderMode: "draft_only", providerOrderMode: "draft_only", orderModeConsistent: true, fulfillmentEnabled: false, localProviderOrderCount: fixture === "empty" ? 0 : 1, lastProviderOrderAt: fixture === "empty" ? null : "2026-08-28T01:01:00Z", lastConfigurationEvidenceAt: "2026-08-28T00:00:00Z" },
    migration: { id: "permanent-printful-2026-08", status: "waiting", phase: "source_files", manuallyPaused: true, verifiedProducts: 12, mappedVariants: 238, blockedProducts: 28, deferredVariants: 5, providerRequestCount: 419, providerFailures: 36, updatedAt: "2026-08-28T00:00:00Z", completedAt: null, mutableFromThisRoute: false },
    mapping: { storefrontProducts: 49, storefrontVariants: 1317, totalProducts: 50, totalVariants: 1323, mappedProviderProducts: 12, mappedProviderVariants: 238, unmappedVariants: 1052, blockedProducts: 28, blockedVariants: 0, deferredVariants: 5, nonSellableVariants: 1323, potentiallyFulfillableVariants: 0, contract: "Printful + mapped + target product ID + target Sync Variant ID + target-verified/native migration" },
    pipeline: [["order_record","Order recorded",true,"commerce_orders","Checkout core","Implemented; local record precedes payment provider creation."],["payment_confirmed","Payment confirmed",true,"commerce_orders.payment_status + signed Stripe webhook receipt","Signed Stripe webhook","Implemented with TEST-only evidence."],["fulfillment_eligible","Fulfillment eligibility",true,"Local settings, order, item snapshot, and provider mappings","Future local workflow","Preparation logic implemented; submission remains disabled."],["provider_draft","Provider draft",false,"No local provider-order record exists","Not implemented","Preview only; no Printful request is made."],["submitted","Provider submitted",false,"commerce_orders.printful_order_id when present","Not implemented","No Printful orders have been submitted."],["shipment","Shipped / delivered",false,"No persisted authority","Not implemented","No shipment or tracking workflow is implemented."]].map(([id,label,implemented,authority,transition,detail]) => ({ id,label,implemented,authority,transition,detail })),
    shipping: { customerData: { state: fixture === "empty" ? "implemented_no_evidence" : "available", persistedFields: ["encrypted_recipient", "destination_country", "destination_region", "shipping_method", "shipping_amount", "currency", "source_quote"], orderSpecificPiiProjectedHere: false }, rates: { state: "implemented_disabled", strategy: "unconfigured", providerQuotePathImplemented: true, providerQuoteCalled: false } }, tracking: { state: fixture === "empty" ? "implemented_no_evidence" : "available", persistedFields: ["encrypted_tracking_number", "encrypted_tracking_url", "carrier", "service", "shipment_state", "provider_shipment_id"], shipmentPollingImplemented: true, providerPollingPerformed: false },
    lifecycle: { schema: { state: "ready", migration: "0018_printful_fulfillment_lifecycle.sql" }, providerOrderModel: { state: "implemented", authority: "commerce_fulfillment_orders" }, draftRecording: { state: "implemented", idempotent: true }, webhookReceiver: { state: "implemented", protocol: "printful_v2_beta_hmac_sha256", route: "/api/webhooks/printful" }, webhookVerification: { state: "not_configured" }, providerSubscription: { state: "not_configured_unverified" }, shipmentNormalization: { state: "implemented", authority: "commerce_fulfillment_shipments" }, partialShipmentHandling: { state: "implemented", authority: "normalized item coverage" }, trackingStorage: { state: "implemented_encrypted" }, carrierDeliveryPolling: { state: "implemented_scheduled" }, reconciliationFallback: { state: "implemented_scheduled", automaticPolling: true, schedule: "every_5_minutes", terminalStates: ["complete", "archived", "canceled"] }, fulfillmentSubmission: { state: "disabled" } },
    operations: { state: "ready", rows: operationRows, page: 1, pageSize: 20, total: operationRows.length, totalPages: operationRows.length ? 1 : 0, counts: { total: operationRows.length, testOrders: fixture === "empty" ? 0 : 1, liveOrders: fixture === "empty" ? 0 : 4, livePartial: fixture === "empty" ? 0 : 1, liveShipped: fixture === "empty" ? 0 : 1, shipments: fixture === "empty" ? 0 : 3, testShipments: 0, liveShipments: fixture === "empty" ? 0 : 3 } },
    draftPreview: { builderVersion: "printful-draft-preview-v1", kind: "draft_preview", eligible: false, blockers: [{ code: "variant_not_sellable", message: "The authoritative variant is not currently sellable." }, { code: "shipping_strategy_missing", message: "No authoritative shipping-rate strategy is configured." }, { code: "shipping_method_missing", message: "An authoritative selected shipping method is required." }, { code: "fulfillment_disabled", message: "Fulfillment submission is intentionally disabled." }], labels: ["DRAFT PREVIEW", "NO PROVIDER REQUEST", "NOT SUBMITTED"], reference: "DRAFT-PREVIEW-NOT-AN-ORDER", environment: "test", item: { productId: "product-authority", product: "Authoritative product", variantId: "variant-authority", variant: "11 oz / Black", provider: "printful", mappedProviderVariant: "target-variant-authority", quantity: 1 }, requirements: { recipient: { source: "synthetic_fixture", complete: true, missing: [], countryCode: "CA", postalCodePresent: true }, shipping: { required: true, strategy: "unconfigured", configured: false, method: null } }, safePayloadPreview: { externalReference: "DRAFT-PREVIEW-NOT-AN-ORDER", recipient: { source: "synthetic_fixture", countryCode: "CA", postalCodePresent: true }, items: [{ providerVariantId: "target-variant-authority", quantity: 1 }], shipping: { strategy: "unconfigured", method: null } }, submission: { available: false, mode: "draft_only", networkRequestMade: false, providerOrderCreated: false, localOrderMutated: false, migrationMutated: false } },
    gates: [["business","Business information","incomplete","Legal identity incomplete.","/commerce/business"],["tax_documents","Tax & documents","blocked","Tax strategy unconfigured.","/commerce/tax"],["payments","Payment authority","disabled","TEST evidence only.","/commerce/payments"],["customer_emails","Customer emails","disabled","Customer sends disabled.","/commerce/emails"],["checkout","Customer checkout","disabled","Normal checkout is intentionally disabled.","/commerce/payments"],["customer_shipping","Customer shipping data","ready","Encrypted order delivery snapshot capability is implemented.","/orders"],["shipping_rates","Shipping rate strategy","blocked","The server quote adapter is implemented, but the canonical shipping strategy is unconfigured.",null],["product_mapping","Product mapping","blocked","No potentially fulfillable variants.","/products"],["printful_provider","Printful provider","ready","Persisted local configuration is internally consistent.",null],["printful_order_mode","Printful order mode","disabled","Draft-only is the maximum permitted mode.",null],["fulfillment","Fulfillment submission","disabled","Fulfillment submission is intentionally disabled.",null],["live_payments","Live payment capture","disabled","Live payment capture is intentionally disabled.","/commerce/payments"]].map(([id,label,state,detail,href]) => ({id,label,state,detail,href})),
    dependencies: { business: { href: "/commerce/business" }, taxDocuments: { href: "/commerce/tax" }, customerEmails: { href: "/commerce/emails", shipmentTemplate: { configured: true, state: "incomplete", revision: 1, updatedAt: "2026-08-28T00:00:00Z" }, sendsEnabled: false }, payments: { href: "/commerce/payments" }, products: { href: "/products" }, orders: { href: "/orders" } },
    evidence: { recent: evidence, counts: { totalOrders: fixture === "empty" ? 1 : 2, testOrders: 1, liveOrders: fixture === "empty" ? 0 : 1, providerOrders: operationRows.length, fulfillmentEvidence: operationRows.length, testShippingSnapshots: fixture === "empty" ? 0 : 1, liveShippingSnapshots: fixture === "empty" ? 0 : 1, shipments: fixture === "empty" ? 0 : 3 }, lastAudit: null },
    technical: { builderVersion: "printful-draft-preview-v1", providerCallsOnRead: false, providerCallsOnPreview: false, previewPersists: false, previewAuditedAsMutation: false, shippingDataCapability: "implemented", shippingRateCapability: "implemented_disabled", trackingCapability: "not_implemented" }, safety: { checkoutEnabled: false, controlledTestCheckoutEnabled: false, livePaymentCaptureEnabled: false, fulfillmentEnabled: false, orderMode: "draft_only", providerSubmissionAvailable: false, previewOnly: true, mutationsAvailableFromThisRoute: false }, canonicalReadiness: null, checkedAt: "2026-08-29T00:00:00Z",
  };
}
