import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN="http://127.0.0.1:4217";const CHROME="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";const ARTIFACTS=path.resolve(".artifacts/gaming-admin");const SCREENSHOTS=process.env.GAMING_BROWSER_SCREENSHOTS==="1";

test("Admin Gaming workspace is responsive, searchable, capability-aware, and editor-complete",async t=>{const server=spawn(process.execPath,["node_modules/vite/bin/vite.js","--host","127.0.0.1","--port","4217"],{stdio:"ignore"});t.after(()=>server.kill());await waitForServer();if(SCREENSHOTS)await mkdir(ARTIFACTS,{recursive:true});const browser=await chromium.launch({executablePath:CHROME,headless:true});t.after(()=>browser.close());
  for(const [width,height] of [[1920,1080],[1440,1000],[1024,900],[768,900],[390,844]]){const context=await browser.newContext({viewport:{width,height}});const page=await context.newPage();const errors=[];page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text());});await mock(page);await page.goto(`${ORIGIN}/gaming`);await page.getByRole("heading",{level:1,name:/Third Railify Gaming/i}).waitFor();assert.equal(await page.locator("html").evaluate(root=>root.scrollWidth<=root.clientWidth),true,`no page overflow at ${width}`);assert.deepEqual(await page.locator(".gaming-metrics strong").allTextContents(),["4","4","3","3"]);assert.deepEqual(await page.locator(".gaming-rotation-list h3").allTextContents(),["WITCHER","LUMINARY","SUPER MARIO WORLD","PARTY ANIMAL"]);assert.equal(await page.locator('[role="table"] [role="row"]').count(),5);await page.getByPlaceholder("Search title, Steam App ID, or URL").fill("1648360");assert.equal(await page.locator('[role="table"] [role="row"]').count(),2);await page.getByPlaceholder("Search title, Steam App ID, or URL").fill("");if(SCREENSHOTS&&(width===1440||width===390))await page.screenshot({path:path.join(ARTIFACTS,`workspace-${width}x${height}.png`),fullPage:true});
    await page.getByRole("button",{name:/Add game/i}).click();const dialog=page.getByRole("dialog");await dialog.waitFor();assert.equal(await dialog.getByLabel("Display title").count(),1);assert.equal(await dialog.getByLabel("Upload replacement").count(),1);assert.equal(await dialog.getByRole("link",{name:/Search Steam/}).getAttribute("href"),"https://store.steampowered.com/search/?term=");assert.equal(await dialog.getByText("Steam mapping is optional; unknown remains valid.").count(),1);if(SCREENSHOTS&&(width===1440||width===390))await page.screenshot({path:path.join(ARTIFACTS,`editor-${width}x${height}.png`),fullPage:false});await dialog.getByRole("button",{name:"Close game editor"}).click();assert.deepEqual(errors,[],`browser errors at ${width}`);await context.close();}
});

async function mock(page){await page.route("**/api/**",route=>{const pathname=new URL(route.request().url()).pathname;if(pathname==="/api/auth/config")return json(route,{configured:true,emailSignupConfigured:false,turnstileSiteKey:"fixture",oauthProviders:[],oauthProviderStates:[],publicOrigin:"https://thirdrailify.pages.dev",adminOrigin:ORIGIN,environment:"test",cookieMode:"host-only"});if(pathname==="/api/auth/session")return json(route,session());if(pathname==="/api/admin/gaming")return json(route,payload());if(pathname==="/api/admin/inbox/summary")return json(route,{ok:true,unread:0,actionable:{goats:{total:0,submissions:0,comments:0,emailFailures:0},total:0},latest:[]});return json(route,{ok:false,error:"not_found"},404);});}
function session(){return{ok:true,authenticated:true,csrfToken:"gaming-csrf",access:{isAdmin:true,isMasterAdmin:false,capabilities:["gaming.view","gaming.manage"]},account:{id:"full",email:"full@example.test",displayName:"Full Admin",username:null,avatarUrl:null,providers:["email"],role:"admin",adminLevel:"full",status:"active",emailVerified:true,createdAt:"2026-09-01T00:00:00.000Z",lastLoginAt:null,source:"test",locked:false}};}
function payload(){const names=[["gaming-witcher","WITCHER","RPG / ADVENTURE",null,null],["gaming-luminary","LUMINARY","ACTION RPG / CO-OP","1648360","https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1648360/library_600x900.jpg"],["gaming-super-mario-world","SUPER MARIO WORLD","PLATFORMER",null,null],["gaming-party-animal","PARTY ANIMAL","PARTY / PHYSICS",null,null]];const games=names.map(([id,title,genre,appId,url],index)=>({id,title,slug:id.replace("gaming-",""),platform:"PC via Steam",description:`${title} managed description`,genre,developer:null,publisher:null,steam:{appId,storeUrl:appId?`https://store.steampowered.com/app/${appId}/`:null,state:appId?"verified":"unverified",provenance:appId?"steam_verified":"manual"},artwork:{url,source:url?"remote":"fallback",assetId:null,width:null,height:null},rotation:{inRotation:true,position:index+1,addedAt:"2026-09-01T00:00:00.000Z"},archived:false,archivedAt:null,createdAt:"2026-09-01T00:00:00.000Z",updatedAt:"2026-09-01T00:00:00.000Z"}));return{ok:true,authority:"Commerce D1",access:{isAdmin:true,isMasterAdmin:false,capabilities:["gaming.view","gaming.manage"]},steamCatalogue:{configured:false,implemented:false,method:"IStoreService/GetAppList",message:"Steam catalogue lookup is not configured."},games,rotation:games,summary:{rotation:4,library:4,missingArtwork:3,missingSteam:3},checkedAt:"2026-09-01T00:00:00.000Z"};}
function json(route,body,status=200){return route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});}async function waitForServer(){for(let i=0;i<100;i+=1){try{if((await fetch(ORIGIN)).ok)return;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}throw new Error("Admin Gaming Vite server did not start.");}
