import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:44187";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
const ARTIFACTS = fileURLToPath(new URL("../.artifacts/polls-v1/", import.meta.url));

test("Admin Automations, Poll authority, deferred studios, and Wheels scaffold render responsively", async (t) => {
  await mkdir(ARTIFACTS, { recursive: true }); const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "44187"], { stdio: "ignore" }); t.after(() => server.kill()); await wait(); const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const viewport of [{ width: 1920, height: 1080 }, { width: 1440, height: 900 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) {
    adminClosedPublic = true;
    const context = await browser.newContext({ viewport }); const page = await context.newPage(); const errors = []; page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); await page.route("**/api/**", respond);
    mode = "healthy"; await page.goto(`${ORIGIN}/automations`, { waitUntil: "networkidle" }); await page.getByRole("heading", { level: 1, name: "Automations" }).waitFor(); await page.getByText("Bot heartbeat is current").waitFor(); assert.equal(await page.locator('.bot-heartbeat[data-heartbeat-tone="healthy"]').count(), 1); assert.equal(await page.locator(".bot-heartbeat__trace").evaluate((node) => getComputedStyle(node).animationName), "bot-heartbeat-trace"); await page.screenshot({ path: `${ARTIFACTS}/automations-heartbeat-current-${viewport.width}.png`, fullPage: true }); assert.equal(await fits(page), true);
    if (viewport.width === 1440) { mode = "pending"; await page.reload({ waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Bot heartbeat is current" }).waitFor(); assert.equal(await page.locator('.bot-heartbeat[data-heartbeat-tone="warning"][data-heartbeat-state="healthy"]').count(), 1); await page.screenshot({ path: `${ARTIFACTS}/automations-heartbeat-warning.png`, fullPage: true }); assert.equal(await page.getByText("Execution unavailable").count(), 6); await page.getByRole("heading", { name: "Rants" }).waitFor(); }
    if (viewport.width === 768) { mode = "stale"; await page.reload({ waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Bot heartbeat is delayed" }).waitFor(); assert.equal(await page.locator('.bot-heartbeat[data-heartbeat-tone="warning"][data-heartbeat-state="stale"]').count(), 1); await page.screenshot({ path: `${ARTIFACTS}/automations-heartbeat-stale.png`, fullPage: true }); }
    if (viewport.width === 390) { mode = "fault"; await page.reload({ waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Bot heartbeat is current" }).waitFor(); assert.equal(await page.locator('.bot-heartbeat[data-heartbeat-tone="warning"][data-provider-state="disconnected"]').count(), 1); await page.screenshot({ path: `${ARTIFACTS}/automations-heartbeat-fault-mobile.png`, fullPage: true }); }
    if (viewport.width === 1920) { mode = "offline"; await page.reload({ waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Bot heartbeat is offline" }).waitFor(); assert.equal(await page.locator('.bot-heartbeat[data-heartbeat-tone="offline"][data-heartbeat-state="offline"]').count(), 1); await page.screenshot({ path: `${ARTIFACTS}/automations-heartbeat-flatline.png`, fullPage: true }); }
    await page.goto(`${ORIGIN}/polls`, { waitUntil: "networkidle" }); await page.getByRole("heading", { level: 1, name: "Poll management" }).waitFor(); await page.getByText("Primary live choice").waitFor(); await page.getByText("Hidden", { exact: true }).waitFor(); assert.equal(await page.getByRole("button", { name: "Hide from gallery" }).count(), 1); assert.equal(await page.getByRole("button", { name: "Show in gallery" }).count(), 1); if (viewport.width === 1920) { await page.getByRole("button", { name: "Hide from gallery" }).click(); await page.getByRole("button", { name: "Show in gallery" }).nth(1).waitFor(); } await page.screenshot({ path: `${ARTIFACTS}/poll-management-${viewport.width}.png`, fullPage: true }); assert.equal(await fits(page), true);
    if (viewport.width === 1440) { await page.goto(`${ORIGIN}/wheels`, { waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Future entry sources" }).waitFor(); assert.equal(await page.locator(".wheel-automation-deferred input:enabled").count(), 0); await page.screenshot({ path: `${ARTIFACTS}/wheels-automation-deferred.png`, fullPage: true }); }
    assert.deepEqual(errors, []); await context.close();
  }
});

let mode = "healthy"; let adminClosedPublic = true;
async function respond(route) { const url = new URL(route.request().url()); const path = url.pathname;
  if (path === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: false, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: ORIGIN, adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" });
  if (path === "/api/auth/session") return json(route, session());
  if (path === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { total: 0, submissions: 0, comments: 0, emailFailures: 0 } } });
  if (path === "/api/admin/automations") return json(route, automations(mode));
  if (path === "/api/admin/polls" && route.request().method() === "GET") return json(route, { ok: true, items: [poll(), closedPoll(adminClosedPublic), hiddenPoll()], count: 3 });
  if (path.endsWith("/visibility") && route.request().method() === "POST") { adminClosedPublic = JSON.parse(route.request().postData() || "{}").public; return json(route, { ok: true, poll: closedPoll(adminClosedPublic) }); }
  if (path === "/api/admin/wheels") return json(route, { ok: true, items: [] });
  if (path === "/api/admin/wheels/stages") return json(route, { ok: true, items: [] });
  if (path === "/api/admin/wheels/results") return json(route, { ok: true, items: [] });
  if (path === "/api/admin/wheels/settings") return json(route, settings());
  return json(route, { ok: true }); }
function automations(state) { const offline = state === "offline"; const pending = state === "pending"; const stale = state === "stale"; const fault = state === "fault"; return { ok: true, config: { desiredRevision: pending ? 4 : 3, desiredState: { discord: { notificationChannelId: "1283069611431956556", mentionRoleId: "1378093455997276211" }, rumble: { enabled: true, intervalSeconds: 120, pollIntervalSeconds: 15 } }, updatedAt: "2026-08-31T00:00:00Z" }, runtime: offline ? { state: "offline", configured: false } : { state: stale ? "stale" : "online", botVersion: "1.1.0", heartbeatAt: new Date().toISOString(), ageSeconds: stale ? 240 : 7, appliedRevision: 3, desiredRevision: pending ? 4 : 3, discordConnected: !fault, errorCode: fault ? "discord_connection_lost" : null, configSyncState: "synchronized", rumbleConfigured: true, providerState: "live", pollLeaseActive: true, pollingIntervalSeconds: 15, livestreamTitle: "Redacted fixture live", livestreamId: "sample-live", lastRumbleFetch: new Date().toISOString(), backlogMayBeTruncated: false, counters: { accepted: 8, noOp: 2, duplicates: 1, nonmatch: 12 } }, activePoll: offline ? null : poll(), deferred: { processControl: true, generalTriggerStudio: true, rants: true, wheelExecution: true }, activity: [{ id: "pae_fixture1", event_type: "bot_desired_config_changed", result: "success", metadata_json: null, created_at: "2026-08-31T00:00:00Z" }] }; }
function poll() { return { id: "pol_primary123", slug: "primary-live-choice", title: "Primary live choice", description: "Fixture", state: "open", public: true, webVotingMode: "anyone", rumbleEnabled: true, rumbleSourceScope: "user:sample-owner", livestreamMode: "automatic", livestreamId: null, revision: 3, totalVotes: 12, options: [{ id: "opt_one1234", label: "One", trigger: "1", normalizedTrigger: "1", votes: 5 }, { id: "opt_two1234", label: "Carrot", trigger: "CARROT", normalizedTrigger: "carrot", votes: 7 }], owner: { id: "creator", displayName: "Approved Creator", avatarUrl: null }, updatedAt: "2026-08-31T00:00:00Z", openedAt: "2026-08-31T00:00:00Z", closedAt: null }; }
function closedPoll(isPublic) { return { ...poll(), id: "pol_closed123", slug: "settled-public-poll", title: "Settled public Poll", state: "closed", public: isPublic, revision: isPublic ? 5 : 6, totalVotes: 21, owner: { id: "creator", displayName: "Approved Creator", avatarUrl: null }, closedAt: "2026-09-01T01:00:00Z" }; }
function hiddenPoll() { return { ...closedPoll(false), id: "pol_hidden123", slug: "settled-hidden-poll", title: "Settled hidden Poll", revision: 4, owner: { id: "another-owner", displayName: "Another Owner", avatarUrl: null } }; }
function settings() { return { ok: true, settings: { defaultTheme: "third-rail-gold", maximumParticipants: 1000, maximumWheelsPerCreator: 20, officialSpinCooldownSeconds: 2, defaultCelebrationIntensity: "full", defaultPublicHistory: true, mechanics: { mechanicsVersion: 1, curveProfile: "broadcast-smooth", customCurve: { holdEnd: .04, tailStart: .66, tailVelocity: .12 }, launchRpsMin: 2.8, launchRpsMax: 4.5, minimumFullTurns: 2, maximumFullTurns: 120, defaultSpinDurationMs: 6500, minimumSpinDurationMs: 2000, maximumSpinDurationMs: 60000 } }, revision: 12, updatedAt: "2026-08-31T00:00:00Z" }; }
function session() { return { ok: true, authenticated: true, csrfToken: "admin-poll-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master Admin", avatarUrl: null, providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-31T00:00:00Z", source: "env_master" } }; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function fits(page) { return page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth); }
async function wait() { for (let index = 0; index < 80; index += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Admin preview did not start"); }
