import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir} from 'node:fs/promises';import {chromium} from 'playwright-core';
import {onRequest as inboxRequest} from '../functions/api/admin/inbox/[[path]].js';
import {catalogueFixture,ORIGIN} from './catalogue-repair-fixture.mjs';import {onRequest as authRequest} from '../functions/api/auth/[[path]].js';import {onRequest as adminRequest} from '../functions/api/admin/commerce/[[path]].js';
test('authenticated editor controls, save state, variants, media and sync review at 1440/768/390',async t=>{
 const f=await catalogueFixture(t);const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4195','--strictPort'],{stdio:'ignore',windowsHide:true});t.after(()=>server.kill());
 for(let n=0;n<50;n++){try{if((await fetch('http://127.0.0.1:4195')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 await mkdir('.wrangler/printful-workflow-20260912/browser',{recursive:true});const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:["--disable-features=LocalNetworkAccessChecks"]});t.after(()=>browser.close());const context=await browser.newContext();const page=await context.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('requestfailed',r=>console.log('FAILED',new URL(r.url()).pathname,r.failure()?.errorText));page.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text().slice(0,300));});page.on('pageerror',e=>errors.push(e.message));
 await context.route('http://127.0.0.1:4195/**',async route=>{const response=await fetch(route.request().url());if(response.status>=400)console.log('LOCAL API STATUS',new URL(route.request().url()).pathname,response.status);await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
 await context.route('**/api/**',async route=>{const r=route.request(),u=new URL(r.url()),headers=new Headers(r.headers());headers.set('Origin',ORIGIN);headers.set('Cookie',f.cookie);const request=new Request(ORIGIN+u.pathname+u.search,{method:r.method(),headers,...(r.method()==='POST'?{body:r.postDataBuffer()}:{})});let response;try{response=u.pathname.startsWith('/api/auth/')?await authRequest({request,env:f.env}):u.pathname.startsWith('/api/admin/inbox/')?await inboxRequest({request,env:f.env}):await adminRequest({request,env:f.env,data:{commerceFetch:async(url,init)=>{assert.equal(init.method,'GET');const path=new URL(url).pathname;if(path==='/stores')return Response.json({result:[{id:18668025,name:'Third Railify API',type:'native'}]});if(path==='/store/products')return Response.json({result:[{id:99999}],paging:{offset:0,total:1,limit:20}});return Response.json({result:{sync_product:{id:99999,name:'Local sync preview',variants:1},sync_variants:[{id:999999,sync_product_id:99999,variant_id:10163,product_id:358,currency:'CAD',retail_price:'5.00',synced:true,is_ignored:false,availability_status:'active',files:[{id:1,type:'preview',preview_url:'https://files.cdn.printful.com/files/local.png',status:'ok'}]}]}});}}});}catch(e){response=Response.json({error:e.code||'local_error',message:e.message},{status:e.status||500});}if(response.status>=400)console.log('LOCAL API STATUS',new URL(route.request().url()).pathname,response.status);await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:Buffer.from(await response.arrayBuffer())});});
 await context.route(/https:\/\/(example.test|files.cdn.printful.com)\//,route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="#cba65f"/></svg>'}));
 await page.goto('http://127.0.0.1:4195/products',{waitUntil:'commit'});await page.getByRole('heading',{name:'Shop / Products',exact:true}).waitFor().catch(async e=>{console.log('LOCAL PAGE',await page.locator('body').innerText(),errors);throw e;});
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(600);await page.locator('.commerce-product-row').filter({has:page.getByText('Repair product 01',{exact:true})}).getByRole('button',{name:'Edit product',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Repair product 01',exact:true});await dialog.getByText('Product is up to date',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Variants',exact:true}).click();await dialog.getByRole('searchbox',{name:'Search variants'}).fill('');await dialog.getByRole('button',{name:'Select matching variants'}).click();await dialog.getByRole('button',{name:'Media',exact:true}).click();await dialog.getByLabel('Alt text',{exact:true}).fill('Local variant preview');await dialog.getByRole('button',{name:'Assign to selected variants'}).click();await dialog.getByRole('button',{name:'Save product',exact:true}).click();await dialog.getByText('Product saved and published.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Shipping',exact:true}).click();await dialog.getByRole('heading',{name:'Automatic Printful rates',exact:true}).waitFor();await dialog.getByRole('button',{name:'Shipping',exact:true}).getAttribute('aria-current');await page.waitForTimeout(100);assert.equal(await dialog.evaluate(el=>el.scrollWidth>el.clientWidth+2),false);await page.screenshot({path:`.wrangler/printful-workflow-20260912/browser/editor-${width}.png`});await dialog.getByRole('button',{name:'Close editor'}).click();}
 await page.getByRole('button',{name:'Sync Printful',exact:true}).click();await page.getByRole('button',{name:'Import & publish eligible products',exact:true}).waitFor({timeout:30000});await page.locator('.sync-settings > summary').click();await page.getByRole('button',{name:'Review variants for Local sync preview'}).click();for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.locator('.printful-sync').screenshot({style:'.topbar, a[href="#admin-main"] { visibility: hidden !important; }',path:`.wrangler/printful-workflow-20260912/browser/sync-${width}.png`});}await page.getByRole('button',{name:'Cancel sync',exact:true}).click();await page.getByRole('status').filter({hasText:'cancelled'}).waitFor();assert.deepEqual(errors,[]);
});
