import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4211";
const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

test("Tax & Documents is responsive, masked, editor-safe, and renders ephemeral previews", async (t) => {
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "4211"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForServer();
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const [width, height] of [[1440, 1050], [768, 1024], [390, 844]]) {
    let tax = taxFixture(); let templates = templateFixture(); const savedTemplates = []; const registrationBodies = [];
    const context = await browser.newContext({ viewport: { width, height }, reducedMotion: "reduce" }); const page = await context.newPage(); const errors = [];
    page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); }); page.on("pageerror", (error) => errors.push(error.message));
    await page.route("**/api/**", async (route) => {
      const request = route.request(); const path = new URL(request.url()).pathname;
      if (path === "/api/auth/config") return json(route, { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" });
      if (path === "/api/auth/session") return json(route, { ok: true, authenticated: true, csrfToken: "fixture-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master", username: null, avatarUrl: null, providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00Z", lastLoginAt: null, source: "test", locked: true } });
      if (path === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { submissions: 0, comments: 0, emailFailures: 0, total: 0 }, total: 0 }, latest: [] });
      if (path === "/api/admin/commerce/tax" && request.method() === "POST") { const body = JSON.parse(request.postData() || "{}"); registrationBodies.push(body); tax = { ...tax, registrationState: { ...tax.registrationState, configured: true }, registrations: [...tax.registrations, { id: "tax-new", maskedIdentifier: "••••0099", revision: 1, updatedAt: "2026-08-29T02:00:00Z", ...body, identifier: undefined }] }; return json(route, tax); }
      if (path.startsWith("/api/admin/commerce/tax/") && request.method() === "POST") { const body = JSON.parse(request.postData() || "{}"); registrationBodies.push(body); tax = { ...tax, registrations: tax.registrations.map((item) => item.id === path.split("/").at(-1) ? { ...item, ...body, maskedIdentifier: item.maskedIdentifier, revision: item.revision + 1 } : item) }; return json(route, tax); }
      if (path === "/api/admin/commerce/tax") return json(route, tax);
      if (path === "/api/admin/commerce/templates") return json(route, templates);
      if (path.match(/^\/api\/admin\/commerce\/templates\/[^/]+\/preview$/)) { const body = JSON.parse(request.postData() || "{}"); return json(route, previewFixture(body.template)); }
      if (path.match(/^\/api\/admin\/commerce\/templates\/[^/]+$/) && request.method() === "POST") { const body = JSON.parse(request.postData() || "{}"); savedTemplates.push(body); templates = { ...templates, templates: templates.templates.map((item) => item.templateKey === body.templateKey ? { ...body, revision: item.revision + 1 } : item) }; return json(route, templates); }
      if (path === "/api/admin/commerce/business") return json(route, businessFixture());
      return json(route, { ok: false, error: "not_found" }, 404);
    });
    await page.goto(`${ORIGIN}/commerce/tax`); await page.getByRole("heading", { level: 1, name: "Tax & documents" }).waitFor();
    assert.equal(await page.getByRole("heading", { level: 1 }).count(), 1);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true);
    const bodyText = await page.locator("body").innerText(); assert.match(bodyText, /••••0001/); assert.doesNotMatch(bodyText, /123456789RT0001|A256GCM|access_token_hash|ciphertext/i);
    assert.equal(await page.getByRole("link", { name: /Manage Business Information/ }).getAttribute("href"), "/commerce/business");
    assert.equal(await page.getByRole("link", { name: /Manage Customer Emails/ }).getAttribute("href"), "/commerce/emails");
    await page.getByRole("button", { name: "Invoice" }).click(); assert.equal(await page.getByRole("button", { name: "Invoice" }).getAttribute("aria-pressed"), "true");
    const heading = page.getByLabel("Document heading"); const originalHeading = await heading.inputValue(); await heading.fill("Draft invoice heading"); assert.match(await page.locator(".document-editor-actions").innerText(), /Unsaved template changes/i);
    await page.getByRole("button", { name: "Discard" }).click(); assert.equal(await heading.inputValue(), originalHeading);
    await page.getByLabel("Customer-facing introduction").fill('<script>alert("unsafe")</script>'); await page.getByRole("button", { name: /Render SAMPLE preview/ }).click(); await page.getByText(/structured plain text only/i).waitFor();
    await page.getByLabel("Customer-facing introduction").fill("Document for {{order_reference}}."); await page.getByRole("button", { name: /Render SAMPLE preview/ }).click(); await page.getByText("Production renderer output").waitFor(); assert.match(await page.locator(".document-preview-panel").innerText(), /SAMPLE · TEST · NOT ISSUED/);
    await page.getByLabel("Footer").fill("Saved invoice footer"); await page.getByRole("button", { name: "Save template" }).click(); await page.getByText(/Invoice template revision 2 saved/).waitFor(); assert.equal(savedTemplates.length, 1); assert.equal(savedTemplates[0].templateKey, "invoice_document");
    if (width === 1440) {
      await page.getByRole("button", { name: /Add registration/ }).first().click(); const addDialog = page.getByRole("dialog", { name: "Add tax registration" }); await addDialog.getByLabel("Jurisdiction").fill(""); await addDialog.getByRole("button", { name: "Add registration", exact: true }).click(); await addDialog.getByText(/valid jurisdiction/i).waitFor();
      await addDialog.getByLabel("Jurisdiction").fill("ON"); await addDialog.locator(".tax-sensitive-field input").fill("NEW-PRIVATE-0099"); await addDialog.getByRole("button", { name: "Add registration", exact: true }).click(); await page.getByText(/encrypted identifier custody/).waitFor(); assert.equal(registrationBodies.at(-1).identifier, "NEW-PRIVATE-0099");
      assert.doesNotMatch(await page.locator("body").innerText(), /NEW-PRIVATE-0099/);
      await page.getByRole("button", { name: "Edit" }).first().click(); const editDialog = page.getByRole("dialog", { name: "Edit tax registration" }); assert.equal(await editDialog.locator(".tax-sensitive-field input").count(), 0); await editDialog.getByRole("button", { name: "Replace identifier" }).click(); assert.equal(await editDialog.locator(".tax-sensitive-field input").inputValue(), ""); page.once("dialog", (dialog) => dialog.accept()); await editDialog.getByRole("button", { name: "Cancel", exact: true }).click();
    }
    await page.keyboard.press("Tab"); assert.equal(await page.evaluate(() => document.activeElement !== document.body), true); assert.deepEqual(errors, []);
    await page.screenshot({ path: `output/tax-documents-${width}.png`, fullPage: true }); await context.close();
  }
});

test("Tax & Documents renders the authoritative no-registration state", async (t) => {
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "127.0.0.1", "--port", "4212"], { stdio: "ignore" }); t.after(() => server.kill()); await waitForServer("http://127.0.0.1:4212");
  const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close()); const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await page.route("**/api/**", async (route) => { const path = new URL(route.request().url()).pathname; if (path === "/api/auth/config") return json(route, { configured: true, publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: "http://127.0.0.1:4212", environment: "test", oauthProviders: [], oauthProviderStates: [] }); if (path === "/api/auth/session") return json(route, { ok: true, authenticated: true, csrfToken: "fixture-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master", providers: [], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "now", source: "test", locked: true } }); if (path === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { total: 0 }, total: 0 }, latest: [] }); if (path === "/api/admin/commerce/tax") { const fixture = taxFixture(); return json(route, { ...fixture, registrations: [], registrationState: { configured: false, activeCount: 0, externallyVerified: false } }); } if (path === "/api/admin/commerce/templates") return json(route, templateFixture()); if (path === "/api/admin/commerce/business") return json(route, businessFixture()); return json(route, { ok: false }, 404); });
  await page.goto("http://127.0.0.1:4212/commerce/tax"); await page.getByText("No tax registration configured", { exact: true }).waitFor(); assert.match(await page.locator("body").innerText(), /does not mean registration is legally unnecessary/i); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true);
});

function taxFixture() { return { ok: true, authority: "Commerce D1", access: access(), registrations: [{ id: "tax-1", registrationType: "gst_hst", jurisdiction: "ON", countryCode: "CA", provinceCode: "ON", maskedIdentifier: "••••••••0001", status: "unverified", effectiveDate: null, expiresAt: null, notes: "Operator supplied; verification not integrated", documentDisclosureEnabled: false, revision: 1, updatedAt: "2026-08-29T00:00:00Z" }], registrationState: { configured: true, activeCount: 0, externallyVerified: false }, calculation: { provider: "unconfigured", stripeTax: "not_enabled_unverified", ratesConfigured: false }, documents: { tokenizedAccessSupported: true, customerAccessEnabled: false, deliveryEnabled: false, previewCount: 0, issuedCount: 0, revokedCount: 0, lastGeneratedAt: null, lastGeneratedType: null, lastGeneratedStatus: null }, readiness: { ready: false, status: "blocked", reason: "An explicit tax calculation strategy is required." } }; }
function templateFixture() { return { ok: true, databaseConfigured: true, access: access(), templates: [documentTemplate("payment_receipt", "Payment receipt", "ready", true), documentTemplate("invoice_document", "Invoice / sales document", "draft", false)] }; }
function documentTemplate(templateKey, displayName, status, enabled) { return { templateKey, templateKind: "document", displayName, subject: displayName, preheader: "", heading: displayName, introduction: templateKey === "payment_receipt" ? "Payment confirmed for {{order_reference}}." : "Document for {{order_reference}}.", bodyBlocks: ["{{product_summary}}", "Total: {{order_total}} {{currency}}"], ctaLabel: "", ctaUrl: "", supportText: "Questions? Contact {{support_email}}.", footer: "Third Railify Official", accentColor: "#f3c928", status, enabled, revision: 1 }; }
function businessFixture() { const blocked = (summary, details = {}) => ({ ready: false, status: "blocked", summary, details }); const domains = { business: blocked("Legal identity remains incomplete."), tax: blocked("Tax calculation provider is unconfigured.", { registrationsConfigured: false }), documents: blocked("Receipt ready; invoice blocked.", { receiptTemplateReady: true, invoiceReady: false, customerAccessEnabled: false }), communications: blocked("Production customer sends are disabled.", { providerConfigured: true, readyTemplates: 2, sendEnabled: false }), payments: blocked("Stripe TEST acceptance only."), fulfillment: blocked("Fulfillment submission is disabled.", { enabled: false }), checkout: blocked("Normal checkout is disabled.", { normalCheckoutEnabled: false }) }; return { ok: true, databaseConfigured: true, encryptionConfigured: true, access: access(), authority: "Commerce D1", privacy: { publicSafe: [], adminOnly: [], sensitive: [] }, profile: { tradingName: "Third Railify Official", countryCode: "CA", provinceCode: "ON", currencyCode: "CAD", publicAddress: {}, publicContactEmail: "info@thirdrailify.com", supportEmail: "support@thirdrailify.com", publicPhone: "", websiteUrl: "", invoicePrefix: "", documentFooter: "", taxProviderState: "unavailable", invoiceAccentColor: "#f3c928", receiptAccentColor: "#f3c928", revision: 1, updatedAt: "2026-08-29T00:00:00Z", private: { legalBusinessNameStored: false, privateAddressStored: false, privatePhoneStored: false, businessRegistrationNumberStored: false, legalBusinessNameMasked: "", privateAddressMasked: "", privatePhoneMasked: "", businessRegistrationNumberMasked: "", registrations: [] } }, readiness: { overallStatus: "action_required", completion: { complete: 4, total: 9, percent: 44 }, groups: [], profile: { coreIdentity: "complete", publicContact: "complete", legalIdentity: "not_configured", address: "not_configured", tax: "unverified", documents: "partial", productionCommerce: "action_required" }, dependencies: { ...domains, paypalRequired: false }, documentIdentity: { tradingName: "Third Railify Official", legalNameStored: false, addressStored: false, contactEmail: "support@thirdrailify.com", taxRegistrationState: "unverified", receiptTemplate: { state: "complete", revision: 1 }, invoiceTemplate: { state: "incomplete", revision: 1 } } }, canonicalReadiness: { ok: true, authority: "Commerce D1", phase: "pre_cutover", productionReady: false, mandatoryDomains: Object.keys(domains), domains, checkedAt: "2026-08-29T00:00:00Z" } }; }
function previewFixture(template) { const variables = { order_reference: "TEST-ORDER-PREVIEW", customer_name: "Preview customer", merchant_name: "Third Railify Official", order_total: "15.00", currency: "CAD", product_summary: "Third Rail Farm | Black Glossy Mug — 11 oz / Black × 1", support_email: "support@thirdrailify.com", receipt_url: "https://example.invalid/test", shipping_method: "Not configured", tracking_number: "Not available" }; const merge = (value) => String(value || "").replace(/\{\{\s*([a-z0-9_]+)\s*\}\}/gi, (_, key) => variables[key] || ""); return { ok: true, source: "synthetic_fixture", test: true, orderId: null, variables, preview: { ...template, heading: merge(template.heading), introduction: merge(template.introduction), bodyBlocks: template.bodyBlocks.map(merge), supportText: merge(template.supportText), footer: merge(template.footer), text: "safe", html: "<p>safe</p>" } }; }
function access() { return { isMasterAdmin: true, capabilities: ["commerce.view", "commerce.business.manage", "commerce.templates.manage"] }; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function waitForServer(origin = ORIGIN) { for (let attempt = 0; attempt < 80; attempt += 1) { try { if ((await fetch(origin)).ok) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Vite server did not start."); }
