import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { chromium } from "playwright-core";

const ORIGIN = "http://127.0.0.1:4179"; const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

test("Admin Wheels Library, Access, Results, and detail render across the required matrix", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-v1/", import.meta.url)); await mkdir(artifacts, { recursive: true });
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4179"], { stdio: "ignore" }); t.after(() => server.kill()); await wait(); const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const viewport of [{ width: 1440, height: 900 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) { const context = await browser.newContext({ viewport }); const page = await context.newPage(); const errors = []; page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); await page.route("**/api/**", respond);
    await page.goto(`${ORIGIN}/wheels`); await page.getByRole("heading", { level: 1, name: "Wheels library" }).waitFor(); await page.getByText("Third Railify Demo Draw").waitFor(); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/admin-library-desktop.png`, fullPage: true }); if (viewport.width < 760) { await page.getByRole("button", { name: "Open navigation" }).click(); await page.getByRole("link", { name: "Wheel Access" }).waitFor(); }
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true); assert.deepEqual(errors, []); assert.equal(await page.locator("h1").count(), 1);
    await page.goto(`${ORIGIN}/wheels/access`); await page.getByRole("heading", { level: 1, name: "Wheels access" }).waitFor(); await page.getByText("Approved Creator").first().waitFor(); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/admin-access-desktop.png`, fullPage: true });
    await page.goto(`${ORIGIN}/wheels/results`); await page.getByRole("heading", { level: 1, name: "Official results" }).waitFor(); await page.getByText("Demo GOAT 03").waitFor(); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/admin-results-desktop.png`, fullPage: true });
    await page.goto(`${ORIGIN}/wheels/wheel-demo-id`); await page.getByRole("heading", { level: 1, name: "Third Railify Demo Draw" }).waitFor(); await page.getByText("PARTICIPANT SUMMARY").waitFor(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true); await context.close(); }
});

async function respond(route) { const url = new URL(route.request().url()); if (url.pathname === "/api/auth/config") return json(route, authConfig()); if (url.pathname === "/api/auth/session") return json(route, session()); if (url.pathname === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { total: 0, submissions: 0, comments: 0, emailFailures: 0 } } }); if (url.pathname === "/api/admin/wheels" ) return json(route, { ok: true, items: [wheel()] }); if (url.pathname === "/api/admin/wheels/settings") return json(route, { ok: true, settings: { defaultTheme: "third-rail-gold", maximumParticipants: 1000, maximumWheelsPerCreator: 20, officialSpinCooldownSeconds: 2, defaultCelebrationIntensity: "full", defaultPublicHistory: true }, revision: 1, updatedAt: "2026-08-29T00:00:00.000Z" }); if (url.pathname === "/api/admin/wheels/access") return json(route, access()); if (url.pathname === "/api/admin/wheels/accounts") return json(route, { ok: true, accounts: [account()] }); if (url.pathname === "/api/admin/wheels/results") return json(route, { ok: true, items: [result()] }); if (url.pathname === "/api/admin/wheels/wheel-demo-id") return json(route, { ok: true, item: { ...wheel(), config: { themePreset: "third-rail-gold" }, entries: [{ id: "entry-1", label: "Demo GOAT 03", order: 0, weight: 2, colour: "#F3C928", state: "active" }], access: [{ account: account(), role: "owner", active: true, updatedAt: "2026-08-29T00:00:00.000Z" }], results: [result()] } }); return json(route, { ok: false, error: "not_found" }, 404); }
function account() { return { id: "creator", displayName: "Approved Creator", email: "creator@example.test", role: "user", adminLevel: "none" }; }
function wheel() { return { id: "wheel-demo-id", reference: "DEMO-WHEEL-01", slug: "third-railify-demo-draw", title: "Third Railify Demo Draw", description: "Synthetic fixture", lifecycle: "active", visibility: "public", owner: account(), participantCount: 8, revision: 7, officialEnabled: true, demoEnabled: true, editingLocked: false, spinLocked: false, latestWinner: "Demo GOAT 03", latestResultAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }; }
function access() { return { ok: true, grants: [{ account: account(), active: true, mayCreate: true, maximumOwnedWheels: 20, updatedAt: "2026-08-29T00:00:00.000Z" }], assignments: [{ wheelId: "wheel-demo-id", wheelTitle: "Third Railify Demo Draw", wheelSlug: "third-railify-demo-draw", account: account(), role: "owner", active: true, updatedAt: "2026-08-29T00:00:00.000Z" }] }; }
function result() { return { id: "spin-demo", wheelId: "wheel-demo-id", wheelTitle: "Third Railify Demo Draw", wheelSlug: "third-railify-demo-draw", winningEntryId: "entry-1", winningLabel: "Demo GOAT 03", winningWeight: 2, wheelRevision: 7, snapshotHash: "a".repeat(64), performedByAccountId: "creator", performer: account(), idempotencyKey: "demo-idempotency-key", createdAt: "2026-08-29T00:00:00.000Z", voided: false, voidedAt: null, voidReason: null, voidedBy: null }; }
function authConfig() { return { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }; }
function session() { return { ok: true, authenticated: true, csrfToken: "admin-wheel-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master Admin", username: null, avatarUrl: null, providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", lastLoginAt: null, source: "env_master", locked: true } }; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function wait() { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Admin preview did not start."); }
