import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import test from "node:test";
import { chromium } from "playwright-core";
import { calculateNaturalnessDiagnostics, cloneDefaultWheelMechanics, compileVelocityProfile } from "../src/wheels/mechanics.mjs";

const ORIGIN = "http://127.0.0.1:4179"; const CHROME = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";

test("Admin Wheels Overview, Library, Mechanics, Stages, Access, Results, and detail render across the required matrix", async (t) => {
  const artifacts = fileURLToPath(new URL("../.artifacts/wheels-mechanics-v2/", import.meta.url)); await mkdir(artifacts, { recursive: true }); const natural = compileVelocityProfile(cloneDefaultWheelMechanics()); await writeFile(`${artifacts}/sampled-metrics.json`, JSON.stringify({ generatedAt: new Date().toISOString(), profile: natural.mechanics.curveProfile, coefficients: natural.mechanics.physics, sampleCount: natural.sampleCount, sampleTimes: [.1, .25, .5, .75, .9, .97].map((u) => ({ u, velocity: natural.velocity[Math.round(u * (natural.sampleCount - 1))], progress: natural.progress[Math.round(u * (natural.sampleCount - 1))] })), diagnostics: calculateNaturalnessDiagnostics(natural) }, null, 2));
  const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "preview", "--host", "127.0.0.1", "--port", "4179"], { stdio: "ignore" }); t.after(() => server.kill()); await wait(); const browser = await chromium.launch({ executablePath: CHROME, headless: true }); t.after(() => browser.close());
  for (const viewport of [{ width: 1920, height: 1080 }, { width: 1600, height: 900 }, { width: 1440, height: 900 }, { width: 1365, height: 768 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 430, height: 932 }, { width: 390, height: 844 }]) {
    const context = await browser.newContext({ viewport }); const page = await context.newPage(); const errors = []; let settingsPosts = 0; page.on("console", (entry) => { if (entry.type() === "error") errors.push(entry.text()); }); page.on("pageerror", (error) => errors.push(error.message)); page.on("request", (request) => { if (new URL(request.url()).pathname === "/api/admin/wheels/settings" && request.method() === "POST") settingsPosts += 1; }); await page.route("**/api/**", respond);
    await page.goto(`${ORIGIN}/wheels`); await page.getByRole("heading", { level: 1, name: "Wheels Overview" }).waitFor(); await page.getByText("Natural Hybrid").waitFor(); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/admin-overview-desktop.png`, fullPage: true }); if (viewport.width < 760) { await page.getByRole("button", { name: "Open navigation" }).click(); await page.getByRole("link", { name: "Wheel Library", exact: true }).waitFor(); }
    await page.goto(`${ORIGIN}/wheels/library`); await page.getByRole("heading", { level: 1, name: "Wheel Library" }).waitFor(); await page.getByText("Third Railify Demo Draw").waitFor(); if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/admin-library-desktop.png`, fullPage: true });
    await page.goto(`${ORIGIN}/wheels/mechanics`); await page.getByRole("heading", { level: 1, name: "Wheel Mechanics" }).waitFor(); await page.getByRole("img", { name: "Natural Hybrid angular velocity graph" }).first().waitFor(); assert.equal(await page.getByRole("button", { name: /SELECTED Natural Hybrid/ }).getAttribute("aria-pressed"), "true");
    if (viewport.width === 1440) {
      await page.screenshot({ path: `${artifacts}/01-admin-natural-hybrid.png`, fullPage: true });
      await page.getByRole("img", { name: "Natural Hybrid angular velocity graph" }).last().screenshot({ path: `${artifacts}/02-natural-velocity.png` });
      await page.getByRole("img", { name: "Natural Hybrid angular deceleration graph" }).screenshot({ path: `${artifacts}/03-natural-deceleration.png` });
      await page.getByRole("img", { name: "Natural Hybrid cumulative rotation graph" }).screenshot({ path: `${artifacts}/04-natural-progress.png` });
      await page.locator(".mechanics-panel").filter({ hasText: "2 · PHYSICS CONTROLS" }).screenshot({ path: `${artifacts}/06-physics-controls.png` });
      await page.locator(".mechanics-panel").filter({ hasText: "3 · ADVANCED CURVE" }).screenshot({ path: `${artifacts}/07-custom-shape-editor.png` });
      await page.locator(".mechanics-panel").filter({ hasText: "8 · NATURALNESS DIAGNOSTICS" }).screenshot({ path: `${artifacts}/08-naturalness-diagnostics.png` });
      await page.locator(".curve-preset-grid").screenshot({ path: `${artifacts}/10-preset-gallery.png` });
      await page.getByLabel("Preview duration").selectOption("3"); await page.getByRole("button", { name: "Preview spin" }).click(); await page.waitForTimeout(180); await page.locator(".mechanics-preview").screenshot({ path: `${artifacts}/11-preview-early.png` }); await page.waitForTimeout(1050); await page.locator(".mechanics-preview").screenshot({ path: `${artifacts}/12-preview-middle.png` }); await page.waitForTimeout(1380); await page.locator(".mechanics-preview").screenshot({ path: `${artifacts}/13-preview-tail.png` }); await page.waitForTimeout(650); await page.locator(".mechanics-preview").screenshot({ path: `${artifacts}/14-preview-settled.png` });
    }
    await page.getByRole("button", { name: /SELECT Quick Draw/ }).click(); assert.equal(await page.getByRole("button", { name: /SELECTED Quick Draw/ }).getAttribute("aria-pressed"), "true");
    await page.getByRole("button", { name: "Discard" }).click(); assert.equal(await page.getByRole("button", { name: /SELECTED Natural Hybrid/ }).getAttribute("aria-pressed"), "true");
    await page.getByRole("button", { name: /SELECT Heavy Flywheel/ }).click(); await page.getByRole("button", { name: "Reset to Natural Hybrid" }).click(); assert.equal(await page.getByRole("button", { name: /SELECTED Natural Hybrid/ }).getAttribute("aria-pressed"), "true");
    await page.getByRole("button", { name: /SELECT Quick Draw/ }).click();
    if (viewport.width === 1440) {
      await page.getByRole("img", { name: "Quick Draw angular velocity graph" }).last().screenshot({ path: `${artifacts}/05-current-vs-draft-overlay.png` });
      await page.getByRole("img", { name: "Quick Draw angular velocity graph" }).last().screenshot({ path: `${artifacts}/18-quick-draw.png` });
      await page.getByRole("button", { name: /SELECT Heavy Flywheel/ }).click(); await page.getByRole("img", { name: "Heavy Flywheel angular velocity graph" }).last().screenshot({ path: `${artifacts}/16-heavy-flywheel.png` });
      await page.getByRole("button", { name: /SELECT Suspense Tail/ }).click(); await page.getByRole("img", { name: "Suspense Tail angular velocity graph" }).last().screenshot({ path: `${artifacts}/17-suspense-tail.png` });
      await page.getByRole("button", { name: /SELECT Mechanical Clicker/ }).click(); await page.getByRole("img", { name: "Mechanical Clicker angular velocity graph" }).last().screenshot({ path: `${artifacts}/19-mechanical-clicker.png` });
      await page.getByRole("button", { name: /SELECT Legacy Broadcast Smooth/ }).click(); await page.locator(".mechanics-panel").filter({ hasText: "8 · NATURALNESS DIAGNOSTICS" }).screenshot({ path: `${artifacts}/09-handbrake-risk.png` }); await page.getByLabel("Preview duration").selectOption("3"); await page.getByRole("button", { name: "Preview spin" }).click(); await page.waitForTimeout(2610); await page.locator(".mechanics-preview").screenshot({ path: `${artifacts}/15-v112-ending-comparison.png` }); await page.getByRole("button", { name: "Stop / reset" }).click();
      await page.getByRole("button", { name: /SELECT Quick Draw/ }).click();
    }
    const saveButton = page.getByRole("button", { name: "Save Mechanics" }); assert.equal(await saveButton.isEnabled(), true); assert.match(await page.locator(".mechanics-savebar").innerText(), /Unsaved mechanics draft/); assert.equal(await saveButton.evaluate((button) => button.getAttribute("type")), "submit"); const validity = await page.locator("form.wheel-mechanics-page").evaluate((form) => ({ valid: form.checkValidity(), invalid: [...form.querySelectorAll(":invalid")].map((item) => ({ label: item.parentElement?.textContent, value: item.value })) })); assert.deepEqual(validity, { valid: true, invalid: [] }); await saveButton.click(); await page.waitForTimeout(500); assert.equal(settingsPosts, 1); assert.equal(await page.locator(".admin-alert").allTextContents().then((items) => items.join(" | ")), ""); const savedToast = page.locator(".admin-toast").filter({ hasText: "Mechanics saved at policy revision 2." }); await savedToast.waitFor(); assert.equal(await page.getByRole("button", { name: /SELECTED Natural Hybrid/ }).getAttribute("aria-pressed"), "true");
    await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight)); const toastGeometry = await page.locator(".admin-toast-region").evaluate((node) => { const rect = node.getBoundingClientRect(); return { position: getComputedStyle(node).position, top: rect.top, bottom: rect.bottom, viewport: innerHeight }; }); assert.equal(toastGeometry.position, "fixed"); assert.equal(toastGeometry.top >= 0 && toastGeometry.bottom <= toastGeometry.viewport, true); assert.equal(await page.locator(".admin-alert--success").count(), 0);
    if (viewport.width === 1440) await page.screenshot({ path: `${artifacts}/admin-mechanics-toast-desktop.png` }); if (viewport.width === 390) await page.screenshot({ path: `${artifacts}/20-admin-mobile-mechanics.png`, fullPage: true }); await savedToast.getByRole("button", { name: "Dismiss notification" }).click(); await savedToast.waitFor({ state: "detached" });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true); assert.deepEqual(errors, []); assert.equal(await page.locator("h1").count(), 1);
    await page.goto(`${ORIGIN}/wheels/stages`); await page.getByRole("heading", { level: 1, name: "Wheels Stages" }).waitFor(); await page.getByText("Demo Stage").waitFor();
    await page.goto(`${ORIGIN}/wheels/access`); await page.getByRole("heading", { level: 1, name: "Wheels access" }).waitFor(); await page.getByText("Approved Creator").first().waitFor();
    await page.goto(`${ORIGIN}/wheels/results`); await page.getByRole("heading", { level: 1, name: "Official results" }).waitFor(); await page.getByText("Demo GOAT 03").waitFor();
    await page.goto(`${ORIGIN}/wheels/wheel-demo-id`); await page.getByRole("heading", { level: 1, name: "Third Railify Demo Draw" }).waitFor(); await page.getByText("PARTICIPANT SUMMARY").waitFor(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true); await context.close();
  }
});

async function respond(route) {
  const url = new URL(route.request().url()); if (url.pathname === "/api/auth/config") return json(route, authConfig()); if (url.pathname === "/api/auth/session") return json(route, session()); if (url.pathname === "/api/admin/inbox/summary") return json(route, { ok: true, unread: 0, actionable: { goats: { total: 0, submissions: 0, comments: 0, emailFailures: 0 } } }); if (url.pathname === "/api/admin/wheels") return json(route, { ok: true, items: [wheel()] }); if (url.pathname === "/api/admin/wheels/settings") return json(route, settings(url, route.request().method())); if (url.pathname === "/api/admin/wheels/stages") return json(route, { ok: true, items: [stage()] }); if (url.pathname === "/api/admin/wheels/access") return json(route, access()); if (url.pathname === "/api/admin/wheels/accounts") return json(route, { ok: true, accounts: [account()] }); if (url.pathname === "/api/admin/wheels/results") return json(route, { ok: true, items: [result()] }); if (url.pathname === "/api/admin/wheels/wheel-demo-id") return json(route, { ok: true, item: { ...wheel(), config: { themePreset: "third-rail-gold" }, entries: [{ id: "entry-1", label: "Demo GOAT 03", order: 0, weight: 2, colour: "#F3C928", state: "active" }], access: [{ account: account(), role: "owner", active: true, updatedAt: "2026-08-29T00:00:00.000Z" }], results: [result()], media: [] } }); return json(route, { ok: false, error: "not_found" }, 404);
}
function mechanics() { return cloneDefaultWheelMechanics(); }
function settings(_url, method) { return { ok: true, settings: { defaultTheme: "third-rail-gold", maximumParticipants: 1000, maximumWheelsPerCreator: 20, officialSpinCooldownSeconds: 2, defaultCelebrationIntensity: "full", defaultPublicHistory: true, mechanics: mechanics() }, revision: method === "POST" ? 2 : 1, updatedAt: "2026-08-31T00:00:00.000Z" }; }
function account() { return { id: "creator", displayName: "Approved Creator", email: "creator@example.test", role: "user", adminLevel: "none" }; }
function wheel() { return { id: "wheel-demo-id", reference: "DEMO-WHEEL-01", slug: "thirdrailify-demo-draw", title: "Third Railify Demo Draw", description: "Synthetic fixture", lifecycle: "active", visibility: "public", owner: account(), participantCount: 8, revision: 7, officialEnabled: true, demoEnabled: true, editingLocked: false, spinLocked: false, latestWinner: "Demo GOAT 03", latestResultAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }; }
function stage() { return { id: "stage-demo", slug: "demo-stage", title: "Demo Stage", description: "Synthetic Stage", owner: account(), visibility: "public", lifecycle: "active", revision: 2, wheelCount: 1, createdAt: "2026-08-29T00:00:00.000Z", updatedAt: "2026-08-29T00:00:00.000Z" }; }
function access() { return { ok: true, grants: [{ account: account(), active: true, mayCreate: true, maximumOwnedWheels: 20, updatedAt: "2026-08-29T00:00:00.000Z" }], assignments: [{ wheelId: "wheel-demo-id", wheelTitle: "Third Railify Demo Draw", wheelSlug: "thirdrailify-demo-draw", account: account(), role: "owner", active: true, updatedAt: "2026-08-29T00:00:00.000Z" }] }; }
function result() { return { id: "spin-demo", wheelId: "wheel-demo-id", wheelTitle: "Third Railify Demo Draw", wheelSlug: "thirdrailify-demo-draw", winningEntryId: "entry-1", winningLabel: "Demo GOAT 03", winningWeight: 2, wheelRevision: 7, snapshotHash: "a".repeat(64), performedByAccountId: "creator", performer: account(), idempotencyKey: "demo-idempotency-key", createdAt: "2026-08-29T00:00:00.000Z", voided: false, voidedAt: null, voidReason: null, voidedBy: null }; }
function authConfig() { return { configured: true, emailSignupConfigured: true, turnstileSiteKey: null, oauthProviders: [], oauthProviderStates: [], publicOrigin: "https://thirdrailify.pages.dev", adminOrigin: ORIGIN, environment: "test", cookieMode: "host-only" }; }
function session() { return { ok: true, authenticated: true, csrfToken: "admin-wheel-csrf", access: { isAdmin: true, isMasterAdmin: true }, account: { id: "master", email: "master@example.test", displayName: "Master Admin", username: null, avatarUrl: null, providers: ["email"], role: "admin", adminLevel: "master", status: "active", emailVerified: true, createdAt: "2026-08-29T00:00:00.000Z", lastLoginAt: null, source: "env_master", locked: true } }; }
function json(route, body, status = 200) { return route.fulfill({ status, contentType: "application/json", body: JSON.stringify(body) }); }
async function wait() { for (let attempt = 0; attempt < 60; attempt += 1) { try { if ((await fetch(ORIGIN)).ok) return; } catch { /* starting */ } await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Admin preview did not start."); }
