import { adminApi } from "../auth/client";

export type GamingGame = { id:string;title:string;slug:string|null;platform:string;description:string;genre:string;developer:string|null;publisher:string|null;steam:{appId:string|null;storeUrl:string|null;state:"unverified"|"verified"|"manual_override";provenance:string};artwork:{url:string|null;source:"uploaded"|"remote"|"fallback";assetId:string|null;width:number|null;height:number|null};rotation:{inRotation:boolean;position:number|null;addedAt:string|null};archived:boolean;archivedAt:string|null;createdAt:string;updatedAt:string };
export type GamingPayload = { ok:true;authority:string;access:{isAdmin:boolean;isMasterAdmin:boolean;capabilities:string[]};steamCatalogue:{configured:boolean;implemented:boolean;method:string;message:string};games:GamingGame[];rotation:GamingGame[];summary:{rotation:number;library:number;missingArtwork:number;missingSteam:number};checkedAt:string;mutation?:{gameId:string} };
export type GamingDraft = { id?:string;title:string;slug:string;platform:string;description:string;genre:string;developer:string;publisher:string;steamAppId:string;steamStoreUrl:string;steamState:"unverified"|"verified"|"manual_override";provenance:"manual"|"steam_verified"|"manual_override";remoteArtworkUrl:string };

export const getGaming = () => adminApi<GamingPayload>("/api/admin/gaming");
export const mutateGaming = (csrfToken:string, body:Record<string,unknown>) => adminApi<GamingPayload>("/api/admin/gaming", { method:"POST", headers:{"X-CSRF-Token":csrfToken}, body:JSON.stringify(body) });
export async function uploadGamingArtwork(csrfToken:string, gameId:string, file:File) { const response=await fetch(`/api/admin/gaming/${encodeURIComponent(gameId)}/artwork`,{method:"POST",credentials:"include",cache:"no-store",headers:{"Content-Type":file.type,"X-CSRF-Token":csrfToken,"X-File-Name":file.name},body:file});const payload=await response.json().catch(()=>null) as (GamingPayload&{message?:string})|null;if(!response.ok||!payload?.ok)throw new Error(payload?.message||"Artwork could not be uploaded.");return payload; }
export function steamSearchUrl(title:string){return `https://store.steampowered.com/search/?term=${encodeURIComponent(title.trim())}`;}
