import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import { getAdminPolls, mutatePollLifecycle, mutatePollVisibility, type AdminPoll } from '../polls/admin-client';
import { pollAdminRequest } from '../polls/admin-request';
import '../styles/polls-admin.css';

type ImageAsset = { id: string; url: string };
type Matchup = Omit<AdminPoll, 'options'> & { presentationType?: string; presentation?: { colors?: string[]; context?: string | null; featuredOrder?: number }; credits?: { unresolved: number }; media?: { banner?: ImageAsset }; options: Array<AdminPoll['options'][number] & { description?: string; image?: ImageAsset }> };
const empty = { livestreamMode: 'automatic', livestreamId: '', title: '', description: '', rumbleEnabled: false, rumbleSourceScope: '', presentationType: 'abootnothing', presentation: { colors: ['#f3c928', '#a9b7da'], context: '', featuredOrder: 0 }, options: [{ label: 'Side one', trigger: '1', description: '' }, { label: 'Side two', trigger: '2', description: '' }] };
export function AbootNothingPage() {
  const { csrfToken, hasCapability } = useAuth(); const canManage = hasCapability('polls.manage');
  const [discovery, setDiscovery] = useState<{ source: { scope: string; displayName: string } | null; livestreams: Array<{ id: string; title: string; isLive: boolean }> } | null>(null);
  useEffect(() => { void pollAdminRequest<NonNullable<typeof discovery>>("/api/admin/polls/discovery").then(setDiscovery).catch(() => setDiscovery(null)); }, []);
  const [items, setItems] = useState<Matchup[]>([]), [selected, setSelected] = useState<Matchup | null>(null), [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(empty), [state, setState] = useState('all'), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const p = await getAdminPolls(state, 'abootnothing'); setItems((p.items as Matchup[]).filter(p => p.presentationType === 'abootnothing')); } catch (e) { setError(String(e)); } }, [state]);
  useEffect(() => { void load(); }, [load]);
  const edit = (poll: Matchup | null) => { setSelected(poll); setEditing(true); setDraft(poll ? { ...empty, ...poll, description: poll.description || '', rumbleSourceScope: poll.rumbleSourceScope || '', presentationType: 'abootnothing', presentation: { colors: poll.presentation?.colors || empty.presentation.colors, context: poll.presentation?.context || '', featuredOrder: poll.presentation?.featuredOrder || 0 }, options: poll.options.map(o => ({ ...o, description: o.description || '' })) } : structuredClone(empty)); };
  const action = async (fn: () => Promise<unknown>) => { setBusy(true); setError(''); try { await fn(); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save matchup.'); } finally { setBusy(false); } };
  const save = (e: FormEvent) => { e.preventDefault(); void action(async () => { const value = await pollAdminRequest<{ poll: Matchup }>(`/api/admin/polls/${selected ? `${selected.slug}/save` : 'create'}`, csrfToken || '', { ...draft, options: selected?.state === 'open' ? undefined : draft.options, revision: selected?.revision }); edit(value.poll); }); };
  const upload = async (file: File, index?: number) => { if (!selected) return; await action(async () => { const form = new FormData(); form.set('image', file); const url = `/api/admin/polls/${selected.slug}/media/${index === undefined ? 'banner' : `option/${selected.options[index].id}`}`; const response = await fetch(url, { method: 'POST', credentials: 'include', headers: { 'X-CSRF-Token': csrfToken || '' }, body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.message); const value = await pollAdminRequest<{ poll: Matchup }>(`/api/admin/polls/${selected.slug}`); edit(value.poll); }); };
  const locked = selected?.state === 'open' || Boolean(selected?.totalVotes || selected?.credits?.unresolved);
  return <div className="poll-admin aboot-admin"><header className="poll-heading"><div><p className="eyebrow">THE THIRD RAIL · CONTENT & OPERATIONS</p><h1>Aboot Nothing</h1><p>Two opposing subjects. One Poll, shared votes and a permanent matchup history.</p></div><div><button className="primary-button" disabled={!canManage || busy} onClick={() => edit(null)}>Create matchup</button><Link to="/automations#poll-voting">Voting policy & reconciliation</Link></div></header>{error ? <p role="alert">{error}</p> : null}
    <section className="poll-panel"><label>Matchups<select value={state} onChange={e => setState(e.target.value)}><option value="all">All matchups</option><option value="open">Current</option><option value="closed">Past</option><option value="draft">Drafts</option><option value="archived">Archived</option></select></label><div className="aboot-admin-grid">{items.map(p => <article key={p.id}><div className="aboot-admin-versus">{p.options.map((o, i) => <div key={o.id} style={{ borderColor: p.presentation?.colors?.[i] }} >{o.image ? <img src={p.public ? o.image.url : `/api/admin/polls/media/${o.image.id}`} alt="" /> : null}<strong>{o.label}</strong></div>)}<b>VS</b></div><h2>{p.title}</h2><p>{p.state} · {p.public ? 'Listed' : 'Hidden'} · {p.totalVotes} votes · {p.credits?.unresolved ?? 'Unknown'} awaiting allocation</p><div className="poll-actions"><button disabled={!canManage || busy} onClick={() => edit(p)}>Edit matchup</button>{p.state === 'open' ? <button disabled={!canManage || busy} onClick={() => void action(() => mutatePollLifecycle(csrfToken || '', p, 'close'))}>Close</button> : p.state !== 'archived' ? <button disabled={!canManage || busy} onClick={() => void action(() => mutatePollLifecycle(csrfToken || '', p, 'open'))}>Open</button> : null}{p.state === 'closed' ? <button disabled={!canManage || busy} onClick={() => void action(() => mutatePollVisibility(csrfToken || '', p, !p.public))}>{p.public ? 'Hide' : 'List'}</button> : null}{['draft', 'closed'].includes(p.state) ? <button disabled={!canManage || busy} onClick={() => void action(() => mutatePollLifecycle(csrfToken || '', p, 'archive'))}>Archive</button> : null}{p.state === 'archived' ? <button disabled={!canManage || busy} onClick={() => void action(() => mutatePollLifecycle(csrfToken || '', p, 'restore'))}>Restore draft</button> : null}<a href={`https://thirdrailify.com/polls/${p.slug}`}>Public detail</a></div></article>)}</div>{!items.length ? <p>No matchups in this view.</p> : null}</section>
    {editing ? <form className="poll-panel automation-fields" onSubmit={save}><header><h2>{selected ? 'Edit matchup' : 'New matchup'}</h2><button type="button" onClick={() => setEditing(false)}>Close editor</button></header><label>Title<input required maxLength={140} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label>Context / episode<input maxLength={160} value={draft.presentation.context} onChange={e => setDraft({ ...draft, presentation: { ...draft.presentation, context: e.target.value } })} /></label><label>Description<textarea maxLength={2000} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label>
    {selected?.state === 'open' ? <p>Subject names, descriptions and triggers stay fixed while voting is open. Colours and artwork can still be updated.</p> : null}<div className="aboot-admin-grid">{draft.options.map((option, i) => <fieldset key={i}><legend>Opposing item {i + 1}</legend><label>Name<input required disabled={selected?.state === 'open'} maxLength={160} value={option.label} onChange={e => setDraft({ ...draft, options: draft.options.map((o, n) => n === i ? { ...o, label: e.target.value } : o) })} /></label><label>Trigger<input required disabled={locked} value={option.trigger} onChange={e => setDraft({ ...draft, options: draft.options.map((o, n) => n === i ? { ...o, trigger: e.target.value } : o) })} /></label><label>Description<input disabled={selected?.state === 'open'} maxLength={240} value={option.description} onChange={e => setDraft({ ...draft, options: draft.options.map((o, n) => n === i ? { ...o, description: e.target.value } : o) })} /></label><label>Feature colour<input type="color" value={draft.presentation.colors[i]} onChange={e => setDraft({ ...draft, presentation: { ...draft.presentation, colors: draft.presentation.colors.map((c, n) => n === i ? e.target.value : c) } })} /></label>{selected?.options[i]?.image ? <img className="aboot-admin-preview" src={`/api/admin/polls/media/${selected.options[i].image!.id}`} alt={`${option.label} artwork`} /> : null}<label>Square artwork<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!selected || busy} onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file, i); }} /></label></fieldset>)}</div>
    <label>Cover image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!selected || busy} onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); }} /></label>{selected?.media?.banner ? <img className="aboot-admin-preview" src={`/api/admin/polls/media/${selected.media.banner.id}`} alt="Matchup cover" /> : null}<small>Save first, then add or replace artwork.</small><label>Featured order (0 = automatic)<input type="number" min={0} max={999} value={draft.presentation.featuredOrder} onChange={e => setDraft({ ...draft, presentation: { ...draft.presentation, featuredOrder: Number(e.target.value) } })} /></label><label><input type="checkbox" disabled={selected?.state === 'open'} checked={draft.rumbleEnabled} onChange={e => setDraft({ ...draft, rumbleEnabled: e.target.checked })} />Rumble ordinary chat</label><label>Detected source<select disabled={selected?.state === 'open'} value={draft.rumbleSourceScope === discovery?.source?.scope ? draft.rumbleSourceScope : ''} onChange={e => setDraft({ ...draft, rumbleSourceScope: e.target.value })}><option value="">Custom source / discovery unavailable</option>{discovery?.source ? <option value={discovery.source.scope}>{discovery.source.displayName} ({discovery.source.scope})</option> : null}</select></label><label>Stream selection<select disabled={selected?.state === 'open'} value={draft.livestreamMode === 'automatic' ? '' : draft.livestreamId} onChange={e => setDraft({ ...draft, livestreamMode: e.target.value ? 'exact' : 'automatic', livestreamId: e.target.value })}><option value="">Automatic (one detected live stream)</option>{discovery?.livestreams.filter(s => s.isLive).map(s => <option key={s.id} value={s.id}>{s.title} ({s.id})</option>)}{draft.livestreamId && !discovery?.livestreams.some(s => s.id === draft.livestreamId) ? <option value={draft.livestreamId}>{draft.livestreamId}</option> : null}</select></label><label>Rumble source<input disabled={selected?.state === 'open'} value={draft.rumbleSourceScope} placeholder="user:… or channel:…" onChange={e => setDraft({ ...draft, rumbleSourceScope: e.target.value })} /></label><button className="primary-button" disabled={busy || !canManage}>Save matchup</button></form> : null}
  </div>;
}
