import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { AdminIcon } from "../components/AdminIcon";
import { useAuth } from "../auth/AuthProvider";
import { AuthClientError } from "../auth/types";
import { getGaming, mutateGaming, resolveSteamApp, searchSteam, steamSearchUrl, uploadGamingArtwork, type GamingDraft, type GamingGame, type GamingPayload, type SteamGame, type SteamSearchResult } from "../gaming/client";
import "../styles/gaming-admin.css";

const blank:GamingDraft={title:"",slug:"",platform:"PC via Steam",description:"",genre:"",developer:"",publisher:"",steamAppId:"",steamStoreUrl:"",steamState:"unverified",provenance:"manual",remoteArtworkUrl:""};
type Filter="all"|"rotation"|"library"|"artwork"|"steam"|"archived";

export function GamingAdminPage(){
  const {csrfToken,hasCapability}=useAuth();const canManage=hasCapability("gaming.manage");const [payload,setPayload]=useState<GamingPayload|null>(null);const [error,setError]=useState<{code:string;message:string}|null>(null);const [busy,setBusy]=useState("");const [search,setSearch]=useState("");const [filter,setFilter]=useState<Filter>("all");const [editing,setEditing]=useState<GamingGame|null|"new">(null);
  const load=useCallback(async()=>{try{setError(null);setPayload(await getGaming());}catch(reason){setError(reason instanceof AuthClientError?{code:reason.code,message:reason.message}:{code:"gaming_query_failed",message:reason instanceof Error?reason.message:"Gaming authority is unavailable."});}},[]);useEffect(()=>{void load();},[load]);
  const act=async(body:Record<string,unknown>,key:string)=>{try{setBusy(key);setError(null);setPayload(await mutateGaming(csrfToken,body));}catch(reason){setError({code:reason instanceof AuthClientError?reason.code:"gaming_action_failed",message:reason instanceof Error?reason.message:"The Gaming action failed."});}finally{setBusy("");}};
  const games=useMemo(()=>payload?.games.filter((game)=>{const q=search.trim().toLowerCase();const matches=!q||`${game.title} ${game.steam.appId||""} ${game.steam.storeUrl||""}`.toLowerCase().includes(q);const state=filter==="all"||filter==="rotation"&&game.rotation.inRotation||filter==="library"&&!game.rotation.inRotation&&!game.archived||filter==="artwork"&&!game.artwork.url||filter==="steam"&&game.steam.state!=="verified"||filter==="archived"&&game.archived;return matches&&state;})||[],[payload,search,filter]);
  return <main className="gaming-admin" aria-labelledby="gaming-admin-title">
    <header className="gaming-admin__hero"><div><p className="eyebrow">ADMIN-OWNED PROGRAMMING AUTHORITY</p><h1 id="gaming-admin-title">Third Railify <span>Gaming</span></h1><p>Curate the permanent Game Library and the ordered Current Rotation consumed by the Public Gaming page.</p></div><div className="gaming-admin__hero-actions"><a href="https://thirdrailify.com/gaming" target="_blank" rel="noreferrer">Open Public Gaming <AdminIcon name="external"/></a><button type="button" onClick={()=>setEditing("new")} disabled={!canManage}><AdminIcon name="gaming"/> Add game</button></div></header>
    {error?.code==="gaming_migration_required"?<section className="gaming-migration-state" role="alert"><AdminIcon name="signal" size={30}/><div><p className="eyebrow">GAMING DATABASE MIGRATION REQUIRED</p><h2>Gaming database update required</h2><p>The Gaming catalogue schema is not available in this environment yet. Apply the approved Gaming migration before using the Library or Current Rotation.</p></div></section>:error&&<div className="admin-alert" role="alert">{error.message}</div>}
    {payload&&<section className="gaming-metrics" aria-label="Gaming catalogue summary">{[["Current rotation",payload.summary.rotation],["Historical library",payload.summary.library],["Missing artwork",payload.summary.missingArtwork],["Steam unverified",payload.summary.missingSteam]].map(([label,value])=><article key={String(label)}><strong>{value}</strong><span>{label}</span></article>)}</section>}
    {payload&&<div className="gaming-steam-status" role="status"><AdminIcon name="link"/><div><strong>{payload.steamCatalogue.available?"Steam lookup configured":"Steam lookup not configured"}</strong><p>Steam Store lookup with independent Community and embedded catalogue fallbacks{payload.steamCatalogue.officialCatalogueConfigured?" and optional official catalogue verification":"; manual entry remains available"}.</p></div><code>{payload.steamCatalogue.method}</code></div>}
    <section className="gaming-workspace" aria-labelledby="current-rotation-title"><header><div><p className="eyebrow">PUBLIC PROGRAMMING ORDER</p><h2 id="current-rotation-title">Current Rotation</h2></div><span className="gaming-authority-chip"><i/> Dynamic · 3 minute edge freshness</span></header>
      {!payload?<State text={error?"Current Rotation unavailable":"Loading Current Rotation…"}/>:payload.rotation.length?<div className="gaming-rotation-list">{payload.rotation.map((game,index)=><article key={game.id}><Cover game={game}/><div className="gaming-rotation-list__copy"><span>POSITION {String(game.rotation.position).padStart(2,"0")}</span><h3>{game.title}</h3><p>{game.platform} · {game.genre||"Genre not supplied"}</p><Quality game={game}/></div><div className="gaming-row-actions"><button aria-label={`Move ${game.title} up`} disabled={!canManage||index===0||Boolean(busy)} onClick={()=>void act({action:"move",gameId:game.id,direction:"up"},game.id)}><AdminIcon name="moveUp"/> Move up</button><button aria-label={`Move ${game.title} down`} disabled={!canManage||index===payload.rotation.length-1||Boolean(busy)} onClick={()=>void act({action:"move",gameId:game.id,direction:"down"},game.id)}><AdminIcon name="moveDown"/> Move down</button><button onClick={()=>setEditing(game)}><AdminIcon name="edit"/> Edit</button><button className="is-remove" disabled={!canManage||Boolean(busy)} onClick={()=>{if(confirm(`Remove ${game.title} from Current Rotation? The historical Game Library record will remain.`))void act({action:"remove_from_rotation",gameId:game.id},game.id);}}>Remove from rotation</button></div></article>)}</div>:<State text="Current Rotation is configured empty. Add a Library game when programming is ready."/>}
    </section>
    <section className="gaming-workspace" aria-labelledby="game-library-title"><header><div><p className="eyebrow">PERMANENT HISTORICAL REGISTER</p><h2 id="game-library-title">Game Library</h2></div></header>
      <div className="gaming-library-tools"><label><span className="sr-only">Search Game Library</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title, Steam App ID, or URL"/></label><nav aria-label="Game Library filters">{(["all","rotation","library","artwork","steam","archived"] as Filter[]).map(value=><button key={value} className={filter===value?"is-active":""} onClick={()=>setFilter(value)}>{value==="library"?"Not in rotation":value==="artwork"?"Missing artwork":value==="steam"?"Missing Steam":value}</button>)}</nav></div>
      <div className="gaming-library-table" role="table" aria-label="Historical Game Library"><div className="gaming-library-table__head" role="row"><span>Artwork</span><span>Game</span><span>Steam</span><span>Rotation</span><span>Updated</span><span>Actions</span></div>{games.map(game=><div role="row" key={game.id} className={game.archived?"is-archived":""}><span role="cell"><Cover game={game}/></span><span role="cell"><strong>{game.title}</strong><small>{game.platform}</small><Quality game={game}/></span><span role="cell"><b>{game.steam.state==="verified"?"VERIFIED":game.steam.appId?"UNVERIFIED":"NOT MAPPED"}</b><small>{game.steam.appId?`App ${game.steam.appId}`:"Manual metadata valid"}</small></span><span role="cell"><b>{game.rotation.inRotation?`POSITION ${game.rotation.position}`:game.archived?"ARCHIVED":"LIBRARY ONLY"}</b></span><span role="cell"><time dateTime={game.updatedAt}>{new Date(game.updatedAt).toLocaleDateString("en-AU")}</time></span><span role="cell" className="gaming-table-actions"><button onClick={()=>setEditing(game)}><AdminIcon name="edit"/> Edit</button>{!game.archived&&(game.rotation.inRotation?<span className="gaming-in-state">IN ROTATION</span>:<button disabled={!canManage||Boolean(busy)} onClick={()=>void act({action:"add_to_rotation",gameId:game.id},game.id)}>Add to rotation</button>)}<button disabled={!canManage||Boolean(busy)} onClick={()=>void act({action:game.archived?"restore":"archive",gameId:game.id},game.id)}>{game.archived?"Restore":"Archive"}</button></span></div>)}{!games.length&&<State text="No games match this Library view."/>}</div>
    </section>
    {editing&&<GameEditor game={editing==="new"?null:editing} canManage={canManage} csrfToken={csrfToken} onClose={()=>setEditing(null)} onSaved={(next)=>{setPayload(next);setEditing(null);}}/>}
  </main>;
}

function GameEditor({game,canManage,csrfToken,onClose,onSaved}:{game:GamingGame|null;canManage:boolean;csrfToken:string;onClose:()=>void;onSaved:(payload:GamingPayload)=>void}){
  const initial:GamingDraft=game?{id:game.id,title:game.title,slug:game.slug||"",platform:game.platform,description:game.description,genre:game.genre,developer:game.developer||"",publisher:game.publisher||"",steamAppId:game.steam.appId||"",steamStoreUrl:game.steam.storeUrl||"",steamState:game.steam.state,provenance:game.steam.provenance as GamingDraft["provenance"],remoteArtworkUrl:game.artwork.source==="remote"?game.artwork.url||"":""}:blank;
  const [draft,setDraft]=useState<GamingDraft>(initial);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState(initial.remoteArtworkUrl||game?.artwork.url||"");const [savedGameId,setSavedGameId]=useState(game?.id||"");const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [savingStage,setSavingStage]=useState<"record"|"artwork"|"">("");const [lookup,setLookup]=useState(game?.steam.appId||game?.title||"");const [lookupState,setLookupState]=useState<"idle"|"searching"|"results"|"partial"|"empty"|"unavailable">("idle");const [results,setResults]=useState<SteamSearchResult[]>([]);const [matched,setMatched]=useState<SteamGame|null>(null);const dialog=useRef<HTMLDivElement>(null);
  useEffect(()=>{dialog.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key);},[onClose]);
  useEffect(()=>{if(!file){setPreview(draft.remoteArtworkUrl||game?.artwork.url||"");return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file,draft.remoteArtworkUrl,game?.artwork.url]);
  const set=<K extends keyof GamingDraft>(key:K,value:GamingDraft[K])=>setDraft(current=>{const manualOverride=Boolean(matched)&&key!=="provenance"&&key!=="steamState";return{...current,[key]:value,...(manualOverride?{provenance:"manual_override" as const}:{}),...(manualOverride&&(key==="steamAppId"||key==="steamStoreUrl")?{steamState:"manual_override" as const}:{})};});
  const applySteam=(steam:SteamGame,overwrite:boolean)=>{setMatched(steam);setDraft(current=>{const choose=(existing:string,incoming:string)=>overwrite||!existing.trim()?incoming:existing;const keepArtwork=Boolean(file)||Boolean(game?.artwork.url);return{...current,title:choose(current.title,steam.name),platform:current.platform||"PC via Steam",description:choose(current.description,steam.description),genre:choose(current.genre,steam.genre),developer:choose(current.developer,steam.developer),publisher:choose(current.publisher,steam.publisher),steamAppId:steam.appId,steamStoreUrl:steam.storeUrl,steamState:"verified",provenance:overwrite||!game?"steam_verified":current.provenance,remoteArtworkUrl:keepArtwork?current.remoteArtworkUrl:choose(current.remoteArtworkUrl,steam.artworkUrl||"")};});};
  const applySteamSearchResult=(result:SteamSearchResult)=>{setDraft(current=>{const choose=(existing:string,incoming:string)=>!existing.trim()?incoming:existing;const keepArtwork=Boolean(file)||Boolean(game?.artwork.url);return{...current,title:choose(current.title,result.name),platform:current.platform||"PC via Steam",steamAppId:result.appId,steamStoreUrl:result.storeUrl,steamState:"unverified",provenance:game?current.provenance:"manual",remoteArtworkUrl:keepArtwork?current.remoteArtworkUrl:choose(current.remoteArtworkUrl,result.artworkUrl||"")};});};
  const selectResult=async(result:SteamSearchResult)=>{applySteamSearchResult(result);try{setLookupState("searching");setError("");const response=await resolveSteamApp(result.appId);applySteam(response.result,!game);setLookupState("results");}catch{setLookupState("partial");}};
  const runLookup=async(event?:FormEvent)=>{event?.preventDefault();try{setLookupState("searching");setError("");setResults([]);const response=await searchSteam(lookup);if(response.mode==="app"){applySteam(response.result,!game);setResults([response.result]);setLookupState("results");return;}setResults(response.results);setLookupState(response.results.length?"results":"empty");}catch{setLookupState("unavailable");}};
  const refresh=async()=>{if(!draft.steamAppId)return;try{setLookupState("searching");setError("");const response=await resolveSteamApp(draft.steamAppId);applySteam(response.result,false);setLookupState("results");}catch{setLookupState("unavailable");}};
  const submit=async(event:FormEvent)=>{event.preventDefault();try{setSaving(true);setSavingStage("record");setError("");const currentId=savedGameId||draft.id||"";let payload=await mutateGaming(csrfToken,{action:currentId?"update":"create",game:{...draft,...(currentId?{id:currentId}:{})},inRotation:false});const id=currentId||payload.mutation?.gameId||payload.games.find(item=>item.title===draft.title)?.id||"";if(id&&!savedGameId){setSavedGameId(id);setDraft(current=>({...current,id}));}if(file&&id){setSavingStage("artwork");payload=await uploadGamingArtwork(csrfToken,id,file);}onSaved(payload);}catch(reason){setError(reason instanceof Error?reason.message:"The game could not be saved.");}finally{setSavingStage("");setSaving(false);}};
  return <div className="gaming-editor-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div ref={dialog} tabIndex={-1} className="gaming-editor" role="dialog" aria-modal="true" aria-labelledby="game-editor-title"><header><div><p className="eyebrow">GAME LIBRARY RECORD</p><h2 id="game-editor-title">{game?`Edit ${game.title}`:"Add game"}</h2><p>Steam assists the editor; manual curation remains authoritative.</p></div><button type="button" aria-label="Close game editor" onClick={onClose}><AdminIcon name="close"/></button></header><form onSubmit={event=>void submit(event)}><div className="gaming-editor__body">{error&&<div className="admin-alert" role="alert">{error}</div>}<fieldset disabled={!canManage||saving}>
    <section className="gaming-steam-lookup"><div className="gaming-steam-heading"><div><p className="eyebrow">STEAM LOOKUP</p><h3>{game?"Find / change Steam match":"Find on Steam"}</h3><p>Search a title, or paste a numeric App ID or canonical Steam Store URL.</p></div><a href={steamSearchUrl(draft.title||lookup)} target="_blank" rel="noreferrer">External Search Steam <AdminIcon name="external"/></a></div><div className="gaming-steam-search"><label><span className="sr-only">Search Steam games</span><input value={lookup} onChange={event=>setLookup(event.target.value)} placeholder="Search Steam games, App ID, or Store URL" onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void runLookup();}}}/></label><button type="button" onClick={()=>void runLookup()} disabled={lookupState==="searching"}>{lookupState==="searching"?"Searching…":"Search"}</button>{game&&draft.steamAppId&&<button type="button" className="secondary-button" onClick={()=>void refresh()} disabled={lookupState==="searching"}>Refresh from Steam</button>}</div>
      {lookupState==="searching"&&<div className="gaming-lookup-state" role="status">Searching Steam Store…</div>}{lookupState==="empty"&&<div className="gaming-lookup-state" role="status">No Steam matches. Manual entry remains available.</div>}{lookupState==="partial"&&<div className="gaming-lookup-state is-warn" role="status">Steam listing selected. Extended metadata could not be loaded; review the fields before saving.</div>}{lookupState==="unavailable"&&<div className="gaming-lookup-state is-warn" role="status">Steam is temporarily unavailable. You can still complete and save every field manually.</div>}
      {results.length>0&&<div className="gaming-steam-results" role="list" aria-label="Steam search results">{results.map(result=><article role="listitem" key={result.appId}>{result.artworkUrl?<img src={result.artworkUrl} alt=""/>:<span className="gaming-result-fallback"><AdminIcon name="gaming"/></span>}<div><strong>{result.name}</strong><small>Steam App {result.appId}{result.platforms.length?` · ${result.platforms.join(" / ")}`:""}</small></div><button type="button" onClick={()=>void selectResult(result)} disabled={lookupState==="searching"}>Use this listing</button></article>)}</div>}
      {matched&&<div className="gaming-steam-match" role="status"><div><span>STEAM MATCH</span><strong>{matched.name}</strong><small>App {matched.appId} · Metadata loaded</small></div>{game&&<button type="button" className="secondary-button" onClick={()=>applySteam(matched,true)}>Apply Steam values to curated text</button>}</div>}
    </section>
    <section><h3>Public display</h3><div className="gaming-editor-grid"><Field label="Display title"><input required maxLength={120} value={draft.title} onChange={e=>set("title",e.target.value)}/></Field><Field label="Platform label"><input maxLength={80} value={draft.platform} onChange={e=>set("platform",e.target.value)}/></Field><Field label="Genre / category"><input maxLength={120} value={draft.genre} onChange={e=>set("genre",e.target.value)}/></Field><Field label="Canonical slug"><input maxLength={100} value={draft.slug} onChange={e=>set("slug",e.target.value)}/></Field><Field label="Short description" wide><textarea rows={3} maxLength={600} value={draft.description} onChange={e=>set("description",e.target.value)}/></Field><Field label="Developer"><input maxLength={120} value={draft.developer} onChange={e=>set("developer",e.target.value)}/></Field><Field label="Publisher"><input maxLength={120} value={draft.publisher} onChange={e=>set("publisher",e.target.value)}/></Field></div></section>
    <section><h3>Artwork</h3><div className="gaming-artwork-editor"><div className="gaming-artwork-preview">{preview?<img src={preview} alt={`${draft.title||"Selected game"} artwork preview`}/>:<span><AdminIcon name="gaming" size={32}/> Public fallback art</span>}</div><div><Field label="Upload replacement"><input type="file" accept="image/png,image/jpeg,image/webp,image/bmp" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><Field label="Or public HTTPS image URL"><input type="url" value={draft.remoteArtworkUrl} onChange={e=>set("remoteArtworkUrl",e.target.value)} placeholder="https://…"/></Field>{game?.artwork.source==="uploaded"&&<p className="gaming-artwork-precedence">Uploaded artwork is retained when Steam metadata is applied.</p>}{game?.artwork.url&&<button type="button" className="secondary-button" onClick={async()=>{try{setSaving(true);onSaved(await mutateGaming(csrfToken,{action:"remove_artwork",gameId:game.id}));}catch(reason){setError(reason instanceof Error?reason.message:"Artwork could not be removed.");}finally{setSaving(false);}}}>Remove artwork · use fallback</button>}</div></div></section>
    <section><div className="gaming-steam-heading"><div><h3>Steam mapping</h3><p>{draft.steamState==="verified"?"Verified match selected; all fields remain editable.":"Steam mapping is optional; unknown remains valid."}</p></div></div><div className="gaming-editor-grid"><Field label="Steam App ID"><input inputMode="numeric" maxLength={12} value={draft.steamAppId} onChange={e=>set("steamAppId",e.target.value)}/></Field><Field label="Canonical Steam Store URL"><input type="url" value={draft.steamStoreUrl} onChange={e=>set("steamStoreUrl",e.target.value)}/></Field><Field label="Mapping state"><select value={draft.steamState} onChange={e=>set("steamState",e.target.value as GamingDraft["steamState"])}><option value="unverified">Unverified / manual</option><option value="verified">Verified exact match</option><option value="manual_override">Manual override</option></select></Field><Field label="Metadata provenance"><select value={draft.provenance} onChange={e=>set("provenance",e.target.value as GamingDraft["provenance"])}><option value="manual">Manual</option><option value="steam_verified">Steam verified</option><option value="manual_override">Manual override</option></select></Field></div></section>
  </fieldset></div><footer><span>{canManage?"The game record and uploaded artwork must both finish before save completes. Changes are audited.":"Read-only capability"}</span><div><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" disabled={!canManage||saving}>{savingStage==="artwork"?"Uploading artwork…":saving?"Saving…":"Save game"}</button></div></footer></form></div></div>;
}

function Field({label,wide=false,children}:{label:string;wide?:boolean;children:ReactNode}){return <label className={wide?"is-wide":""}><span>{label}</span>{children}</label>;}function Cover({game}:{game:GamingGame}){return <div className="gaming-cover">{game.artwork.url?<img src={game.artwork.url} alt={`${game.title} cover`}/>:<span aria-label={`${game.title} fallback artwork`}><AdminIcon name="gaming"/></span>}</div>;}function Quality({game}:{game:GamingGame}){const values=[game.artwork.url?"ART READY":"MISSING ARTWORK",game.steam.state==="verified"?"STEAM VERIFIED":"STEAM UNVERIFIED",game.description?"COPY READY":"MISSING DESCRIPTION"];return <div className="gaming-quality">{values.map(value=><small key={value} className={value.startsWith("MISSING")||value.endsWith("UNVERIFIED")?"is-warn":""}>{value}</small>)}</div>;}function State({text}:{text:string}){return <div className="gaming-state"><AdminIcon name="signal"/><p>{text}</p></div>;}
