import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { Link, useOutletContext } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import { adminApi } from "../auth/client";
import { AdminIcon } from "../components/AdminIcon";
import type { AdminShellOutletContext } from "../components/AdminShell";
import { getCustomerEmailsControlPlane, getFulfillmentShipping, getMerchandisingProducts, getPaymentsControlPlane, type CommerceOverviewPayload, type CustomerEmailsPayload, type FulfillmentShippingPayload, type MerchandisingProduct, type PaymentsControlPlanePayload } from "../commerce/client";
import { getCommerceOverview } from "../commerce/client";
import { getGoatsOverview, getGoatSettings, type GoatAdminSummary } from "../goats/client";
import { readBannerSettings, type BannerSettings } from "../banner/client";
import { getWheelLibrary, getWheelSettings, type AdminWheel } from "../wheels/client";

type AdminStatus = { ok: true; checkedAt: string; configuration: { d1Configured: boolean; turnstileConfigured: boolean; resendConfigured: boolean; oauthProviders: string[] }; accounts: { total: number; regular: number; admins: number; disabled: number; pending: number } };
type LoadState<T> = { value: T | null; error: string };
const empty = <T,>(): LoadState<T> => ({ value: null, error: "" });

export function MediaOperationsPage() {
  const { account } = useAuth();
  const { startLoading } = useOutletContext<AdminShellOutletContext>();
  const [products, setProducts] = useState<LoadState<MerchandisingProduct[]>>(empty);
  const [goats, setGoats] = useState<LoadState<GoatAdminSummary[]>>(empty);
  const [wheels, setWheels] = useState<LoadState<AdminWheel[]>>(empty);
  const [query, setQuery] = useState("");
  const load = useCallback(async () => {
    const stop = startLoading("Loading media operations");
    const [catalogue, community, wheelLibrary] = await Promise.allSettled([getMerchandisingProducts(), getGoatsOverview(), getWheelLibrary()]);
    setProducts(settled(catalogue, (value) => value.products));
    setGoats(settled(community, (value) => value.recent));
    setWheels(settled(wheelLibrary, (value) => value.items));
    stop();
  }, [startLoading]);
  useEffect(() => { void load(); }, [load]);
  const assets = useMemo(() => {
    const seen = new Set<string>();
    return (products.value || []).flatMap((product) => [product.primaryImageUrl, ...product.additionalImages].filter((url): url is string => Boolean(url)).map((url, index) => ({ url, product, usage: index === 0 ? "Primary catalogue image" : "Catalogue gallery" }))).filter((asset) => !seen.has(asset.url) && Boolean(seen.add(asset.url))).filter((asset) => `${asset.product.title} ${asset.product.slug} ${asset.url}`.toLowerCase().includes(query.trim().toLowerCase()));
  }, [products.value, query]);
  const goatMediaCount = (goats.value || []).reduce((sum, item) => sum + item.mediaCount, 0);
  return <OperationsPage icon="media" eyebrow="Asset operations" title="Media library" summary="A read-only inventory of safe media references. Upload, replacement, and deletion remain inside the authoritative product, GOATS, Wheels, and account editors.">
    <MetricRail items={[{ label: "Catalogue assets", value: products.value ? String(assets.length) : "—" }, { label: "Recent GOATS media", value: goats.value ? String(goatMediaCount) : "—" }, { label: "Wheels", value: wheels.value ? String(wheels.value.length) : "—" }, { label: "Current avatar", value: account?.avatarUrl ? "Configured" : "Initials" }]} />
    <PartialErrors states={[products, goats, wheels]} onRetry={load} />
    <section className="operations-panel operations-panel--wide"><header><div><p className="eyebrow">Public-safe catalogue references</p><h2>Commerce imagery</h2><p>Images are deduplicated by their stored public URL. Product editing remains the only write authority.</p></div><Link className="secondary-button" to="/products">Manage products</Link></header><label className="operations-search"><span>Search assets</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Product, slug, or URL" /></label>{products.value ? assets.length ? <div className="media-inventory" role="list">{assets.slice(0, 60).map((asset) => <article key={asset.url} role="listitem"><img src={asset.url} alt="" loading="lazy" referrerPolicy="no-referrer" /><div><span>{asset.usage}</span><strong>{asset.product.title}</strong><small>/{asset.product.slug} · {human(asset.product.sourceProvider)}</small></div><a className="text-button" href={asset.url} target="_blank" rel="noreferrer">Open image</a></article>)}</div> : <EmptyState title={query ? "No matching catalogue assets" : "No catalogue imagery"} detail={query ? "Change the search term to inspect another safe reference." : "The product authority returned no stored image URLs."} /> : <LoadingState label="Loading catalogue imagery…" />}</section>
    <div className="operations-grid operations-grid--split"><section className="operations-panel"><header><div><p className="eyebrow">Private originals remain protected</p><h2>GOATS media</h2><p>The aggregate shows only Admin-proxied recent previews and counts; no R2 object key is exposed.</p></div><Link className="secondary-button" to="/goats">Open moderation</Link></header>{goats.value ? goats.value.length ? <div className="compact-asset-list">{goats.value.slice(0, 8).map((item) => <Link key={item.id} to={`/goats/${item.id}`}>{item.mainMediaUrl ? <img src={item.mainMediaUrl} alt="" loading="lazy" /> : <span><AdminIcon name="media" /></span>}<div><strong>{item.displayName}</strong><small>{item.mediaCount} asset{item.mediaCount === 1 ? "" : "s"} · {human(item.status)}</small></div></Link>)}</div> : <EmptyState title="No recent GOATS assets" detail="Media will appear through the existing moderated submission workflow." /> : <LoadingState label="Loading GOATS media…" />}</section>
      <section className="operations-panel"><header><div><p className="eyebrow">Owner-scoped editing</p><h2>Wheels and profiles</h2><p>Wheel images stay attached to their wheel lifecycle. Avatar writes stay attached to the signed account profile route.</p></div></header><AuthorityLinks items={[{ to: "/wheels", title: `${wheels.value?.length ?? "—"} Wheels`, detail: "Open a wheel to inspect or manage its active background, centre, and segment assets." }, { to: "/access", title: "Account avatars", detail: "The current user can update their own avatar through the existing protected profile control." }]} /></section></div>
  </OperationsPage>;
}

export function MembershipOperationsPage() {
  const { startLoading } = useOutletContext<AdminShellOutletContext>();
  const [status, setStatus] = useState<LoadState<AdminStatus>>(empty);
  const [payments, setPayments] = useState<LoadState<PaymentsControlPlanePayload>>(empty);
  const load = useCallback(async () => { const stop = startLoading("Auditing membership authority"); const [accounts, payment] = await Promise.allSettled([adminApi<AdminStatus>("/api/admin/status"), getPaymentsControlPlane()]); setStatus(settled(accounts)); setPayments(settled(payment)); stop(); }, [startLoading]);
  useEffect(() => { void load(); }, [load]);
  return <OperationsPage icon="vip" eyebrow="Capability audit" title="VIP / Membership" summary="The site has a real account authority and a public VIP proposition, but no persisted membership tier, entitlement, expiry, renewal, or subscription-billing authority yet.">
    <MetricRail items={[{ label: "All accounts", value: status.value ? String(status.value.accounts.total) : "—" }, { label: "Regular accounts", value: status.value ? String(status.value.accounts.regular) : "—", note: "Not a membership count" }, { label: "PayPal membership", value: payments.value?.paypal.membershipEnabled ? "Enabled" : "Disabled" }, { label: "Authoritative tiers", value: "Not implemented" }]} />
    <PartialErrors states={[status, payments]} onRetry={load} />
    <div className="operations-grid operations-grid--split"><section className="operations-panel"><header><div><p className="eyebrow">Real identity authority</p><h2>Accounts, not subscribers</h2><p>These counts describe authentication accounts only. They must not be presented as VIPs, paid members, MRR, churn, or renewals.</p></div><Link className="secondary-button" to="/access">Open Users / Access</Link></header>{status.value ? <DefinitionGrid items={[{ term: "Regular accounts", value: String(status.value.accounts.regular) }, { term: "Admin accounts", value: String(status.value.accounts.admins) }, { term: "Pending verification", value: String(status.value.accounts.pending) }, { term: "Disabled accounts", value: String(status.value.accounts.disabled) }]} /> : <LoadingState label="Loading account posture…" />}</section>
      <section className="operations-panel"><header><div><p className="eyebrow">Payment architecture</p><h2>Paid membership is deferred</h2><p>PayPal contains an explicit membership gate, but it is disabled and no recurring product or entitlement reducer exists.</p></div><Link className="secondary-button" to="/commerce/payments">Open payments</Link></header><CapabilityList items={[{ label: "One-time donations", state: payments.value?.paypal.donationsEnabled ? "configured" : "disabled", detail: "A donation is not treated as membership." }, { label: "Recurring billing", state: "deferred", detail: "No subscription agreement, renewal, or cancellation workflow." }, { label: "Tier entitlements", state: "deferred", detail: "No authoritative tier-to-capability mapping." }, { label: "Manual grants", state: "deferred", detail: "No audited membership grant or expiry model." }]} /></section></div>
  </OperationsPage>;
}

export function IntegrationsOperationsPage() {
  const { config } = useAuth();
  const { startLoading } = useOutletContext<AdminShellOutletContext>();
  const [overview, setOverview] = useState<LoadState<CommerceOverviewPayload>>(empty); const [payments, setPayments] = useState<LoadState<PaymentsControlPlanePayload>>(empty); const [fulfillment, setFulfillment] = useState<LoadState<FulfillmentShippingPayload>>(empty); const [email, setEmail] = useState<LoadState<CustomerEmailsPayload>>(empty); const [status, setStatus] = useState<LoadState<AdminStatus>>(empty);
  const load = useCallback(async () => { const stop = startLoading("Loading sanitized integration posture"); const values = await Promise.allSettled([getCommerceOverview(), getPaymentsControlPlane(), getFulfillmentShipping(), getCustomerEmailsControlPlane(), adminApi<AdminStatus>("/api/admin/status")]); setOverview(settled(values[0])); setPayments(settled(values[1])); setFulfillment(settled(values[2])); setEmail(settled(values[3])); setStatus(settled(values[4])); stop(); }, [startLoading]);
  useEffect(() => { void load(); }, [load]);
  const providers = overview.value?.providers || [];
  return <OperationsPage icon="integrations" eyebrow="Credential-safe directory" title="Integrations" summary="Sanitized configuration and activation posture from existing server authorities. Configured never implies connected or healthy, and this page performs no provider verification call.">
    <MetricRail items={[{ label: "Commerce providers", value: overview.value ? String(providers.length) : "—" }, { label: "OAuth enabled", value: config ? String(config.oauthProviderStates.filter((item) => item.status === "enabled").length) : "—" }, { label: "Email provider", value: email.value?.provider.configured ? "Configured" : "Not configured" }, { label: "External polling", value: "None" }]} />
    <PartialErrors states={[overview, payments, fulfillment, email, status]} onRetry={load} />
    <section className="operations-panel operations-panel--wide"><header><div><p className="eyebrow">Commerce and delivery</p><h2>Provider directory</h2><p>Provider credentials and technical identifiers remain server-only or masked by their owning control planes.</p></div></header><div className="integration-directory">{providers.map((provider) => <IntegrationCard key={provider.provider} title={provider.label} state={provider.status} purpose={providerPurpose(provider.provider)} facts={[{ term: "Environment", value: human(provider.environment) }, { term: "Credentials", value: provider.apiConfigured || provider.provider === "paypal" && payments.value?.paypal.credentialConfigured ? "Configured" : "Not configured" }, { term: "Enabled", value: provider.checkoutEnabled || provider.livePaymentsEnabled ? "Yes" : "No" }, { term: "Last internal evidence", value: formatDate(provider.lastSynchronizedAt || null) }]} to={provider.provider === "printful" ? "/commerce/fulfillment" : "/commerce/payments"} />)}{email.value ? <IntegrationCard title="Resend" state={email.value.provider.configured ? "configured" : "not_configured"} purpose="Transactional customer email delivery" facts={[{ term: "Credential", value: email.value.provider.credentialConfigured ? "Configured" : "Not configured" }, { term: "Sender", value: email.value.provider.senderConfigured ? "Configured" : "Not configured" }, { term: "External verification", value: human(email.value.provider.externalVerification) }, { term: "Customer sends", value: email.value.safety.customerSendsEnabled ? "Enabled" : "Disabled" }]} to="/commerce/emails" /> : null}</div></section>
    <div className="operations-grid operations-grid--split"><section className="operations-panel"><header><div><p className="eyebrow">Authentication</p><h2>Identity providers</h2><p>Enabled means runtime configuration is present; no OAuth login is attempted from this page.</p></div><Link className="secondary-button" to="/access">Open access</Link></header><CapabilityList items={(config?.oauthProviderStates || []).map((provider) => ({ label: provider.label, state: provider.status, detail: provider.message || "Server-side OAuth callback architecture is present." }))} /></section><section className="operations-panel"><header><div><p className="eyebrow">Platform services</p><h2>Internal runtime posture</h2><p>Only binding presence already projected by authenticated APIs is reported.</p></div></header><CapabilityList items={[{ label: "Account D1", state: status.value?.configuration.d1Configured ? "configured" : "unavailable", detail: "Shared authentication account authority." }, { label: "Commerce D1", state: overview.value?.databaseConfigured ? "configured" : "unavailable", detail: "Admin-owned commerce persistence." }, { label: "Profile and media R2", state: "configured", detail: "Existing bound storage; this directory does not perform a bucket health probe." }, { label: "Turnstile", state: status.value?.configuration.turnstileConfigured ? "configured" : "not_configured", detail: "Human-verification credential presence only." }, { label: "Printful fulfillment", state: fulfillment.value?.provider.configured ? "configured" : "disabled", detail: fulfillment.value?.provider.configurationEvidence || "No authoritative configuration evidence loaded." }]} /></section></div>
  </OperationsPage>;
}

export function SettingsOperationsPage() {
  const { config } = useAuth(); const { startLoading } = useOutletContext<AdminShellOutletContext>();
  const [banner, setBanner] = useState<LoadState<BannerSettings>>(empty); const [goats, setGoats] = useState<LoadState<Awaited<ReturnType<typeof getGoatSettings>>>>(empty); const [wheels, setWheels] = useState<LoadState<Awaited<ReturnType<typeof getWheelSettings>>>>(empty); const [status, setStatus] = useState<LoadState<AdminStatus>>(empty);
  const load = useCallback(async () => { const stop = startLoading("Loading configuration authorities"); const values = await Promise.allSettled([readBannerSettings(), getGoatSettings(), getWheelSettings(), adminApi<AdminStatus>("/api/admin/status")]); setBanner(settled(values[0])); setGoats(settled(values[1])); setWheels(settled(values[2])); setStatus(settled(values[3])); stop(); }, [startLoading]); useEffect(() => { void load(); }, [load]);
  return <OperationsPage icon="settings" eyebrow="Authority map" title="Settings" summary="Global posture and direct routes to the existing configuration owners. Each authority keeps its own validation, CSRF, revision, audit, and Master Admin boundary.">
    <MetricRail items={[{ label: "Environment", value: config?.environment ? human(config.environment) : "—" }, { label: "Site banner", value: banner.value ? banner.value.config.normal.enabled ? "Enabled" : "Disabled" : "—" }, { label: "GOATS defaults", value: goats.value ? "Configured" : "—" }, { label: "Wheels revision", value: wheels.value ? String(wheels.value.revision) : "—" }]} />
    <PartialErrors states={[banner, goats, wheels, status]} onRetry={load} />
    <section className="operations-panel operations-panel--wide"><header><div><p className="eyebrow">One owner per setting</p><h2>Configuration directory</h2><p>Open the authoritative workspace to make a change; this page does not duplicate or simulate saves.</p></div></header><div className="settings-authority-grid"><AuthorityCard icon="content" title="Site / announcements" state={banner.value ? banner.value.config.normal.enabled ? "Enabled" : "Configured / disabled" : "Unavailable"} detail="Normal promotion and automatic Live Now presentation." to="/content" /><AuthorityCard icon="goats" title="Community defaults" state={goats.value ? `${human(goats.value.comments)} comments · ${human(goats.value.reactions)} reactions` : "Unavailable"} detail="Global GOATS comment and reaction inheritance." to="/goats/settings" /><AuthorityCard icon="wheels" title="Wheels policy" state={wheels.value ? `Revision ${wheels.value.revision}` : "Unavailable"} detail="Theme, participant bounds, creator limits, and official cooldown." to="/wheels" /><AuthorityCard icon="commerce" title="Commerce operations" state="Fail-closed gates" detail="Business, payment, tax, email, fulfillment, and launch settings." to="/commerce" /><AuthorityCard icon="users" title="Account security" state={status.value?.configuration.turnstileConfigured ? "Turnstile configured" : "Turnstile unavailable"} detail="Roles, account state, sessions, and environment-master locks." to="/access" /><AuthorityCard icon="integrations" title="Provider configuration" state="Sanitized status" detail="Credential presence, enablement, and internal evidence." to="/integrations" /></div></section>
    <section className="operations-panel operations-panel--wide"><header><div><p className="eyebrow">Deferred global capabilities</p><h2>Not yet configurable</h2><p>These controls stay visibly disabled until a real persistence and authorization contract exists.</p></div></header><div className="deferred-settings"><label><span>Organization-wide notification defaults</span><select disabled><option>Deferred</option></select><small>No global communication preference authority.</small></label><label><span>Site-wide maintenance mode</span><button type="button" className="secondary-button" disabled>Not yet configurable</button><small>No audited global maintenance switch.</small></label><label><span>Cross-feature moderation policy</span><select disabled><option>Deferred</option></select><small>GOATS-specific policy remains in GOATS.</small></label></div></section>
  </OperationsPage>;
}

function OperationsPage({ icon, eyebrow, title, summary, children }: { icon: "media" | "vip" | "integrations" | "settings"; eyebrow: string; title: string; summary: string; children: ReactNode }) { return <div className="operations-page"><section className="operations-heading"><span><AdminIcon name={icon} size={27} /></span><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{summary}</p></div><b>Authenticated Admin view</b></section>{children}</div>; }
function MetricRail({ items }: { items: Array<{ label: string; value: string; note?: string }> }) { return <section className="operations-metrics" aria-label="Operational summary">{items.map((item) => <article key={item.label}><span>{item.label}</span><strong>{item.value}</strong>{item.note ? <small>{item.note}</small> : null}</article>)}</section>; }
function PartialErrors({ states, onRetry }: { states: Array<LoadState<unknown>>; onRetry: () => void | Promise<void> }) { const errors = states.map((state) => state.error).filter(Boolean); return errors.length ? <div className="admin-alert" role="alert"><div><strong>Partial operational snapshot</strong><p>{errors.join(" ")}</p></div><button type="button" className="secondary-button" onClick={() => void onRetry()}>Retry reads</button></div> : null; }
function LoadingState({ label }: { label: string }) { return <div className="operations-state" role="status">{label}</div>; }
function EmptyState({ title, detail }: { title: string; detail: string }) { return <div className="operations-state"><strong>{title}</strong><span>{detail}</span></div>; }
function DefinitionGrid({ items }: { items: Array<{ term: string; value: string }> }) { return <dl className="operations-definitions">{items.map((item) => <div key={item.term}><dt>{item.term}</dt><dd>{item.value}</dd></div>)}</dl>; }
function CapabilityList({ items }: { items: Array<{ label: string; state: string; detail: string }> }) { return <div className="capability-list">{items.map((item) => <article key={item.label}><span className={`capability-state is-${tone(item.state)}`}>{human(item.state)}</span><div><strong>{item.label}</strong><p>{item.detail}</p></div></article>)}</div>; }
function AuthorityLinks({ items }: { items: Array<{ to: string; title: string; detail: string }> }) { return <div className="authority-links">{items.map((item) => <Link key={item.to} to={item.to}><div><strong>{item.title}</strong><p>{item.detail}</p></div><AdminIcon name="arrow" size={15} /></Link>)}</div>; }
function IntegrationCard({ title, state, purpose, facts, to }: { title: string; state: string; purpose: string; facts: Array<{ term: string; value: string }>; to: string }) { return <article className="integration-card"><header><div><strong>{title}</strong><p>{purpose}</p></div><span className={`capability-state is-${tone(state)}`}>{human(state)}</span></header><DefinitionGrid items={facts} /><Link className="text-button" to={to}>Open authority <AdminIcon name="arrow" size={13} /></Link></article>; }
function AuthorityCard({ icon, title, state, detail, to }: { icon: Parameters<typeof AdminIcon>[0]["name"]; title: string; state: string; detail: string; to: string }) { return <Link className="settings-authority" to={to}><span><AdminIcon name={icon} size={20} /></span><div><strong>{title}</strong><b>{state}</b><p>{detail}</p></div><AdminIcon name="arrow" size={14} /></Link>; }
function settled<T, U = T>(result: PromiseSettledResult<T>, select?: (value: T) => U): LoadState<U> { return result.status === "fulfilled" ? { value: select ? select(result.value) : result.value as unknown as U, error: "" } : { value: null, error: message(result.reason) }; }
function message(reason: unknown) { return reason instanceof Error ? reason.message : "An authoritative read is unavailable."; }
function human(value: string) { return String(value || "unknown").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function tone(value: string) { const state = value.toLowerCase(); if (/enabled|connected|verified|ready|configured/.test(state) && !/not_|unverified|disabled/.test(state)) return "ready"; if (/disabled|deferred|unavailable|not configured|not_configured/.test(state)) return "muted"; return "attention"; }
function formatDate(value: string | null) { if (!value) return "No evidence"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Unavailable" : new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function providerPurpose(provider: string) { return ({ paypal: "Preferred direct merchant checkout and donations", stripe: "Retained payment option and historical TEST evidence", printful: "Catalogue and fulfillment provider", printify: "Unavailable alternate fulfillment provider", wix: "Legacy commerce source" } as Record<string, string>)[provider] || "Existing server-side integration"; }
