import { useCallback, useEffect, useState } from "react";
import { Link, useOutletContext } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import type { AdminShellOutletContext } from "../components/AdminShell";
import { BotHeartbeatCard } from "../components/BotHeartbeatCard";
import { searchAccounts, type AccountSummary } from "../wheels/client";
import { getAdminPolls, getAutomations, getPollAccess, mutatePollGrant, mutatePollLifecycle, mutatePollVisibility, saveAutomations, type AdminPoll, type AutomationPayload } from "../polls/admin-client";
import "../styles/polls-admin.css";

const FILTERS = ["all", "open", "draft", "closed", "archived"] as const;

export function PollManagementPage() {
  const { csrfToken, hasCapability } = useAuth(); const canManage = hasCapability("polls.manage"); const { startLoading } = useOutletContext<AdminShellOutletContext>();
  const [state, setState] = useState<(typeof FILTERS)[number]>("all"); const [items, setItems] = useState<AdminPoll[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(() => { const stop = startLoading("Loading Poll authority"); return getAdminPolls(state).then((payload) => { setItems(payload.items); setError(""); }).catch((reason) => setError(message(reason))).finally(stop); }, [startLoading, state]);
  useEffect(() => { void load(); }, [load]);
  const action = async (poll: AdminPoll, value: "open" | "close" | "archive" | "restore") => { if (!csrfToken || !canManage) return; setBusy(poll.id); setError(""); try { await mutatePollLifecycle(csrfToken, poll, value); await load(); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } };
  const visibility = async (poll: AdminPoll, isPublic: boolean) => { if (!csrfToken || !canManage) return; setBusy(poll.id); setError(""); try { await mutatePollVisibility(csrfToken, poll, isPublic); await load(); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } };
  return <div className="poll-admin"><PageHeading eyebrow="POLL AUTHORITY" title="Poll management" copy="Inspect lifecycle, public listing, owners, voting policy, Rumble leases, and authoritative aggregate totals without exposing raw vote rows." actions={<><Link className="secondary-button" to="/polls/access">Creator access</Link><a className="secondary-button" href="https://thirdrailify.com/polls" target="_blank" rel="noreferrer">Open Public Polls ↗</a></>} />
    <nav className="poll-admin__filters" aria-label="Poll state filters">{FILTERS.map((value) => <button key={value} type="button" className={state === value ? "is-active" : ""} onClick={() => setState(value)}>{value}</button>)}</nav>
    {error ? <Alert>{error}</Alert> : null}<section className="poll-metrics"><Metric label="Loaded records" value={items.length} /><Metric label="Open" value={items.filter((item) => item.state === "open").length} /><Metric label="Publicly listed" value={items.filter((item) => item.public && new Set(["open", "closed"]).has(item.state)).length} /><Metric label="Votes" value={items.reduce((sum, item) => sum + item.totalVotes, 0)} /></section>
    <section className="poll-panel"><header><div><p className="eyebrow">SERVER AGGREGATES</p><h2>{items.length} Poll{items.length === 1 ? "" : "s"}</h2></div><button className="secondary-button" type="button" onClick={() => void load()}>Refresh</button></header>{items.length ? <div className="poll-table-wrap"><table><thead><tr><th>Poll</th><th>Owner</th><th>Policy</th><th>Rumble</th><th>Votes</th><th>Lifecycle</th><th>Listing</th><th>Controls</th></tr></thead><tbody>{items.map((poll) => <tr key={poll.id}><td><strong>{poll.title}</strong><span>/{poll.slug} · r{poll.revision}</span></td><td><strong>{poll.owner.displayName}</strong><span>{poll.owner.id}</span></td><td>{poll.webVotingMode === "anyone" ? "Anyone" : "Signed-in"}</td><td>{poll.rumbleEnabled ? <><b>Enabled</b><span>{poll.rumbleSourceScope || "Source pending"}</span></> : "Web only"}</td><td><strong>{poll.totalVotes}</strong><span>{poll.options.length} options</span></td><td><Status value={poll.state} /></td><td><Status value={poll.public ? "Listed" : "Hidden"} /></td><td><div className="poll-actions">{new Set(["draft", "closed"]).has(poll.state) ? <button disabled={!canManage || busy === poll.id} onClick={() => void action(poll, "open")}>Open</button> : null}{poll.state === "open" ? <button disabled={!canManage || busy === poll.id} onClick={() => void action(poll, "close")}>Close</button> : null}{poll.state === "closed" ? <button disabled={!canManage || busy === poll.id} onClick={() => void visibility(poll, !poll.public)}>{poll.public ? "Hide from gallery" : "Show in gallery"}</button> : null}{new Set(["draft", "closed"]).has(poll.state) ? <button disabled={!canManage || busy === poll.id} onClick={() => void action(poll, "archive")}>Archive</button> : null}{poll.state === "archived" ? <button disabled={!canManage || busy === poll.id} onClick={() => void action(poll, "restore")}>Restore draft</button> : null}{poll.public && new Set(["open", "closed"]).has(poll.state) ? <a href={`https://thirdrailify.com/polls/${poll.slug}`} target="_blank" rel="noreferrer">Inspect ↗</a> : null}</div></td></tr>)}</tbody></table></div> : <Empty>No Polls match this state. Zero Polls is an authoritative empty state.</Empty>}</section>
  </div>;
}

export function PollCreatorAccessPage() {
  const { csrfToken, hasCapability } = useAuth(); const canManage = hasCapability("polls.manage"); const { startLoading } = useOutletContext<AdminShellOutletContext>(); const [accounts, setAccounts] = useState<AccountSummary[]>([]); const [grants, setGrants] = useState<Awaited<ReturnType<typeof getPollAccess>>["grants"]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(() => { const stop = startLoading("Loading Poll creator access"); return Promise.all([getPollAccess(), searchAccounts(query)]).then(([access, found]) => { setGrants(access.grants); setAccounts(found.accounts); setError(""); }).catch((reason) => setError(message(reason))).finally(stop); }, [query, startLoading]); useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const mutate = async (accountId: string, approved: boolean) => { if (!csrfToken || !canManage) return; setBusy(accountId); try { setGrants((await mutatePollGrant(csrfToken, accountId, approved ? "revoke" : "approve")).grants); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } };
  return <div className="poll-admin"><PageHeading eyebrow="LEAST PRIVILEGE" title="Poll creator access" copy="Regular accounts are unapproved by default. Grants allow creation and management of owned Polls only; bot-global controls remain Admin-only." actions={<Link className="secondary-button" to="/polls">Back to Polls</Link>} />{error ? <Alert>{error}</Alert> : null}<section className="poll-panel"><header><form className="poll-search" onSubmit={(event) => { event.preventDefault(); void load(); }}><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search accounts" /><button>Search</button></form></header><div className="poll-account-list">{accounts.map((account) => { const grant = grants.find((item) => item.account_id === account.id); const approved = Boolean(grant?.active && grant?.may_create_polls); const implicit = new Set(["full", "master"]).has(account.adminLevel || ""); return <article key={account.id}><div><strong>{account.displayName}</strong><span>{account.email || "No email"}</span></div><Status value={implicit ? `${account.adminLevel} Admin · implicit` : approved ? "Approved creator" : "Not approved"} />{!implicit ? <button type="button" disabled={!canManage || busy === account.id} onClick={() => void mutate(account.id, approved)}>{approved ? "Revoke" : "Approve"}</button> : null}</article>; })}</div></section></div>;
}

export function AutomationsPage() {
  const { csrfToken, hasCapability } = useAuth(); const canManage = hasCapability("automations.manage"); const { startLoading } = useOutletContext<AdminShellOutletContext>(); const [payload, setPayload] = useState<AutomationPayload | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(() => { const stop = startLoading("Loading bot control plane"); return getAutomations().then((value) => { setPayload(value); setError(""); }).catch((reason) => setError(message(reason))).finally(stop); }, [startLoading]); useEffect(() => { void load(); const timer = window.setInterval(() => { if (!document.hidden) void load(); }, 15000); return () => window.clearInterval(timer); }, [load]);
  const runtime = payload?.runtime; const desired = payload?.config.desiredRevision || 0; const applied = Number(runtime?.appliedRevision || 0); const pending = desired !== applied || new Set(["local_pending", "conflict", "conflict_resolved_remote"]).has(String(runtime?.configSyncState || ""));
  const update = (group: "discord" | "rumble", key: string, value: unknown) => setPayload((current) => current ? { ...current, config: { ...current.config, desiredState: { ...current.config.desiredState, [group]: { ...(current.config.desiredState[group] || {}), [key]: value } } } } : current);
  const save = async () => { if (!payload || !csrfToken || !canManage) return; setBusy(true); try { setPayload(await saveAutomations(csrfToken, payload)); } catch (reason) { setError(message(reason)); } finally { setBusy(false); } };
  return <div className="poll-admin automations"><PageHeading eyebrow="BOT CONTROL PLANE" title="Automations" copy="Versioned desired state in Admin D1; signed bot pull and heartbeat; one shared Rumble client in the Discord runtime." actions={<button className="secondary-button" type="button" onClick={() => void load()}>Refresh status</button>} />{error ? <Alert>{error}</Alert> : null}<BotHeartbeatCard payload={payload} error={error || undefined} loading={!payload && !error} />{payload ? <>
    <div className="automation-grid"><section className="poll-panel"><header><div><p className="eyebrow">DESIRED STATE · REVISION {desired}</p><h2>Discord configuration</h2></div><Status value={pending ? "Pending apply" : "Synchronized"} /></header><div className="automation-fields"><Toggle label="Rumble Discord notifications" checked={Boolean(payload.config.desiredState.rumble?.enabled)} disabled={!canManage} onChange={(value) => update("rumble", "enabled", value)} /><label><span>Normal Rumble cadence (30–86400 seconds)</span><input type="number" min={30} max={86400} value={payload.config.desiredState.rumble?.intervalSeconds || 120} disabled={!canManage} onChange={(event) => update("rumble", "intervalSeconds", Number(event.target.value))} /></label><label><span>Notification channel ID</span><input value={payload.config.desiredState.discord?.notificationChannelId || ""} disabled={!canManage} onChange={(event) => update("discord", "notificationChannelId", event.target.value)} /></label><label><span>Mention role ID</span><input value={payload.config.desiredState.discord?.mentionRoleId || ""} disabled={!canManage} onChange={(event) => update("discord", "mentionRoleId", event.target.value)} /></label><button className="primary-button" type="button" disabled={!canManage || busy} onClick={() => void save()}>{busy ? "Saving…" : "Save desired state"}</button></div><p className="control-note">These fields converge with the existing Rumble/channel slash commands through revisioned bot sync. Environment secrets and immutable provider identity stay read-only. Process Start/Stop/Restart is deferred because no authenticated process manager exists.</p></section>
    <section className="poll-panel"><header><div><p className="eyebrow">RUMBLE RUNTIME</p><h2>Shared snapshot scheduler</h2></div><Status value={runtime?.rumbleConfigured ? String(runtime?.providerState || "configured") : "Not configured"} /></header><dl className="automation-facts"><Fact term="Poll lease" value={runtime?.pollLeaseActive ? "High-frequency active" : "Inactive"} /><Fact term="Interval" value={runtime?.pollingIntervalSeconds ? `${runtime.pollingIntervalSeconds}s` : "Normal cadence"} /><Fact term="Live stream" value={String(runtime?.livestreamTitle || runtime?.livestreamId || "None acquired")} /><Fact term="Backoff" value={runtime?.backoffSeconds ? `${runtime.backoffSeconds}s` : "None"} /><Fact term="Event window" value={runtime?.pollLeaseActive ? runtime?.backlogMayBeTruncated ? "Recent window at limit" : "Within provider limit" : "No active Poll work"} /><Fact term="Last fetch" value={runtime?.lastRumbleFetch ? formatDate(String(runtime.lastRumbleFetch)) : "Not reported"} /></dl><p className="control-note">Active Poll cadence is owned by the Poll lease (10–30 seconds); normal cadence above applies only when no high-frequency lease is active. The event-window signal reports bounded Rumble snapshot saturation, not local queue depth.</p></section></div>
    <section className="poll-panel automation-monitor"><header><div><p className="eyebrow">ACTIVE RUMBLE POLL</p><h2>{payload.activePoll?.title || "No high-frequency Poll lease"}</h2></div>{payload.activePoll ? <Link to="/polls">Open Poll authority</Link> : null}</header>{payload.activePoll ? <div className="automation-monitor__body"><dl><Fact term="Owner" value={payload.activePoll.owner.displayName} /><Fact term="Revision" value={String(payload.activePoll.revision)} /><Fact term="Source" value={payload.activePoll.rumbleSourceScope || "Waiting"} /><Fact term="Opened" value={payload.activePoll.openedAt ? formatDate(payload.activePoll.openedAt) : "Not recorded"} /></dl><div>{payload.activePoll.options.map((option) => <span key={option.id}><b>{option.trigger}</b> → {option.label}</span>)}</div></div> : <Empty>No Rumble-enabled Poll is open. The bot should remain on its normal provider cadence.</Empty>}</section>
    <section className="trigger-studio"><Deferred title="Ordinary chat" copy="Exact whole-message text can vote in an active Poll. General action rules are deferred." state="Poll voting operational" /><Deferred title="Followers" copy="Username, profile image and followed timestamp are mapped for a later trigger family." /><Deferred title="Subscribers" copy="User, amount and subscription time are known; execution is disabled." /><Deferred title="Gifted subscriptions" copy="Purchaser, gift type/count and video context are known; execution is disabled." /><Deferred title="Livestream state" copy="Live ID, title, visibility and safe metrics can feed future rules." /><Deferred title="Rants" copy="Schema not captured in a non-empty sample. Parsing and execution remain disabled." /></section>
    <section className="poll-panel"><header><div><p className="eyebrow">BOUNDED ACTIVITY</p><h2>Control-plane audit</h2></div></header><div className="automation-activity">{payload.activity.length ? payload.activity.map((item) => <article key={item.id}><Status value={item.result} /><strong>{label(item.event_type)}</strong><time>{formatDate(item.created_at)}</time></article>) : <Empty>No automation activity has been recorded.</Empty>}</div></section>
  </> : <Empty>Loading Automations authority…</Empty>}</div>;
}

function PageHeading({ eyebrow, title, copy, actions }: { eyebrow: string; title: string; copy: string; actions?: React.ReactNode }) { return <header className="poll-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div><div>{actions}</div></header>; }
function Metric({ label: text, value }: { label: string; value: number }) { return <article><strong>{value}</strong><span>{text}</span></article>; }
function Status({ value }: { value: string }) { return <span className={`poll-status poll-status--${value.toLowerCase().replace(/[^a-z]+/g, "-")}`}>{value}</span>; }
function Fact({ term, value }: { term: string; value: string }) { return <div><dt>{term}</dt><dd>{value}</dd></div>; }
function Alert({ children }: { children: React.ReactNode }) { return <div className="admin-alert" role="alert">{children}</div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="poll-empty">{children}</div>; }
function Deferred({ title, copy, state = "Deferred" }: { title: string; copy: string; state?: string }) { return <article><Status value={state} /><h3>{title}</h3><p>{copy}</p><button type="button" disabled>Execution unavailable</button></article>; }
function Toggle({ label: text, checked, disabled, onChange }: { label: string; checked: boolean; disabled: boolean; onChange: (value: boolean) => void }) { return <label className="automation-toggle"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span>{text}</span></label>; }
function message(value: unknown) { return value instanceof Error ? value.message : "The Poll control plane is unavailable."; }
function label(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Unknown" : new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short" }).format(date); }
