import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminIcon } from '../components/AdminIcon';
import { RumbleSubscriberTrend } from '../components/RumbleSubscriberTrend';
import { useAuth } from '../auth/AuthProvider';
import '../styles/rumble-intelligence.css';

type RecordEvidence = { id: string; displayName: string; username: string; user: string | null; amount: unknown; amountPresent: boolean; dateRaw: string | null; dateUtc: string | null; reviewAt: string | null; classification: string; rule: string };
type Sighting = { at: string; observedAt: string | null; provenance: string; classification: string; records: RecordEvidence[] };
type Person = { name: string; displayName: string; avatar: string | null; current: boolean; presence: string; classification: string; hasPaid: boolean; hasGifted: boolean; needsReview: boolean; hadPaid: boolean; hadGifted: boolean; records: RecordEvidence[]; timeline: Sighting[]; firstObserved: string; lastObserved: string; firstMissing: string | null; confirmedMissing: string | null };
type Point = { id: string; providerAt: string; observedAt: string | null; provenance: string; count: number; rawCount: number; arrivals: number | null; removals: number | null; gapBefore: boolean };
type Report = { source: string; label?: string; health: string; current: null | { id: string; providerAt: string; observedAt: string | null; receivedAt: string; provenance: string; rawCount: number; reportedCount: number; duplicateRows: number; unexpectedAmounts: number; reasons: string[] }; attempt: null | { observedAt: string | null; receivedAt: string; reasons: string[]; provenance: string; coverageGaps: number }; counts?: { [key: string]: number }; distinctCount?: number; accounts: Person[]; history: Point[]; coverage?: { from: string; to: string; bounded: boolean } };
const labels = ['Self-paid', 'Gifted', 'Self-paid + gifted', 'Needs review'];
const rosterPolicy = (person: Person) => person.current && person.hasPaid && !person.needsReview ? 'Included by self-paid roster' : person.current && person.needsReview ? 'Excluded: needs review' : person.current && person.hasGifted ? 'Excluded: gifted-only' : 'Excluded: not currently listed';
const date = (v: string | null | undefined) => v ? new Date(v).toLocaleString(undefined, { timeZoneName: 'short' }) : 'Unknown';
const csvCell = (v: unknown) => `"${String(v ?? '').replace(/^[\s]*[=+@-]/, m => `'${m}`).replaceAll('"', '""')}"`;
async function request<T>(path = '', body?: unknown, csrf = ''): Promise<T> {
  const response = await fetch(`/api/admin/rumble-intelligence${path}`, { credentials: 'include', cache: 'no-store', method: body ? 'POST' : 'GET', headers: { Accept: 'application/json', ...(body ? { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  if (!response.headers.get('content-type')?.includes('application/json')) throw new Error('The report did not return JSON. Check API routing.');
  const value = await response.json(); if (!response.ok) throw new Error(value.message || value.error || 'Report unavailable'); return value;
}

export function RumbleIntelligencePage() {
  const { csrfToken, hasCapability } = useAuth();
  const [reportRevision, setReportRevision] = useState(0);
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [presence, setPresence] = useState('current'); const [sort, setSort] = useState('name'); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(20); const [selected, setSelected] = useState<Person | null>(null); const [tab, setTab] = useState('registry');
  const [importFile, setImportFile] = useState<unknown>(null); const [preview, setPreview] = useState<{ observationId: string; previewFingerprint: string; source: string; providerAt: string; qualified: boolean; metadata: { rawCount: number; reasons: string[] } } | null>(null);
  const [archive, setArchive] = useState<{ bounded: boolean; records: (RecordEvidence & { firstProviderAt: string; lastProviderAt: string; firstBotObservedAt: string | null; lastBotObservedAt: string | null; firstReceivedAt: string; lastReceivedAt: string })[] } | null>(null);
  const [archiveError, setArchiveError] = useState('');
  const dialog = useRef<HTMLDialogElement>(null);
  const load = useCallback(async () => { setLoading(true); try { setReport(await request<Report>()); setReportRevision(value => value + 1); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Report unavailable'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (selected) dialog.current?.showModal(); else dialog.current?.close(); }, [selected]);
  useEffect(() => { let active = true; setArchive(null); setArchiveError(''); if (selected && report) request<NonNullable<typeof archive>>(`/person?source=${encodeURIComponent(report.source)}&name=${encodeURIComponent(selected.name)}`).then(value => { if (active) setArchive(value); }).catch(e => { if (active) setArchiveError(e instanceof Error ? e.message : 'Historical evidence unavailable'); }); return () => { active = false; }; }, [selected, report]);
  const people = useMemo(() => (report?.accounts || []).filter(a => (presence === 'all' || (presence === 'current' ? a.current : !a.current)) && a.displayName.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'paid' ? a.hasPaid : filter === 'gift' ? a.hasGifted : a.classification === filter))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : b.lastObserved.localeCompare(a.lastObserved)), [report, presence, query, filter, sort]);
  const pages = Math.max(1, Math.ceil(people.length / pageSize)); const visiblePage = Math.min(page, pages - 1);
  function exportCsv() {
    const rows = [['Source', 'Snapshot ID', 'As of UTC', 'Name', 'Presence', 'Classification', 'Rule', 'Basis', 'Reported dates', 'First observed within coverage', 'Last observed', 'Uncertainty'], ...people.map(a => [report?.source, report?.current?.id, report?.current?.providerAt, a.displayName, a.presence, a.classification, 'amount-v1', '500 cents self-paid; 0 gifted; other review', a.records.map(r => r.dateRaw).join(' | '), a.firstObserved, a.lastObserved, 'API-listed; renewal/expiry unknown; observation coverage bounded'])];
    const url = URL.createObjectURL(new Blob([rows.map(row => row.map(csvCell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'rumble-subscribers.csv'; a.click(); URL.revokeObjectURL(url);
  }
  async function previewImport(file?: File) { setPreview(null); setImportFile(null); if (!file) return; try { if (file.size > 2 * 1024 * 1024) throw new Error('Import must be at most 2 MiB.'); const snapshot: unknown = JSON.parse(await file.text()); const value = await request<NonNullable<typeof preview>>('/import/preview', { snapshot }, csrfToken); setImportFile(snapshot); setPreview(value); } catch (e) { setError(e instanceof Error ? e.message : 'Import failed'); } }
  async function commitImport() { try { await request('/import/commit', { snapshot: importFile, observationId: preview?.observationId, previewFingerprint: preview?.previewFingerprint }, csrfToken); setPreview(null); setImportFile(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Import failed'); } }
  const current = report?.current;
  return <main className="ri-workspace">
    <header className="ri-heading"><div><p className="eyebrow">RUMBLE INTELLIGENCE</p><h1>Subscriber Registry</h1><p>Currently listed subscribers · observed evidence, not verified billing status</p></div><button className="secondary-button" disabled={loading} onClick={() => void load()}>{loading ? 'Refreshing…' : 'Refresh report'}</button></header>
    {error && <div role="alert" className="ri-alert">{error}{report && ' Last-known report retained; refresh failed.'}</div>}
    <RumbleSubscriberTrend refreshVersion={reportRevision} source={report?.source || "user:1sl8zm"} snapshotId={current?.id} total={report?.distinctCount} paidTotal={report?.counts ? (report.counts['Self-paid'] || 0) + (report.counts['Self-paid + gifted'] || 0) : undefined} asOf={current?.providerAt} />
    <section className="ri-source" aria-label="Source and freshness" data-status={error ? 'unavailable' : report?.health || 'loading'}>
      <header className="ri-source-header"><div className="ri-source-identity"><span className="ri-source-mark"><AdminIcon name="rumble" size={25} /></span><div><p className="ri-source-eyebrow">SOURCE &amp; FRESHNESS</p><h2>{report?.label || 'ThirdRailify'}</h2><code>{report?.source || 'user:1sl8zm'}</code></div></div><span className="ri-source-status"><i />{error ? 'Unavailable' : report?.health === 'qualified' ? 'Qualified snapshot' : report?.health || 'Loading'}</span></header>
      <div className="ri-source-overview"><div className="ri-source-observed"><span>As observed from Rumble</span><time>{date(current?.providerAt)}</time></div><div><span>Collection</span><strong>{current ? current.provenance === 'live' ? 'Live Bot observation' : 'Historical import' : 'Awaiting observation'}</strong></div><div><span>Collection quality</span><strong>{report?.attempt ? report.attempt.reasons.length ? 'Review required' : 'No reported quality errors' : 'Awaiting observation'}</strong></div></div>
      <details><summary><span>Source and collection details</span><span className="ri-source-disclosure" aria-hidden="true">+</span></summary><div className="ri-source-details"><dl className="ri-source-fields">
        <Field label="Source scope" value={report?.source?.startsWith('channel:') ? 'Channel-scoped' : 'User-scoped'} />
        <Field label="Bot fetch" value={date(current?.observedAt)} /><Field label="Admin received" value={date(current?.receivedAt)} />
        <Field label="Latest transport attempt" value={date(report?.attempt?.observedAt || report?.attempt?.receivedAt)} />
        <Field label="Provenance" value={current?.provenance || 'No qualified snapshot'} /><Field label="Lost coverage observations" value={report?.attempt ? String(report.attempt.coverageGaps || 0) : 'Unknown'} />
      </dl>{!!report?.attempt?.reasons.length && <div className="ri-source-quality"><span>Reported quality issues</span><p>{report.attempt.reasons.join(', ')}</p></div>}<dl className="ri-source-snapshot"><Field label="Snapshot ID" value={current?.id || 'None'} /></dl><p className="ri-source-note">Provider time measures observation freshness; it does not prove internal subscriber data changed.</p></div></details>
    </section>
    <div className="ri-stats"><article><span>Reported records</span><strong>{current?.reportedCount ?? '—'}</strong></article><article><span>Distinct listed accounts</span><strong>{report?.distinctCount ?? '—'}</strong></article>{labels.map(label => <article key={label}><span>{label}</span><strong>{report?.counts?.[label] ?? '—'}</strong></article>)}</div>
    <p className="ri-note">Amount-derived policy: exactly 500 cents = Self-paid; exactly 0 = Gifted recipient. Both means simultaneous current records and qualifies once for a self-paid roster. Other or missing amounts need review. A Gifted Sub Purchase is a separate purchaser event.</p>
    <p className="ri-note"><Link to="/automations?subscriberRoster=1">Manage current self-paid subscriber Wheel automation</Link></p>
    <nav className="ri-tabs" aria-label="Report views">{['registry', 'history', 'data quality'].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
    {tab === 'registry' && <section aria-label="Subscriber Registry"><div className="ri-filters"><label>Search names<input value={query} onChange={e => { setQuery(e.target.value); setPage(0); }} placeholder="Find a subscriber" /></label><label>Classification<select value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}><option value="all">All classifications</option>{labels.map(l => <option key={l}>{l}</option>)}<option value="paid">Has self-paid (overlaps)</option><option value="gift">Has gifted (overlaps)</option></select></label><label>Presence<select value={presence} onChange={e => { setPresence(e.target.value); setPage(0); }}><option value="current">Currently listed</option><option value="missing">Missing / no longer listed</option><option value="all">All observed accounts</option></select></label><label>Sort<select value={sort} onChange={e => setSort(e.target.value)}><option value="name">Name A–Z</option><option value="observed">Last observed</option></select></label><button className="secondary-button" onClick={exportCsv} disabled={!people.length}>Export filtered CSV</button></div>
      <div className="ri-table-scroll"><table><thead><tr><th>Subscriber</th><th>Presence</th><th>Classification</th><th>Roster policy</th><th>Reported subscription date(s)</th><th>Last observed</th></tr></thead><tbody>{people.slice(visiblePage * pageSize, (visiblePage + 1) * pageSize).map(a => <tr key={a.name}><td><button className="ri-person" onClick={() => setSelected(a)}><Avatar name={a.displayName} url={a.avatar} /><span>{a.displayName}</span></button></td><td>{a.presence}</td><td><TypeChip classification={a.classification} />{!a.current && <small>Last observed classification</small>}</td><td><RosterChip person={a} /></td><td>{a.records.length ? a.records.map(r => <small key={r.id}>{date(r.dateUtc)}</small>) : 'No current records'}</td><td>{date(a.lastObserved)}</td></tr>)}</tbody></table></div>
      {!people.length && <p className="ri-empty">{loading ? 'Loading subscriber observations…' : current ? 'No subscribers match these filters.' : 'No qualified snapshot yet. The Bot’s next successful observation will populate this report.'}</p>}
      <footer className="ri-pagination"><label>Rows per page<select aria-label="Rows per page" value={pageSize} onChange={e => { setPageSize(Number(e.target.value)); setPage(0); }}>{[10, 20, 50, 100].map(size => <option key={size} value={size}>{size}</option>)}</select></label><span>{people.length} accounts · Page {visiblePage + 1} of {pages}</span><button disabled={visiblePage === 0} onClick={() => setPage(visiblePage - 1)}>Previous</button><button disabled={visiblePage + 1 >= pages} onClick={() => setPage(visiblePage + 1)}>Next</button></footer></section>}
    {tab === 'history' && <section><h2>Observed membership history</h2><p>Up to 180 qualified checkpoints. Coverage: {date(report?.coverage?.from)} – {date(report?.coverage?.to)}. Gaps do not imply continuous coverage. Initial arrivals/removals are unknown.</p><div className="ri-table-scroll"><table><thead><tr><th>Observed provider time</th><th>Accounts</th><th>Raw records</th><th>Arrivals</th><th>Removals</th><th>Coverage</th></tr></thead><tbody>{report?.history.slice().reverse().map(p => <tr key={p.id}><td>{date(p.providerAt)}</td><td><meter min="0" max={Math.max(1, ...report.history.map(h => h.count))} value={p.count} /> {p.count}</td><td>{p.rawCount}</td><td>{p.arrivals ?? 'Unknown'}</td><td>{p.removals ?? 'Unknown'}</td><td>{p.provenance}{p.gapBefore ? ' · gap before observation' : ''}</td></tr>)}</tbody></table></div></section>}
    {tab === 'data quality' && <section><h2>Data quality and historical imports</h2><p>Raw rows: {current?.rawCount ?? '—'} · Identical duplicate rows: {current?.duplicateRows ?? '—'} · Unexpected/missing amounts: {current?.unexpectedAmounts ?? '—'}.</p><p>Count consistency is not a provider guarantee of complete active entitlements. First disappearance is pending confirmation; a second distinct newer qualified observation confirms “No longer listed”. Exact cancellation and renewal dates remain unknown.</p><p>Record identity can collide when the provider reports identical grants without a subscription ID. Historical details are bounded to the displayed coverage.</p>{hasCapability('rumble_intelligence.manage') && <div className="ri-import"><label>Preview original ThirdRailify snapshot<input type="file" accept="application/json,.json" onChange={e => void previewImport(e.target.files?.[0])} /></label><p>Historical provenance only. The separate danielclancy source and derived audit JSON are rejected.</p>{preview && <div><p>{preview.source} · {date(preview.providerAt)} · {preview.metadata.rawCount} rows · {preview.qualified ? 'Qualified' : preview.metadata.reasons.join(', ')}</p><button className="primary-button" onClick={() => void commitImport()}>Commit reviewed historical import</button></div>}</div>}</section>}
    <dialog ref={dialog} className="ri-drawer" onCancel={() => setSelected(null)} onClose={() => setSelected(null)} aria-labelledby="ri-person-title">{selected && <>
      <header className="ri-detail-header"><div className="ri-detail-identity"><Avatar key={selected.name} name={selected.displayName} url={selected.avatar} /><div><p className="ri-detail-eyebrow">SUBSCRIBER PROFILE</p><h2 id="ri-person-title">{selected.displayName}</h2></div></div><button onClick={() => setSelected(null)} aria-label="Close subscriber details">Close</button></header>
      <div className="ri-detail-body">
        <div className="ri-detail-badges"><span className={`ri-detail-presence${selected.current ? ' is-current' : ''}`}>{selected.presence}</span><TypeChip classification={selected.classification} /><RosterChip person={selected} /></div>
        <section className="ri-detail-overview" aria-label="Subscriber overview"><dl className="ri-detail-fields">
          <Field label="Rumble source" value={report?.source} /><Field label="Normalized name" value={selected.name} />
          <Field label="Historical paid evidence" value={selected.hadPaid ? 'Yes' : 'No observed evidence'} /><Field label="Historical gifted evidence" value={selected.hadGifted ? 'Yes' : 'No observed evidence'} />
          <Field label="First observed within coverage" value={date(selected.firstObserved)} /><Field label="Last observed within coverage" value={date(selected.lastObserved)} />
        </dl></section>
        {selected.firstMissing && <section className="ri-detail-notice"><h3>Disappearance interval</h3><dl className="ri-detail-fields"><Field label="Last listed" value={date(selected.lastObserved)} /><Field label="First missing" value={date(selected.firstMissing)} /><Field label="Confirmed missing" value={date(selected.confirmedMissing)} /></dl></section>}
        <section className="ri-detail-section"><div className="ri-detail-section-title"><h3>Current record evidence</h3><span>{selected.records.length} records</span></div>{selected.records.length ? selected.records.map(r => <Evidence key={r.id} record={r} />) : <p className="ri-detail-caption">No records in the current qualified snapshot.</p>}</section>
        <section className="ri-detail-section"><div className="ri-detail-section-title"><h3>Retained record history</h3>{archive && <span>{archive.records.length} records</span>}</div>
          {archiveError && <p role="alert" className="ri-alert">{archiveError}</p>}{!archive && !archiveError && <p role="status" className="ri-detail-caption">Loading retained record evidence...</p>}
          {archive && <><p className="ri-detail-caption">Distinct reported records across retained history{archive.bounded ? ' (latest 500; additional evidence retained)' : ''}.</p>{archive.records.map(r => <details key={r.id}><summary><span>{r.classification}</span><time>{r.dateRaw || 'Date unavailable'}</time></summary><Evidence record={r} /><dl className="ri-detail-fields ri-detail-archive-times"><Field label="First provider snapshot" value={date(r.firstProviderAt)} /><Field label="Last provider snapshot" value={date(r.lastProviderAt)} /><Field label="First actual Bot observation" value={date(r.firstBotObservedAt)} /><Field label="Last actual Bot observation" value={date(r.lastBotObservedAt)} /><Field label="First Admin receipt" value={date(r.firstReceivedAt)} /><Field label="Last Admin receipt" value={date(r.lastReceivedAt)} /></dl></details>)}</>}
        </section>
        <section className="ri-detail-section"><div className="ri-detail-section-title"><h3>Recent observation timeline</h3><span>{selected.timeline.length} observations</span></div>{selected.timeline.slice().reverse().map(s => <details key={s.at}><summary><time>{date(s.at)}</time><span>{s.classification}</span><span className="ri-detail-provenance">{s.provenance}</span></summary><dl className="ri-detail-fields"><Field label="Actual Bot fetch" value={date(s.observedAt)} /></dl>{s.records.map(r => <Evidence key={r.id} record={r} />)}</details>)}</section>
        <p className="ri-detail-policy">Rule <code>amount-v1</code> is an operator amount policy, not a provider <code>is_gifted</code> flag. Billing renewal and actual expiry remain unknown.</p>
      </div>
    </>}</dialog>
  </main>;
}
function TypeChip({ classification }: { classification: string }) {
  const tone = ({ 'Self-paid': 'paid', 'Gifted': 'gifted', 'Self-paid + gifted': 'mixed', 'Needs review': 'unknown' } as Record<string, string>)[classification] || 'unknown';
  return <span className={`ri-chip ri-type-chip ri-type-chip--${tone}`}>{classification}</span>;
}
function RosterChip({ person }: { person: Person }) { const included = person.current && person.hasPaid && !person.needsReview; return <span className={`ri-chip ri-type-chip ri-type-chip--${included ? 'paid' : 'unknown'}`}>{rosterPolicy(person)}</span>; }
function Field({ label, value }: { label: string; value: string | null | undefined }) { return <div className="ri-detail-field"><dt>{label}</dt><dd>{value ?? 'Unknown'}</dd></div>; }
function Evidence({ record: r }: { record: RecordEvidence }) {
  return <article className="ri-evidence">
    <div className="ri-evidence-heading"><TypeChip classification={r.classification} /><span className="ri-evidence-rule">Rule <code>{r.rule}</code></span></div>
    <dl className="ri-detail-fields">
      <Field label="Raw amount_cents" value={r.amountPresent ? JSON.stringify(r.amount) : 'missing'} /><Field label="Raw user" value={r.user || 'missing'} /><Field label="Raw username" value={r.username} />
      <Field label="Reported subscription date" value={r.dateRaw || 'Invalid/missing'} /><Field label="Validated UTC" value={r.dateUtc || 'Unavailable'} /><Field label="30-day review date" value={date(r.reviewAt)} />
    </dl>
    <p className="ri-evidence-note">Initial review only. Currently listed records are not expired automatically.</p>
    <dl className="ri-evidence-id"><Field label="Record ID" value={r.id} /></dl>
  </article>;
}

function Avatar({ name, url }: { name: string; url: string | null }) { const [failed, setFailed] = useState(false); return <span className="ri-avatar">{name.slice(0, 1)}{url && !failed && <img src={url} alt="" loading="lazy" referrerPolicy="no-referrer" onError={() => setFailed(true)} />}</span>; }
