import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { RumbleSubscriberTrend } from '../components/RumbleSubscriberTrend';
import { useAuth } from '../auth/AuthProvider';
import '../styles/rumble-intelligence.css';

type RecordEvidence = { id: string; displayName: string; username: string; user: string | null; amount: unknown; amountPresent: boolean; dateRaw: string | null; dateUtc: string | null; reviewAt: string | null; classification: string; rule: string };
type Sighting = { at: string; observedAt: string | null; provenance: string; classification: string; records: RecordEvidence[] };
type Person = { name: string; displayName: string; avatar: string | null; current: boolean; presence: string; classification: string; hasPaid: boolean; hasGifted: boolean; hadPaid: boolean; hadGifted: boolean; records: RecordEvidence[]; timeline: Sighting[]; firstObserved: string; lastObserved: string; firstMissing: string | null; confirmedMissing: string | null };
type Point = { id: string; providerAt: string; observedAt: string | null; provenance: string; count: number; rawCount: number; arrivals: number | null; removals: number | null; gapBefore: boolean };
type Report = { source: string; label?: string; health: string; current: null | { id: string; providerAt: string; observedAt: string | null; receivedAt: string; provenance: string; rawCount: number; reportedCount: number; duplicateRows: number; unexpectedAmounts: number; reasons: string[] }; attempt: null | { observedAt: string | null; receivedAt: string; reasons: string[]; provenance: string; coverageGaps: number }; counts?: { [key: string]: number }; distinctCount?: number; accounts: Person[]; history: Point[]; coverage?: { from: string; to: string; bounded: boolean } };
const labels = ['Self-paid', 'Gifted', 'Self-paid + gifted', 'Needs review'];
const date = (v: string | null | undefined) => v ? new Date(v).toLocaleString(undefined, { timeZoneName: 'short' }) : 'Unknown';
const csvCell = (v: unknown) => `"${String(v ?? '').replace(/^[\s]*[=+@-]/, m => `'${m}`).replaceAll('"', '""')}"`;
async function request<T>(path = '', body?: unknown, csrf = ''): Promise<T> {
  const response = await fetch(`/api/admin/rumble-intelligence${path}`, { credentials: 'include', cache: 'no-store', method: body ? 'POST' : 'GET', headers: { Accept: 'application/json', ...(body ? { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  if (!response.headers.get('content-type')?.includes('application/json')) throw new Error('The report did not return JSON. Check API routing.');
  const value = await response.json(); if (!response.ok) throw new Error(value.message || value.error || 'Report unavailable'); return value;
}

export function RumbleIntelligencePage() {
  const { csrfToken, hasCapability } = useAuth();
  const [reportRevision, setReportRevision] = useState(0);
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [presence, setPresence] = useState('current'); const [sort, setSort] = useState('name'); const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(20); const [selected, setSelected] = useState<Person | null>(null); const [tab, setTab] = useState('registry');
  const [importFile, setImportFile] = useState<unknown>(null); const [preview, setPreview] = useState<{ observationId: string; previewFingerprint: string; source: string; providerAt: string; qualified: boolean; metadata: { rawCount: number; reasons: string[] } } | null>(null);
  const [archive, setArchive] = useState<{ bounded: boolean; records: (RecordEvidence & { firstProviderAt: string; lastProviderAt: string; firstBotObservedAt: string | null; lastBotObservedAt: string | null; firstReceivedAt: string; lastReceivedAt: string })[] } | null>(null);
  const [archiveError, setArchiveError] = useState('');
  const dialog = useRef<HTMLDialogElement>(null);
  const load = useCallback(async () => { setLoading(true); try { setReport(await request<Report>()); setReportRevision(value => value + 1); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Report unavailable'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (selected) dialog.current?.showModal(); else dialog.current?.close(); }, [selected]);
  useEffect(() => { let active = true; setArchive(null); setArchiveError(''); if (selected && report) request<NonNullable<typeof archive>>(`/person?source=${encodeURIComponent(report.source)}&name=${encodeURIComponent(selected.name)}`).then(value => { if (active) setArchive(value); }).catch(e => { if (active) setArchiveError(e instanceof Error ? e.message : 'Historical evidence unavailable'); }); return () => { active = false; }; }, [selected, report]);
  const people = useMemo(() => (report?.accounts || []).filter(a => (presence === 'all' || (presence === 'current' ? a.current : !a.current)) && a.displayName.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'paid' ? a.hasPaid : filter === 'gift' ? a.hasGifted : a.classification === filter))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : b.lastObserved.localeCompare(a.lastObserved)), [report, presence, query, filter, sort]);
  const pages = Math.max(1, Math.ceil(people.length / pageSize)); const visiblePage = Math.min(page, pages - 1);
  function exportCsv() {
    const rows = [['Source', 'Snapshot ID', 'As of UTC', 'Name', 'Presence', 'Classification', 'Rule', 'Basis', 'Reported dates', 'First observed within coverage', 'Last observed', 'Uncertainty'], ...people.map(a => [report?.source, report?.current?.id, report?.current?.providerAt, a.displayName, a.presence, a.classification, 'amount-v1', '500 cents self-paid; 0 gifted; other review', a.records.map(r => r.dateRaw).join(' | '), a.firstObserved, a.lastObserved, 'API-listed; renewal/expiry unknown; observation coverage bounded'])];
    const url = URL.createObjectURL(new Blob([rows.map(row => row.map(csvCell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'rumble-subscribers.csv'; a.click(); URL.revokeObjectURL(url);
  }
  async function previewImport(file?: File) { setPreview(null); setImportFile(null); if (!file) return; try { if (file.size > 2 * 1024 * 1024) throw new Error('Import must be at most 2 MiB.'); const snapshot: unknown = JSON.parse(await file.text()); const value = await request<NonNullable<typeof preview>>('/import/preview', { snapshot }, csrfToken); setImportFile(snapshot); setPreview(value); } catch (e) { setError(e instanceof Error ? e.message : 'Import failed'); } }
  async function commitImport() { try { await request('/import/commit', { snapshot: importFile, observationId: preview?.observationId, previewFingerprint: preview?.previewFingerprint }, csrfToken); setPreview(null); setImportFile(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Import failed'); } }
  const current = report?.current;
  return <main className="ri-workspace">
    <header className="ri-heading"><div><p className="eyebrow">RUMBLE INTELLIGENCE</p><h1>Subscriber Registry</h1><p>Currently listed subscribers · observed evidence, not verified billing status</p></div><button className="secondary-button" disabled={loading} onClick={() => void load()}>{loading ? 'Refreshing…' : 'Refresh report'}</button></header>
    {error && <div role="alert" className="ri-alert">{error}{report && ' Last-known report retained; refresh failed.'}</div>}
    <RumbleSubscriberTrend refreshVersion={reportRevision} source={report?.source || "user:1sl8zm"} snapshotId={current?.id} total={report?.distinctCount} asOf={current?.providerAt} />
    <section className="ri-source" aria-label="Source and freshness"><div><strong>{report?.label || 'ThirdRailify'}</strong><span className="ri-chip">{error ? 'Unavailable' : report?.health || 'Loading'}</span><p>As observed from Rumble at {date(current?.providerAt)}</p></div><details><summary>Source and collection details</summary><p>{report?.source || 'user:1sl8zm'} · {report?.source?.startsWith('channel:') ? 'channel-scoped' : 'user-scoped'}</p><p>Bot fetch: {date(current?.observedAt)} · Admin received: {date(current?.receivedAt)}</p><p>Latest transport attempt: {date(report?.attempt?.observedAt || report?.attempt?.receivedAt)} · {report?.attempt?.reasons.join(', ') || 'No reported quality errors'}</p><p>Provenance: {current?.provenance || 'No qualified snapshot'} · Lost coverage observations: {report?.attempt?.coverageGaps || 0}</p><p>Snapshot ID: <code>{current?.id || 'None'}</code></p><p>Provider time measures observation freshness; it does not prove internal subscriber data changed.</p></details></section>
    <div className="ri-stats"><article><span>Reported records</span><strong>{current?.reportedCount ?? '—'}</strong></article><article><span>Distinct listed accounts</span><strong>{report?.distinctCount ?? '—'}</strong></article>{labels.map(label => <article key={label}><span>{label}</span><strong>{report?.counts?.[label] ?? '—'}</strong></article>)}</div>
    <p className="ri-note">Amount-derived classification: 500 cents = Self-paid; 0 = Gifted. Both means simultaneous current records. Other or missing amounts need review. Gifted still has the operator’s nominal 500-cent value.</p>
    <nav className="ri-tabs" aria-label="Report views">{['registry', 'history', 'data quality'].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
    {tab === 'registry' && <section aria-label="Subscriber Registry"><div className="ri-filters"><label>Search names<input value={query} onChange={e => { setQuery(e.target.value); setPage(0); }} placeholder="Find a subscriber" /></label><label>Classification<select value={filter} onChange={e => { setFilter(e.target.value); setPage(0); }}><option value="all">All classifications</option>{labels.map(l => <option key={l}>{l}</option>)}<option value="paid">Has self-paid (overlaps)</option><option value="gift">Has gifted (overlaps)</option></select></label><label>Presence<select value={presence} onChange={e => { setPresence(e.target.value); setPage(0); }}><option value="current">Currently listed</option><option value="missing">Missing / no longer listed</option><option value="all">All observed accounts</option></select></label><label>Sort<select value={sort} onChange={e => setSort(e.target.value)}><option value="name">Name A–Z</option><option value="observed">Last observed</option></select></label><button className="secondary-button" onClick={exportCsv} disabled={!people.length}>Export filtered CSV</button></div>
      <div className="ri-table-scroll"><table><thead><tr><th>Subscriber</th><th>Presence</th><th>Classification</th><th>Reported subscription date(s)</th><th>Last observed</th></tr></thead><tbody>{people.slice(visiblePage * pageSize, (visiblePage + 1) * pageSize).map(a => <tr key={a.name}><td><button className="ri-person" onClick={() => setSelected(a)}><Avatar name={a.displayName} url={a.avatar} /><span>{a.displayName}</span></button></td><td>{a.presence}</td><td><span className="ri-chip">{a.classification}</span>{!a.current && <small>Last observed classification</small>}</td><td>{a.records.length ? a.records.map(r => <small key={r.id}>{date(r.dateUtc)}</small>) : 'No current records'}</td><td>{date(a.lastObserved)}</td></tr>)}</tbody></table></div>
      {!people.length && <p className="ri-empty">{loading ? 'Loading subscriber observations…' : current ? 'No subscribers match these filters.' : 'No qualified snapshot yet. The Bot’s next successful observation will populate this report.'}</p>}
      <footer className="ri-pagination"><label>Rows per page<select aria-label="Rows per page" value={pageSize} onChange={e => { setPageSize(Number(e.target.value)); setPage(0); }}>{[10, 20, 50, 100].map(size => <option key={size} value={size}>{size}</option>)}</select></label><span>{people.length} accounts · Page {visiblePage + 1} of {pages}</span><button disabled={visiblePage === 0} onClick={() => setPage(visiblePage - 1)}>Previous</button><button disabled={visiblePage + 1 >= pages} onClick={() => setPage(visiblePage + 1)}>Next</button></footer></section>}
    {tab === 'history' && <section><h2>Observed membership history</h2><p>Up to 180 qualified checkpoints. Coverage: {date(report?.coverage?.from)} – {date(report?.coverage?.to)}. Gaps do not imply continuous coverage. Initial arrivals/removals are unknown.</p><div className="ri-table-scroll"><table><thead><tr><th>Observed provider time</th><th>Accounts</th><th>Raw records</th><th>Arrivals</th><th>Removals</th><th>Coverage</th></tr></thead><tbody>{report?.history.slice().reverse().map(p => <tr key={p.id}><td>{date(p.providerAt)}</td><td><meter min="0" max={Math.max(1, ...report.history.map(h => h.count))} value={p.count} /> {p.count}</td><td>{p.rawCount}</td><td>{p.arrivals ?? 'Unknown'}</td><td>{p.removals ?? 'Unknown'}</td><td>{p.provenance}{p.gapBefore ? ' · gap before observation' : ''}</td></tr>)}</tbody></table></div></section>}
    {tab === 'data quality' && <section><h2>Data quality and historical imports</h2><p>Raw rows: {current?.rawCount ?? '—'} · Identical duplicate rows: {current?.duplicateRows ?? '—'} · Unexpected/missing amounts: {current?.unexpectedAmounts ?? '—'}.</p><p>Count consistency is not a provider guarantee of complete active entitlements. First disappearance is pending confirmation; a second distinct newer qualified observation confirms “No longer listed”. Exact cancellation and renewal dates remain unknown.</p><p>Record identity can collide when the provider reports identical grants without a subscription ID. Historical details are bounded to the displayed coverage.</p>{hasCapability('rumble_intelligence.manage') && <div className="ri-import"><label>Preview original ThirdRailify snapshot<input type="file" accept="application/json,.json" onChange={e => void previewImport(e.target.files?.[0])} /></label><p>Historical provenance only. The separate danielclancy source and derived audit JSON are rejected.</p>{preview && <div><p>{preview.source} · {date(preview.providerAt)} · {preview.metadata.rawCount} rows · {preview.qualified ? 'Qualified' : preview.metadata.reasons.join(', ')}</p><button className="primary-button" onClick={() => void commitImport()}>Commit reviewed historical import</button></div>}</div>}</section>}
    <dialog ref={dialog} className="ri-drawer" onCancel={() => setSelected(null)} onClose={() => setSelected(null)} aria-labelledby="ri-person-title">{selected && <><header><h2 id="ri-person-title">{selected.displayName}</h2><button onClick={() => setSelected(null)} aria-label="Close subscriber details">Close</button></header><p>{selected.presence} · {selected.classification}</p><p>Source {report?.source} · normalized name {selected.name}</p><p>Historical paid evidence: {selected.hadPaid ? 'Yes' : 'No observed evidence'} · Historical gifted evidence: {selected.hadGifted ? 'Yes' : 'No observed evidence'}</p><p>First/last within coverage: {date(selected.firstObserved)} / {date(selected.lastObserved)}</p>{selected.firstMissing && <p>Disappearance interval: after {date(selected.lastObserved)}, first missing {date(selected.firstMissing)}. Confirmation: {date(selected.confirmedMissing)}.</p>}<h3>Current record evidence ({selected.records.length})</h3>{selected.records.map(r => <Evidence key={r.id} record={r} />)}<h3>Retained record history</h3>{archiveError && <p role="alert">{archiveError}</p>}{!archive && !archiveError && <p>Loading retained record evidence?</p>}{archive && <><p>{archive.records.length} distinct reported records across retained history{archive.bounded ? " (latest 500; additional evidence retained)" : ""}.</p>{archive.records.map(r => <details key={r.id}><summary>{r.classification} ? {r.dateRaw}</summary><Evidence record={r} /><p>First/last provider snapshot: {date(r.firstProviderAt)} / {date(r.lastProviderAt)}</p><p>Actual Bot observations: {date(r.firstBotObservedAt)} / {date(r.lastBotObservedAt)}</p><p>Admin receipts: {date(r.firstReceivedAt)} / {date(r.lastReceivedAt)}</p></details>)}</>}<h3>Recent observation timeline</h3>{selected.timeline.slice().reverse().map(s => <details key={s.at}><summary>{date(s.at)} · {s.classification} · {s.provenance}</summary><p>Actual Bot fetch: {date(s.observedAt)}</p>{s.records.map(r => <Evidence key={r.id} record={r} />)}</details>)}<p>Rule amount-v1 is an operator amount policy, not a provider is_gifted flag. Billing renewal and actual expiry remain unknown.</p></>}</dialog>
  </main>;
}
function Evidence({ record: r }: { record: RecordEvidence }) { return <article className="ri-evidence"><strong>{r.classification}</strong><p>Raw amount_cents: {r.amountPresent ? JSON.stringify(r.amount) : 'missing'} · raw user: {r.user || 'missing'} · raw username: {r.username}</p><p>Reported subscription date: {r.dateRaw || 'Invalid/missing'}<br />Validated UTC: {r.dateUtc || 'Unavailable'}</p><p>30-day review date: {date(r.reviewAt)}. Initial review only; currently listed records are not expired automatically.</p><small>Rule {r.rule} · record {r.id}</small></article>; }

function Avatar({ name, url }: { name: string; url: string | null }) { const [failed, setFailed] = useState(false); return <span className="ri-avatar">{name.slice(0, 1)}{url && !failed && <img src={url} alt="" loading="lazy" referrerPolicy="no-referrer" onError={() => setFailed(true)} />}</span>; }
