export type AdminArea = {
  path: string;
  parentPath?: string;
  label: string;
  shortLabel: string;
  icon: "overview" | "analytics" | "content" | "watch" | "wheels" | "products" | "orders" | "commerce" | "payments" | "business" | "tax" | "emails" | "fulfillment" | "media" | "goats" | "pending" | "approved" | "rejected" | "comments" | "vip" | "users" | "integrations" | "settings";
  summary: string;
  futureScope: string[];
};

export const adminAreas: AdminArea[] = [
  {
    path: "/",
    label: "Overview",
    shortLabel: "Overview",
    icon: "overview",
    summary: "Cross-system operational state, queues, and direct workspace routes.",
    futureScope: ["Authenticated system posture", "Live authority summaries", "Actionable moderation queues"],
  },
  {
    path: "/analytics",
    label: "Audience Analytics",
    shortLabel: "Analytics",
    icon: "analytics",
    summary: "Privacy-minimized first-party audience activity and truthful revenue pulse.",
    futureScope: ["Rolling traffic comparisons", "Coarse activity map", "Authoritative collected revenue"],
  },
  {
    path: "/watch",
    label: "Watch / Broadcast",
    shortLabel: "Watch",
    icon: "watch",
    summary: "Current signal visibility and retained episode controls.",
    futureScope: ["Signed-ingest archive", "24-record retention", "Public visibility controls"],
  },
  {
    path: "/inbox",
    label: "Admin Inbox",
    shortLabel: "Inbox",
    icon: "emails",
    summary: "Internal copies of actionable Admin notices and delivery alerts.",
    futureScope: ["Unread state", "Action links", "Transactional notice history"],
  },
  {
    path: "/content",
    label: "Site Content",
    shortLabel: "Content",
    icon: "content",
    summary: "Public announcement and automatic Live Now presentation controls.",
    futureScope: ["Normal promo banner", "Live takeover presentation", "Safe Public projection"],
  },
  {
    path: "/shop",
    label: "Shop",
    shortLabel: "Shop",
    icon: "products",
    summary: "Product, collection, order, and customer authority.",
    futureScope: ["Products", "Collections", "Orders", "Customers"],
  },
  {
    path: "/wheels",
    label: "Wheels",
    shortLabel: "Wheels",
    icon: "wheels",
    summary: "Competition wheel persistence, lifecycle, locks, access, and official results.",
    futureScope: ["Admin D1 authority", "Approved creators", "Immutable official draws"],
  },
  {
    path: "/wheels/stages",
    parentPath: "/wheels",
    label: "Wheel Stages",
    shortLabel: "Stages",
    icon: "wheels",
    summary: "Multi-Wheel Stage ownership, visibility, lifecycle, and membership.",
    futureScope: ["Stage moderation", "Ordered Wheel membership", "Safe deletion"],
  },
  {
    path: "/wheels/access",
    parentPath: "/wheels",
    label: "Wheel Access",
    shortLabel: "Access",
    icon: "users",
    summary: "Global creator grants and per-wheel least-privilege roles.",
    futureScope: ["Creator approval", "Owner transfer", "Editor and spinner assignments"],
  },
  {
    path: "/wheels/results",
    parentPath: "/wheels",
    label: "Official Results",
    shortLabel: "Results",
    icon: "orders",
    summary: "Immutable official draw history and audited voiding.",
    futureScope: ["Snapshot hashes", "Idempotency", "Non-destructive voids"],
  },
  {
    path: "/products",
    parentPath: "/shop",
    label: "Products",
    shortLabel: "Products",
    icon: "products",
    summary: "Provider-neutral catalogue authority with synchronization disabled.",
    futureScope: ["Product source adapters", "Catalogue validation", "Safe provider write boundary"],
  },
  {
    path: "/collections",
    parentPath: "/shop",
    label: "Collections",
    shortLabel: "Collections",
    icon: "products",
    summary: "Stable collection metadata, ordering, visibility, and product assignment.",
    futureScope: ["Public collection projection", "Stable slugs", "Safe archival"],
  },
  {
    path: "/orders",
    parentPath: "/shop",
    label: "Orders",
    shortLabel: "Orders",
    icon: "orders",
    summary: "Commerce order authority with no synthetic records.",
    futureScope: ["Server-side order access", "Fulfillment status", "Audited operational actions"],
  },
  {
    path: "/customers",
    parentPath: "/shop",
    label: "Customers",
    shortLabel: "Customers",
    icon: "users",
    summary: "Guest and account-backed commerce relationships and order history.",
    futureScope: ["Protected customer projection", "Account linkage", "Historical order relationships"],
  },
  {
    path: "/commerce",
    label: "Commerce Overview",
    shortLabel: "Commerce",
    icon: "commerce",
    summary: "Stripe-first Canadian commerce posture and readiness.",
    futureScope: ["Separate commerce D1", "Provider truth", "Safe activation gates"],
  },
  {
    path: "/commerce/payments",
    parentPath: "/commerce",
    label: "Payments & Payouts",
    shortLabel: "Payments",
    icon: "payments",
    summary: "Dedicated Stripe merchant account, checkout, and payout posture.",
    futureScope: ["Test API identity", "Checkout Sessions", "Merchant-owned payouts"],
  },
  {
    path: "/commerce/business",
    parentPath: "/commerce",
    label: "Business Information",
    shortLabel: "Business",
    icon: "business",
    summary: "Public and encrypted private Canadian business details.",
    futureScope: ["Public storefront profile", "Encrypted legal details", "Controlled projections"],
  },
  {
    path: "/commerce/tax",
    parentPath: "/commerce",
    label: "Tax & Documents",
    shortLabel: "Tax",
    icon: "tax",
    summary: "Tax identifier custody and document presentation.",
    futureScope: ["Encrypted identifiers", "Invoice presentation", "Receipt presentation"],
  },
  {
    path: "/commerce/emails",
    parentPath: "/commerce",
    label: "Customer Emails",
    shortLabel: "Emails",
    icon: "emails",
    summary: "Structured customer lifecycle templates without sending.",
    futureScope: ["Bounded plain text", "Safe CTA fields", "Approval before delivery"],
  },
  {
    path: "/commerce/fulfillment",
    parentPath: "/commerce",
    label: "Fulfillment & Shipping",
    shortLabel: "Fulfillment",
    icon: "fulfillment",
    summary: "Fulfillment readiness, delivery dependencies, mappings, and locked draft preparation.",
    futureScope: ["Customer delivery authority", "Shipping rates", "Explicit production activation"],
  },
  {
    path: "/media",
    label: "Media",
    shortLabel: "Media",
    icon: "media",
    summary: "Future managed brand and editorial asset library.",
    futureScope: ["Asset inventory", "Usage metadata", "Approved upload pipeline"],
  },
  {
    path: "/goats",
    label: "GOATS in the Wild",
    shortLabel: "GOATS",
    icon: "goats",
    summary: "Community submissions, moderation, comments, media, and email events.",
    futureScope: ["Approved public projection", "Approximate map locations", "Transactional outbox"],
  },
  {
    path: "/commerce/analytics",
    parentPath: "/commerce",
    label: "Commerce Intelligence",
    shortLabel: "Intelligence",
    icon: "analytics",
    summary: "LIVE merchandise, donation, refund, cost, and contribution reporting with explicit coverage.",
    futureScope: ["Currency-separated reporting", "Historical transaction economics", "Authoritative cost coverage"],
  },
  {
    path: "/goats/pending",
    parentPath: "/goats",
    label: "Pending Submissions",
    shortLabel: "Pending",
    icon: "pending",
    summary: "Submissions awaiting validation and moderation.",
    futureScope: ["Product validation", "Private media review", "Approximate location confirmation"],
  },
  {
    path: "/goats/approved",
    parentPath: "/goats",
    label: "Approved & Published",
    shortLabel: "Approved",
    icon: "approved",
    summary: "Approved community stories and publication state.",
    futureScope: ["Published records", "Hidden records", "Public projection review"],
  },
  {
    path: "/goats/rejected",
    parentPath: "/goats",
    label: "Rejected Submissions",
    shortLabel: "Rejected",
    icon: "rejected",
    summary: "Rejected submissions and submitter-facing reasons.",
    futureScope: ["Rejection history", "Corrected resubmission", "Private moderation notes"],
  },
  {
    path: "/goats/comments",
    parentPath: "/goats",
    label: "Comment Moderation",
    shortLabel: "Comments",
    icon: "comments",
    summary: "Approved, pending, and hidden authenticated community comments.",
    futureScope: ["Approve, hide, and restore", "Listing context", "Moderation audit"],
  },
  {
    path: "/goats/settings",
    parentPath: "/goats",
    label: "Interaction Defaults",
    shortLabel: "Settings",
    icon: "settings",
    summary: "Global comment and reaction defaults inherited by GOAT listings.",
    futureScope: ["Disabled", "Auto-approved", "Approval required"],
  },
  {
    path: "/goats/emails",
    parentPath: "/goats",
    label: "GOATS Emails",
    shortLabel: "Emails",
    icon: "emails",
    summary: "Branded community lifecycle templates and outbox delivery state.",
    futureScope: ["Branded HTML", "Plain-text fallback", "Retryable delivery"],
  },
  {
    path: "/membership",
    label: "VIP / Membership",
    shortLabel: "VIP",
    icon: "vip",
    summary: "Future membership definitions and support workflow.",
    futureScope: ["Plan authority integration", "Benefit definitions", "Member support tools"],
  },
  {
    path: "/access",
    label: "Users / Access",
    shortLabel: "Access",
    icon: "users",
    summary: "Authenticated accounts, roles, sessions, and audit posture.",
    futureScope: ["D1 identity authority", "Least-privilege roles", "Session and audit controls"],
  },
  {
    path: "/integrations",
    label: "Integrations",
    shortLabel: "Integrations",
    icon: "integrations",
    summary: "Future server-side provider connection posture.",
    futureScope: ["Credential-safe configuration", "Connectivity diagnostics", "Provider capability gates"],
  },
  {
    path: "/settings",
    label: "Settings",
    shortLabel: "Settings",
    icon: "settings",
    summary: "Future organization-level configuration and safeguards.",
    futureScope: ["Validated configuration", "Change previews", "Revision-checked persistence"],
  },
];
