export type PollOption = { id: string; label: string; trigger: string; normalizedTrigger: string; votes: number };
export type AdminPoll = { id: string; slug: string; title: string; description: string | null; state: "draft" | "open" | "closed" | "archived"; public: boolean; webVotingMode: "anyone" | "signed_in"; rumbleEnabled: boolean; rumbleSourceScope: string | null; revision: number; totalVotes: number; options: PollOption[]; owner: { id: string; displayName: string; avatarUrl: string | null }; updatedAt: string; openedAt: string | null; closedAt: string | null };
export type AutomationPayload = { ok: true; config: { desiredRevision: number; desiredState: { discord?: { notificationChannelId?: string | null; mentionRoleId?: string | null }; rumble?: { enabled?: boolean; intervalSeconds?: number; pollIntervalSeconds?: number } }; updatedAt: string | null }; runtime: Record<string, unknown> & { state: "online" | "stale" | "offline"; appliedRevision?: number; desiredRevision?: number; heartbeatAt?: string; botVersion?: string; ageSeconds?: number; configSyncState?: string }; activePoll: AdminPoll | null; deferred: Record<string, boolean>; activity: Array<{ id: string; event_type: string; result: string; metadata_json: string | null; created_at: string }> };

export function getAdminPolls(state = "all") { return request<{ ok: true; items: AdminPoll[]; count: number }>(`/api/admin/polls?state=${encodeURIComponent(state)}`); }
export function getPollAccess() { return request<{ ok: true; grants: Array<{ account_id: string; active: number; may_create_polls: number; account: { id: string; displayName: string; adminLevel: string | null } }> }>("/api/admin/polls/access"); }
export function mutatePollGrant(csrf: string, accountId: string, action: "approve" | "revoke") { return request<Awaited<ReturnType<typeof getPollAccess>>>("/api/admin/polls/grants", { method: "POST", headers: jsonHeaders(csrf), body: JSON.stringify({ accountId, action }) }); }
export function mutatePollLifecycle(csrf: string, poll: AdminPoll, action: "open" | "close" | "archive" | "restore") { return request<{ ok: true; poll: AdminPoll }>(`/api/admin/polls/${encodeURIComponent(poll.slug)}/lifecycle`, { method: "POST", headers: jsonHeaders(csrf), body: JSON.stringify({ revision: poll.revision, action }) }); }
export function getAutomations() { return request<AutomationPayload>("/api/admin/automations"); }
export function saveAutomations(csrf: string, payload: AutomationPayload) { return request<AutomationPayload>("/api/admin/automations", { method: "POST", headers: jsonHeaders(csrf), body: JSON.stringify({ revision: payload.config.desiredRevision, desiredState: payload.config.desiredState }) }); }
function jsonHeaders(csrf: string) { return { "Content-Type": "application/json", "X-CSRF-Token": csrf }; }
async function request<T>(input: string, init: RequestInit = {}) { const response = await fetch(input, { ...init, credentials: "include", cache: "no-store", headers: { Accept: "application/json", ...(init.headers || {}) } }); const payload = await response.json().catch(() => null) as (T & { message?: string; error?: string }) | null; if (!response.ok || !payload) throw new Error(payload?.message || "The Admin Poll service is unavailable."); return payload; }
