import { useEffect, useRef } from 'react';
import { effectiveAppearance, FEATURE_COMPONENTS, FEATURE_EFFECTS, FEATURE_ICONS, FEATURE_PRESETS, type Appearance, type FeatureComponents, type FeatureIcon } from '../lib/entrant-appearance.mjs';
import { buildFeatureEffects, drawFeatureEffects, drawFeatureFill, drawFeatureMarks } from '../lib/entrant-feature-drawing';
import '../styles/entrant-appearance.css';

export function FeatureSlicePreview({ value, label = 'Entrant appearance preview' }: { value: FeatureComponents; label?: string }) {
  const canvas = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const c = canvas.current; const ctx = c?.getContext('2d'); if (!ctx) return; ctx.clearRect(0, 0, 180, 110); ctx.save(); ctx.translate(90, 108); const start = -.9, end = .9; const radius = 102, inner = 23; ctx.beginPath(); ctx.moveTo(0, 0); ctx.arc(0, 0, radius, start - Math.PI / 2, end - Math.PI / 2); ctx.closePath(); ctx.fillStyle = '#353129'; ctx.fill(); drawFeatureFill(ctx, value, start, end, radius, inner); drawFeatureEffects(ctx, buildFeatureEffects([{ start, end, entry: { id: 'preview', appearance: { version: 1, manual: value } } }], radius, inner), radius, inner, 0, true); drawFeatureMarks(ctx, value, start, end, radius, inner); ctx.restore(); }, [value]);
  return <canvas ref={canvas} className="feature-slice-preview" width={180} height={110} role="img" aria-label={label} />;
}
export function EntrantAppearanceControls({ value, onChange, automatic, legacyFill = false, onClearLegacy, label = 'Entrant appearance' }: { value: FeatureComponents; onChange: (v: FeatureComponents) => void; automatic?: Appearance['automatic']; legacyFill?: boolean; onClearLegacy?: () => void; label?: string }) {
  const effective = effectiveAppearance({ appearance: { version: 1, manual: value, automatic }, colour: legacyFill ? '#000000' : null });
  const patch = (part: FeatureComponents) => onChange({ ...value, ...part });
  const clear = (key: keyof FeatureComponents) => { const next = { ...value }; delete next[key]; if (key === 'fill') onClearLegacy?.(); onChange(next); };
  const fx = effective.effects || { kinds: [], intensity: .4, speed: 1, density: 2 };
  return <fieldset className="entrant-appearance"><legend>{label}</legend>
    <div className="entrant-appearance__intro"><FeatureSlicePreview value={effective} /><div><p>Decorative slice treatments. These are not payment verification or account badges.</p><div className="feature-presets">{Object.entries(FEATURE_PRESETS).map(([id, preset]) => <button type="button" key={id} onClick={() => patch(preset.components)}><i style={{ background: `linear-gradient(120deg,${preset.components.fill!.colors.join(',')})` }} />{preset.label}</button>)}</div></div></div>
    <div className="feature-reset-actions"><button type="button" onClick={() => { onClearLegacy?.(); onChange({}); }}>Use automatic appearance</button><button type="button" onClick={() => { onClearLegacy?.(); onChange(Object.fromEntries(FEATURE_COMPONENTS.map(k => [k, null]))); }}>Use Wheel defaults</button></div>
    <div className="feature-controls">
      <div><label>Fill <small>{effective.sources.fill}{legacyFill && !Object.hasOwn(value, 'fill') ? ' · existing colour/image' : ''}</small><select aria-label="Feature fill" value={Object.hasOwn(value, 'fill') ? value.fill ? 'gradient' : 'none' : 'inherit'} onChange={e => e.target.value === 'inherit' ? clear('fill') : patch({ fill: e.target.value === 'none' ? null : { colors: ['#492079', '#DB41D3'] } })}><option value="inherit">Automatic / existing fill</option><option value="none">Wheel palette</option><option value="gradient">Custom gradient</option></select></label>{value.fill && <div className="feature-colors">{value.fill.colors.map((color, i) => <label key={i}>Gradient {i + 1}<input type="color" value={color} onChange={e => patch({ fill: { colors: value.fill!.colors.map((c, n) => n === i ? e.target.value : c) } })} /></label>)}</div>}<button type="button" onClick={() => clear('fill')}>Clear manual fill</button></div>
      <div><label>Icons <small>{effective.sources.icons}</small><select aria-label="Feature icons" value={Object.hasOwn(value, 'icons') ? value.icons?.length ? 'selected' : 'none' : 'inherit'} onChange={e => e.target.value === 'inherit' ? clear('icons') : patch({ icons: e.target.value === 'none' ? [] : ['star'] })}><option value="inherit">Automatic</option><option value="none">None</option><option value="selected">Selected icons</option></select></label>{value.icons?.length ? <div className="feature-checks">{FEATURE_ICONS.map(icon => <label key={icon}><input type="checkbox" checked={value.icons!.includes(icon)} disabled={!value.icons!.includes(icon) && value.icons!.length >= 2} onChange={e => patch({ icons: e.target.checked ? [...value.icons!, icon] : value.icons!.filter(v => v !== icon) as FeatureIcon[] })} />{icon}</label>)}</div> : null}<button type="button" onClick={() => clear('icons')}>Clear manual icons</button></div>
      <div><label>Edge <small>{effective.sources.edge}</small><select aria-label="Feature edge" value={Object.hasOwn(value, 'edge') ? value.edge?.placement || 'none' : 'inherit'} onChange={e => e.target.value === 'inherit' ? clear('edge') : patch({ edge: e.target.value === 'none' ? null : { color: value.edge?.color || '#FFE7A0', placement: e.target.value as 'inner' | 'outer' | 'both' } })}><option value="inherit">Automatic</option><option value="none">None</option><option value="inner">Inner edge</option><option value="outer">Outer edge</option><option value="both">Both edges</option></select></label>{value.edge && <label>Edge colour<input type="color" value={value.edge.color} onChange={e => patch({ edge: { ...value.edge!, color: e.target.value } })} /></label>}<button type="button" onClick={() => clear('edge')}>Clear manual edge</button></div>
      <div><label>Effects <small>{effective.sources.effects}</small><select aria-label="Feature effects" value={Object.hasOwn(value, 'effects') ? value.effects?.kinds.length ? 'selected' : 'none' : 'inherit'} onChange={e => e.target.value === 'inherit' ? clear('effects') : patch({ effects: e.target.value === 'none' ? null : { ...fx, kinds: ['sparkles'] } })}><option value="inherit">Automatic</option><option value="none">None</option><option value="selected">Selected effects</option></select></label>{value.effects && <><div className="feature-checks">{FEATURE_EFFECTS.map(kind => <label key={kind}><input type="checkbox" checked={value.effects!.kinds.includes(kind)} onChange={e => patch({ effects: { ...value.effects!, kinds: e.target.checked ? [...value.effects!.kinds, kind] : value.effects!.kinds.filter(v => v !== kind) } })} />{{ sparkles: 'Cruciform Sparkles', shine: 'Gentle Shine', dazzle: 'Dazzle', pulse: 'Soft Pulse' }[kind]}</label>)}</div>{(['intensity', 'speed', 'density'] as const).map(key => <label key={key}>{key}<input type="range" aria-label={`Effect ${key}`} min={key === 'intensity' ? .1 : key === 'speed' ? .5 : 1} max={key === 'intensity' ? .6 : key === 'speed' ? 1.5 : 4} step={key === 'density' ? 1 : .1} value={value.effects![key]} onChange={e => patch({ effects: { ...value.effects!, [key]: Number(e.target.value) } })} /></label>)}</>}<button type="button" onClick={() => clear('effects')}>Clear manual effects</button></div>
    </div>
  </fieldset>;
}
