import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { EntrantAppearanceControls } from './EntrantAppearanceControls';
import { automationRequest, type Discovery, type RosterPayload, type RosterPreview, type RosterRule, type WheelChoice } from '../lib/automation-client';
import '../styles/subscriber-roster.css';

const initial = (wheelId: string, wheels: WheelChoice[], discovery?: Discovery): RosterRule => ({
  name: 'Current Self-Paid Subscriber Roster', sourceScope: discovery?.source?.scope || '', targetWheelId: wheelId || wheels[0]?.id || '', enabled: false,
  syncMode: 'add_missing', entriesPerMember: 1, minimumQuality: 'qualified_live_current', appearance: null,
});
const when = (value?: string | null) => value ? new Date(value).toLocaleString() : 'Not yet';
const status = (rule: RosterRule, authority?: RosterPayload['authorities'][string]) => !rule.enabled ? 'Paused' : rule.lastResult === 'failed' || !authority?.current ? 'Needs attention' : authority.health === 'stale' ? 'Roster stale' : rule.lastResult === 'removal_blocked' ? 'Sync blocked' : authority.health === 'qualified' ? 'Current' : 'Needs attention';

export function SubscriberRosterPanel({ wheelId = '', request = automationRequest, csrf = '', canManage = true }: { wheelId?: string; request?: typeof automationRequest; csrf?: string; canManage?: boolean }) {
  const [data, setData] = useState<RosterPayload | null>(null); const [editor, setEditor] = useState<RosterRule | null>(null); const [preview, setPreview] = useState<RosterPreview | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setData(await request<RosterPayload>(`rosters?wheelId=${encodeURIComponent(wheelId)}`)); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Subscriber roster automations are unavailable.'); } }, [request, wheelId]);
  useEffect(() => { void load(); }, [load]);
  const save = async (rule: RosterRule) => { setBusy('save'); setError(''); try { await request('rosters', csrf, rule); setEditor(null); setPreview(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Roster automation could not be saved.'); } finally { setBusy(''); } };
  const inspect = async (rule: RosterRule) => { setBusy(`preview:${rule.id}`); setError(''); try { setPreview(await request<RosterPreview>('rosters/preview', csrf, { ruleId: rule.id, revision: rule.revision })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Roster preview failed.'); } finally { setBusy(''); } };
  const sync = async () => { if (!preview?.rule.id) return; setBusy(`sync:${preview.rule.id}`); setError(''); try { setPreview(await request<RosterPreview>('rosters/sync', csrf, { ruleId: preview.rule.id, revision: preview.rule.revision })); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Roster sync failed. Refresh and preview again.'); } finally { setBusy(''); } };
  const rules = data?.rules || [];
  return <section className="subscriber-roster" aria-label="Subscriber roster automations">
    <header><div><p className="eyebrow">SUBSCRIBER ROSTER</p><h2>Current Self-Paid Subscriber Roster</h2><p>Membership automation reads the persisted qualified Rumble Intelligence snapshot. It never fetches Rumble or converts gifted recipients into paid subscribers.</p></div><div><Link to="/rumble-intelligence">View Subscriber Intelligence</Link><button type="button" disabled={!canManage || busy !== '' || !data?.discovery?.source || !(data?.wheels.length)} onClick={() => setEditor(initial(wheelId, data?.wheels || [], data?.discovery))}>Create roster automation</button></div></header>
    {error ? <p className="subscriber-roster__error" role="alert">{error}</p> : null}
    {editor && data ? <RosterEditor rule={editor} wheels={data.wheels} source={data.discovery?.source || null} busy={Boolean(busy)} onChange={setEditor} onClose={() => setEditor(null)} onSave={() => void save(editor)} /> : null}
    <div className="subscriber-roster__cards">{rules.map(rule => { const authority = data?.authorities[rule.sourceScope]; const state = status(rule, authority); return <article key={rule.id} data-status={state.toLowerCase().replaceAll(' ', '-')}>
      <header><div><strong>{rule.name}</strong><small>{rule.targetWheelTitle} · {authority?.label || rule.sourceLabel || rule.sourceScope}</small></div><span>{state}</span></header>
      <dl><Fact label="Qualified as-of" value={when(authority?.current?.providerAt)} /><Fact label="Self-paid eligible" value={authority ? String(authority.counts.eligible) : '—'} /><Fact label="Gifted-only excluded" value={authority ? String(authority.counts.giftedExcluded) : '—'} /><Fact label="Mixed current" value={authority ? String(authority.counts.mixedCurrent) : '—'} /><Fact label="Review excluded" value={authority ? String(authority.counts.reviewExcluded) : '—'} /><Fact label="Managed contribution" value={`${rule.counts?.managed || 0} entrants · ${rule.counts?.managedWeight || 0} weight`} /></dl>
      <p>{rule.entriesPerMember} {rule.entriesPerMember === 1 ? 'entry' : 'entries'} per eligible member · {rule.syncMode === 'exact_managed' ? 'Exact managed roster' : 'Add missing only'}</p>
      <p>Last sync: {when(rule.lastSuccessfulSyncAt)} · {rule.lastResult ? rule.lastResult.replaceAll('_', ' ') : 'not evaluated'}</p>
      {rule.members?.length ? <details><summary>{rule.members.length} managed roster contributions</summary>{rule.members.map(member => <p key={member.entryId}><strong>{member.actorLabel}</strong> · +{member.weight} roster weight · snapshot <code>{member.snapshotId.slice(0, 12)}</code></p>)}</details> : null}
      {rule.lastResult === 'no_op' ? <small>D1-efficient no-op: no Wheel membership writes.</small> : null}
      {rule.syncMode === 'exact_managed' && !authority?.removalAllowed ? <p className="subscriber-roster__warning">Removal blocked — subscriber roster is stale/degraded</p> : null}
      <footer><button disabled={!canManage || Boolean(busy)} onClick={() => { setEditor(rule); setPreview(null); }}>Edit automation</button><button disabled={!canManage || Boolean(busy)} onClick={() => void save({ ...rule, enabled: !rule.enabled })}>{rule.enabled ? 'Disable' : 'Enable'}</button><button disabled={!canManage || Boolean(busy) || !rule.enabled} onClick={() => void inspect(rule)}>Preview changes</button></footer>
    </article>; })}</div>
    {!rules.length && data ? <p>No subscriber roster automations target this scope.</p> : null}
    {preview ? <section className="subscriber-roster__preview" aria-label="Subscriber roster preview"><header><div><p className="eyebrow">PENDING DELTA</p><h3>{preview.rule.targetWheelTitle}</h3></div><span>{preview.removalBlocked ? 'Sync blocked' : preview.status.replaceAll('_', ' ')}</span></header><div><strong>+ {preview.delta.added.length}</strong><span>additions</span><strong>~ {preview.delta.updated.length}</strong><span>weight updates</span><strong>− {preview.delta.removed.length}</strong><span>managed removals</span><strong>= {preview.delta.unchanged}</strong><span>unchanged</span></div><p>{preview.authority.counts.giftedExcluded} gifted excluded · {preview.authority.counts.reviewExcluded} review excluded · {preview.delta.retainedIneligible} ineligible retained</p>{preview.removalBlocked ? <p className="subscriber-roster__warning">Removal blocked — subscriber roster is stale/degraded. Additions may proceed; no managed removal will occur.</p> : null}<button disabled={!canManage || Boolean(busy) || Boolean(preview.synced)} onClick={() => void sync()}>{busy.startsWith('sync:') ? 'Syncing…' : preview.synced ? preview.noOp ? 'No changes written' : 'Sync complete' : 'Sync now'}</button></section> : null}
  </section>;
}

function RosterEditor({ rule, wheels, source, busy, onChange, onClose, onSave }: { rule: RosterRule; wheels: WheelChoice[]; source: Discovery['source']; busy: boolean; onChange: (rule: RosterRule) => void; onClose: () => void; onSave: () => void }) {
  const patch = (value: Partial<RosterRule>) => onChange({ ...rule, ...value });
  return <form className="subscriber-roster__editor" onSubmit={event => { event.preventDefault(); onSave(); }}><header><h3>{rule.id ? 'Edit roster automation' : 'Create roster automation'}</h3><button type="button" onClick={onClose}>Close</button></header><label>Name<input maxLength={100} required value={rule.name} onChange={event => patch({ name: event.target.value })} /></label><label>Target Wheel<select required value={rule.targetWheelId} onChange={event => patch({ targetWheelId: event.target.value })}>{wheels.map(wheel => <option key={wheel.id} value={wheel.id}>{wheel.title}</option>)}</select></label><label>Rumble source<select required value={rule.sourceScope} onChange={event => patch({ sourceScope: event.target.value })}>{source ? <option value={source.scope}>{source.displayName}</option> : <option value="">No detected source</option>}{rule.sourceScope && rule.sourceScope !== source?.scope ? <option value={rule.sourceScope}>{rule.sourceLabel || 'Saved source'}</option> : null}</select></label><label>Entries per self-paid subscriber<input type="number" min={1} max={100000} step={1} value={rule.entriesPerMember} onChange={event => patch({ entriesPerMember: Number(event.target.value) })} /></label><label>Sync mode<select value={rule.syncMode} onChange={event => patch({ syncMode: event.target.value as RosterRule['syncMode'] })}><option value="add_missing">Add missing only</option><option value="exact_managed">Exact managed roster</option></select></label><p>{rule.syncMode === 'exact_managed' ? 'Removes only this rule’s contribution, and only from a fresh qualified live roster.' : 'Never removes previous managed members automatically.'}</p><label><input type="checkbox" checked={Boolean(rule.appearance)} onChange={event => patch({ appearance: event.target.checked ? {} : null })} /> Apply roster entrant appearance</label>{rule.appearance ? <EntrantAppearanceControls value={rule.appearance} onChange={appearance => patch({ appearance })} /> : null}<label><input type="checkbox" checked={rule.enabled} onChange={event => patch({ enabled: event.target.checked })} /> Enabled</label><p>Event awards and roster membership are additive and retain separate provenance.</p><button className="primary-button" disabled={busy || !rule.name.trim() || !rule.sourceScope || !rule.targetWheelId}>Save roster automation</button></form>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
