import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthProvider';
import '../styles/trigger-studio.css';

const families = [
  ['rumble.chat.exact', 'Exact Chat Message', 'Match the complete message; case and outer spaces are ignored.'],
  ['rumble.rant', 'Rant Received', 'Add the ranter. Optionally require an amount, complete message or badge.'],
  ['rumble.follow', 'New Follower', 'Add the follower. Only events after activation qualify.'],
  ['rumble.subscribe', 'New Subscriber', 'Add the subscriber. Provider-reported zero amounts qualify by default.'],
  ['rumble.gift_purchase', 'Gifted Sub Purchase', 'Add the purchaser once per event, regardless of gift quantity.'],
  ['rumble.livestream.started', 'Livestream Started', 'State transition only. This event has no entrant actor.'],
  ['rumble.livestream.stopped', 'Livestream Ended', 'State transition only. This event has no entrant actor.'],
] as const;
type Conditions = { exactText?: string; minAmountCents?: number; minGifts?: number; giftType?: string; badge?: string; livestreamId?: string };
type Rule = { id?: string; revision?: number; name: string; description: string; enabled: boolean; sourceScope: string; eventType: string; conditions: Conditions; actionType: string; targetWheelId: string; duplicatePolicy: string; targetWheelTitle?: string; activatedAt?: string; lastMatchAt?: string; lastOutcome?: string; lastFault?: string; counters?: Record<string, number> };
type Payload = { rules: Rule[]; wheels: { id: string; title: string; lifecycle: string; editing_locked: number }[]; activity: { id: string; rule_id: string; actor_label: string; outcome: string; created_at: string }[] };
type TestResult = { matched: boolean; normalizedText: string; actorKey: string; actorLabel: string; action: string };
const initial = (wheelId: string, scope = ''): Rule => ({ name: '', description: '', enabled: false, sourceScope: scope, eventType: 'rumble.chat.exact', conditions: { exactText: '' }, actionType: 'wheel.add_actor', targetWheelId: wheelId, duplicatePolicy: 'skip' });
async function request<T>(path: string, csrf?: string, body?: unknown): Promise<T> {
  const response = await fetch(`/api/admin/automations/${path}`, { credentials: 'include', cache: 'no-store', method: body ? 'POST' : 'GET', headers: { Accept: 'application/json', ...(body ? { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf || '' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const value = await response.json(); if (!response.ok) throw new Error(value.message || 'Automation request failed.'); return value;
}
const label = (kind: string) => families.find(f => f[0] === kind)?.[1] || kind;
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Not recorded';
function conditionSummary(rule: Rule) {
  const c = rule.conditions; return [c.exactText && `“${c.exactText}”`, c.minAmountCents !== undefined && `Minimum ${c.minAmountCents} cents`, c.minGifts !== undefined && `Minimum ${c.minGifts} gifts`, c.giftType, c.badge && `Badge: ${c.badge}`, c.livestreamId && `Stream: ${c.livestreamId}`].filter(Boolean).join(' · ') || 'Any new event';
}

export function TriggerStudio({ wheelId = '', sourceScope = '', runtime }: { wheelId?: string; sourceScope?: string; runtime?: Record<string, unknown> }) {
  const { csrfToken, hasCapability } = useAuth(); const [params] = useSearchParams();
  const canRead = hasCapability('automations.view') && hasCapability('wheels.view');
  const canManage = hasCapability('automations.manage') && hasCapability('wheels.manage');
  const [payload, setPayload] = useState<Payload | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState('');
  const [editor, setEditor] = useState<Rule | null>(null); const [test, setTest] = useState<TestResult | null>(null);
  const [sample, setSample] = useState({ actorLabel: 'Sample Viewer', text: '', amountCents: 0, totalGifts: 5, giftType: 'random', badge: '', livestreamId: '' });
  const load = useCallback(async () => { if (!canRead) return; setLoading(true); setLoadError(''); try { setPayload(await request<Payload>(`rules?wheelId=${encodeURIComponent(wheelId)}`)); } catch (e) { setLoadError(e instanceof Error ? e.message : 'Could not load rules.'); } finally { setLoading(false); } }, [canRead, wheelId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (params.get('create') === '1' && canManage) setEditor(initial(params.get('wheelId') || wheelId, sourceScope)); }, [params, canManage, wheelId, sourceScope]);
  const mutate = async (path: string, body: unknown, close = false) => { if (!csrfToken || !canManage) return; setBusy(true); setError(''); try { await request(path, csrfToken, body); if (close) setEditor(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Save failed.'); } finally { setBusy(false); } };
  const update = (patch: Partial<Rule>) => { setEditor(r => r ? { ...r, ...patch } : r); setTest(null); };
  const condition = (key: keyof Conditions, value: string, numeric = false) => { if (!editor) return; const next = { ...editor.conditions }; if (!value) delete next[key]; else Object.assign(next, { [key]: numeric ? Number(value) : value }); update({ conditions: next }); };
  const dryRun = async () => { if (!editor) return; setBusy(true); setError(''); try { setTest(await request<TestResult>('test', csrfToken || '', { rule: editor, sample })); } catch (e) { setError(e instanceof Error ? e.message : 'Test failed.'); } finally { setBusy(false); } };
  if (!canRead) return <section className="event-studio"><h2>Rumble automation</h2><p>Automations and Wheels viewing access are required.</p></section>;
  const rules = payload?.rules || []; const totals = (key: string) => rules.reduce((sum, r) => sum + (r.counters?.[key] || 0), 0);
  const stateOnly = editor?.eventType.startsWith('rumble.livestream.'); const textEvent = ['rumble.chat.exact', 'rumble.rant'].includes(editor?.eventType || '');
  return <section className="event-studio" aria-label={wheelId ? 'Wheel Rumble automation' : 'Trigger Studio'}>
    <header className="event-studio__heading"><div><p className="eyebrow">RUMBLE AUTOMATION</p><h2>{wheelId ? 'Wheel automation' : 'Trigger Studio'}</h2><p>Connect Rumble events to your Wheels. Choose what qualifies, review the action, and track the results.</p></div><div className="event-actions"><button type="button" className="secondary-button" disabled={loading || busy} onClick={() => void load()}>{loading ? "Refreshing..." : "Refresh rules"}</button><button type="button" className="primary-button" disabled={!canManage || busy || !payload || Boolean(loadError)} onClick={() => { setEditor(initial(wheelId, sourceScope)); setTest(null); }}>Create automation</button>{wheelId ? <Link to="/automations">Open in Automations</Link> : null}</div></header>
    {loadError && <div className="admin-alert" role="alert"><strong>Rules unavailable</strong><p>{loadError}</p><p>{payload ? "Showing the last loaded rules. Refresh before making changes." : "Rules and activity could not be loaded. Refresh rules to try again."}</p></div>}
    {error ? <div className="admin-alert" role="alert">{error}</div> : null}
    {runtime ? <div className="event-runtime"><strong>Event engine</strong><span className="poll-status">{runtime.lastFault ? 'Needs attention' : runtime.lastSnapshotAt ? 'Reporting' : 'Awaiting Bot report'}</span><span>{Number(runtime.pending || 0)} queued</span><span>{Number(runtime.transitions || 0)} stream transitions</span><small>Last transition: {runtime.lastTransition ? label(String(runtime.lastTransition)) : 'None'} | Last snapshot: {date(runtime.lastSnapshotAt as string | undefined)}{runtime.lastFault ? ` | ${String(runtime.lastFault).replaceAll('_', ' ')}` : ''}</small></div> : <p className="event-runtime">Event engine telemetry is available in Automations. Enabling a rule starts with new events.</p>}
    <div className="event-metrics">{[['Enabled', rules.filter(r => r.enabled).length], ['Paused', rules.filter(r => !r.enabled).length], ['Target Wheels', new Set(rules.map(r => r.targetWheelId)).size], ['Matches', totals('matched')], ['Successful adds', totals('executed')], ['Duplicates / no-op', totals('duplicateEvents') + totals('duplicateEntrants')], ['Failures', totals('failed') + totals('rejected')]].map(([name, value]) => <div key={name}><strong>{payload ? value : '—'}</strong><span>{name}</span></div>)}</div>
    {editor ? <form className="event-editor" aria-label="Automation rule editor" onSubmit={e => { e.preventDefault(); void mutate('rules', editor, true); }}>
      <header><h3>{editor.id ? 'Edit automation' : 'Create automation'}</h3><button type="button" className="secondary-button" onClick={() => setEditor(null)}>Close editor</button></header>
      <div className="event-fields"><label>Rule name<input required maxLength={100} value={editor.name} onChange={e => update({ name: e.target.value })} /></label><label>Description<input maxLength={500} value={editor.description} onChange={e => update({ description: e.target.value })} /></label><label>Rumble source scope<input required placeholder="user:… or channel:…" value={editor.sourceScope} onChange={e => update({ sourceScope: e.target.value })} /></label><label>Event family<select aria-label="Event family" value={editor.eventType} onChange={e => update({ eventType: e.target.value, conditions: {} })}>{families.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label></div>
      <p className="event-family-note">{families.find(f => f[0] === editor.eventType)?.[2]}</p>
      {stateOnly ? <div className="event-incompatible" role="status"><strong>Wheel entry action incompatible</strong><p>Livestream transitions have no actor. Started and ended state is normalized in Bot telemetry; Add actor to Wheel is unavailable.</p></div> : <>
        <fieldset><legend>Conditions</legend><div className="event-fields">
          {textEvent ? <><label>{editor.eventType === 'rumble.chat.exact' ? 'Exact message (required)' : 'Exact rant message (optional)'}<input required={editor.eventType === 'rumble.chat.exact'} maxLength={500} value={editor.conditions.exactText || ''} onChange={e => condition('exactText', e.target.value)} /></label><label>Required badge (optional)<input value={editor.conditions.badge || ''} onChange={e => condition('badge', e.target.value)} /></label><label>Exact livestream ID (optional)<input value={editor.conditions.livestreamId || ''} onChange={e => condition('livestreamId', e.target.value)} /></label></> : null}
          {['rumble.rant', 'rumble.subscribe'].includes(editor.eventType) ? <label>Minimum amount in cents (optional)<input type="number" min={0} max={100000000} step={1} value={editor.conditions.minAmountCents ?? ''} onChange={e => condition('minAmountCents', e.target.value, true)} /></label> : null}
          {editor.eventType === 'rumble.gift_purchase' ? <><label>Minimum gifts (optional)<input type="number" min={0} step={1} value={editor.conditions.minGifts ?? ''} onChange={e => condition('minGifts', e.target.value, true)} /></label><label>Gift type (optional)<input value={editor.conditions.giftType || ''} onChange={e => condition('giftType', e.target.value)} /></label></> : null}
          {editor.eventType === 'rumble.follow' ? <p>Any new follower from this source. No text or amount condition.</p> : null}
        </div></fieldset>
        <fieldset><legend>Add actor to Wheel</legend><div className="event-fields"><label>Target Wheel<select aria-label="Target Wheel" required value={editor.targetWheelId} onChange={e => update({ targetWheelId: e.target.value })}><option value="">Choose a Wheel</option>{payload?.wheels.map(w => <option key={w.id} value={w.id}>{w.title}{w.editing_locked || w.lifecycle === 'archived' ? ' (entry edits unavailable)' : ''}</option>)}</select></label><label>Duplicate policy<select value="skip" disabled><option value="skip">Skip if entrant already exists</option></select></label></div><p>One event creates at most one entry with weight 1. Existing labels are compared using normalized text, including hidden entries.</p></fieldset>
        <label className="event-enable"><input type="checkbox" checked={editor.enabled} onChange={e => update({ enabled: e.target.checked })} />Enable on save</label><p>Saving an enabled rule starts a new activation boundary. Older provider history is ignored. Revision: {editor.revision || 'New'} · Activated: {date(editor.activatedAt)}</p>
        <fieldset className="event-tester"><legend>DRY RUN — NO ACTION WILL BE EXECUTED.</legend><div className="event-fields"><label>Sample actor<input value={sample.actorLabel} onChange={e => { setSample({ ...sample, actorLabel: e.target.value }); setTest(null); }} /></label>{textEvent ? <label>Sample message<input value={sample.text} onChange={e => { setSample({ ...sample, text: e.target.value }); setTest(null); }} /></label> : null}{['rumble.rant', 'rumble.subscribe'].includes(editor.eventType) ? <label>Sample amount (cents)<input type="number" min={0} value={sample.amountCents} onChange={e => { setSample({ ...sample, amountCents: Number(e.target.value) }); setTest(null); }} /></label> : null}{editor.eventType === 'rumble.gift_purchase' ? <><label>Sample gifts<input type="number" min={0} value={sample.totalGifts} onChange={e => { setSample({ ...sample, totalGifts: Number(e.target.value) }); setTest(null); }} /></label><label>Sample gift type<input value={sample.giftType} onChange={e => { setSample({ ...sample, giftType: e.target.value }); setTest(null); }} /></label></> : null}{editor.conditions.badge ? <label>Sample badge<input value={sample.badge} onChange={e => { setSample({ ...sample, badge: e.target.value }); setTest(null); }} /></label> : null}{editor.conditions.livestreamId ? <label>Sample livestream ID<input value={sample.livestreamId} onChange={e => { setSample({ ...sample, livestreamId: e.target.value }); setTest(null); }} /></label> : null}</div><div className="event-actions"><button type="button" className="secondary-button" onClick={() => { setSample({ actorLabel: "Sample Viewer", text: "ENTER", amountCents: editor.eventType === "rumble.rant" ? 100 : 0, totalGifts: 5, giftType: "rumble", badge: "", livestreamId: "sample-live" }); setTest(null); }}>Load redacted sample</button><button type="button" className="secondary-button" disabled={busy || !canManage} onClick={() => void dryRun()}>Test rule</button></div>{test ? <div className="event-test-result" role="status"><strong>{test.matched ? 'Matched' : 'No match'}</strong><p>Actor: {test.actorLabel} · {test.actorKey}</p>{textEvent ? <p>Normalized text: {test.normalizedText || '(empty)'}</p> : null}<p>{test.action}</p></div> : null}</fieldset>
        <button className="primary-button" disabled={busy || !canManage} type="submit">{busy ? 'Working…' : editor.enabled ? 'Save and enable' : 'Save paused rule'}</button>
      </>}
    </form> : null}
    <div className="event-rule-list">{rules.map(rule => <article key={rule.id} className="event-rule"><header><div><p className="eyebrow">{label(rule.eventType)}</p><h3>{rule.name}</h3></div><span className="poll-status">{rule.enabled ? 'Enabled' : 'Disabled'} · r{rule.revision}</span></header><p>{conditionSummary(rule)}</p><p>{rule.sourceScope} → <Link to={`/wheels/${rule.targetWheelId}`}>{rule.targetWheelTitle}</Link> · Add actor · Skip duplicates</p><dl><div><dt>Last match</dt><dd>{date(rule.lastMatchAt)}</dd></div><div><dt>Successful adds</dt><dd>{rule.counters?.executed || 0}</dd></div><div><dt>Duplicate / no-op</dt><dd>{(rule.counters?.duplicateEvents || 0) + (rule.counters?.duplicateEntrants || 0)}</dd></div><div><dt>Last outcome / fault</dt><dd>{rule.lastFault || rule.lastOutcome || 'None'}</dd></div></dl><div className="event-actions"><button type="button" disabled={busy || !canManage} onClick={() => { setEditor(rule); setTest(null); }}>Edit</button><button type="button" disabled={busy || !canManage} onClick={() => void mutate('rules', { ...rule, enabled: !rule.enabled })}>{rule.enabled ? 'Disable' : 'Enable'}</button><button type="button" disabled={busy || !canManage} onClick={() => { if (window.confirm(`Delete automation “${rule.name}”? Existing entries and receipts are retained.`)) void mutate('rules/delete', { id: rule.id, revision: rule.revision, confirm: 'DELETE' }); }}>Delete</button></div></article>)}</div>
    {!rules.length && !loadError ? <p className="event-empty" role="status">{loading ? 'Loading rules…' : payload ? 'No rules yet. Create an automation to connect new Rumble events to a Wheel.' : 'Rules have not loaded.'}</p> : null}
    <div className="event-activity"><h3>Recent Wheel actions</h3>{payload?.activity.length ? payload.activity.map(a => <p key={a.id}><strong>{a.actor_label}</strong> · {a.outcome.replaceAll('_', ' ')} · {date(a.created_at)}</p>) : <p>{loadError ? "Activity unavailable until rules reload successfully." : loading && !payload ? "Loading recent actions..." : "No event receipts recorded."}</p>}</div>
  </section>;
}
