export type AccountSummary = { id: string; displayName: string; email: string | null; role: string; adminLevel: string };
export type AdminWheel = { id: string; reference: string; slug: string; title: string; description: string | null; lifecycle: "draft" | "active" | "archived"; visibility: "public" | "hidden"; owner: AccountSummary; participantCount: number; revision: number; officialEnabled: boolean; demoEnabled: boolean; editingLocked: boolean; spinLocked: boolean; latestWinner: string | null; latestResultAt: string | null; updatedAt: string };
export type AdminResult = { id: string; wheelId: string; wheelTitle: string; wheelSlug: string; winningEntryId: string; winningLabel: string; winningWeight: number; wheelRevision: number; snapshotHash: string; performedByAccountId: string; performer: AccountSummary; idempotencyKey: string; createdAt: string; voided: boolean; voidedAt: string | null; voidReason: string | null; voidedBy: AccountSummary | null };
export type AdminWheelMedia = { id: string; purpose: "background" | "centre"; url: string; contentType: string; byteSize: number; width: number | null; height: number | null; sha256: string; createdAt: string; lifecycle: "active" | "deleted" };
export type WheelAccessPayload = { ok: true; grants: Array<{ account: AccountSummary; active: boolean; mayCreate: boolean; maximumOwnedWheels: number | null; updatedAt: string }>; assignments: Array<{ wheelId: string; wheelTitle: string; wheelSlug: string; account: AccountSummary; role: "owner" | "editor" | "spinner"; active: boolean; updatedAt: string }> };
export type AdminStage = { id: string; slug: string; title: string; description: string | null; owner: AccountSummary; visibility: "public" | "private"; lifecycle: "active" | "archived"; revision: number; wheelCount: number; createdAt: string; updatedAt: string };

export const getWheelLibrary = () => request<{ ok: true; items: AdminWheel[] }>("/api/admin/wheels");
export const getWheelDetail = (id: string) => request<{ ok: true; item: AdminWheel & { config: Record<string, unknown>; entries: Array<{ id: string; label: string; order: number; weight: number; colour: string | null; state: string }>; access: WheelAccessPayload["assignments"]; results: AdminResult[]; media: AdminWheelMedia[] } }>(`/api/admin/wheels/${encodeURIComponent(id)}`);
export const getWheelAccess = () => request<WheelAccessPayload>("/api/admin/wheels/access");
export const getWheelResults = (search = "") => request<{ ok: true; items: AdminResult[] }>(`/api/admin/wheels/results?search=${encodeURIComponent(search)}`);
export const searchAccounts = (search = "") => request<{ ok: true; accounts: AccountSummary[] }>(`/api/admin/wheels/accounts?q=${encodeURIComponent(search)}`);
export const getWheelSettings = () => request<{ ok: true; settings: Record<string, unknown>; revision: number; updatedAt: string }>("/api/admin/wheels/settings");
export const getStageLibrary = () => request<{ ok: true; items: AdminStage[] }>("/api/admin/wheels/stages");
export const mutateGrant = (csrf: string, body: Record<string, unknown>) => write<WheelAccessPayload>("/api/admin/wheels/grants", csrf, body);
export const mutateAssignment = (csrf: string, body: Record<string, unknown>) => write<WheelAccessPayload>("/api/admin/wheels/assignments", csrf, body);
export const mutateControl = (csrf: string, body: Record<string, unknown>) => write<{ ok: true; items: AdminWheel[] }>("/api/admin/wheels/controls", csrf, body);
export const voidResult = (csrf: string, spinId: string, reason: string) => write<{ ok: true; items: AdminResult[] }>("/api/admin/wheels/results/void", csrf, { spinId, reason });
export const saveSettings = (csrf: string, body: Record<string, unknown>) => write<{ ok: true; settings: Record<string, unknown>; revision: number; updatedAt: string }>("/api/admin/wheels/settings", csrf, body);
export const removeAdminWheelMedia = (csrf: string, wheelId: string, assetId: string) => write<{ ok: true; removed: boolean; assetId: string }>(`/api/admin/wheels/${encodeURIComponent(wheelId)}/media/${encodeURIComponent(assetId)}/remove`, csrf, {});
export const mutateStage = (csrf: string, body: { stageId: string; action: "hide" | "archive" | "restore" | "delete"; confirmDelete?: boolean }) => write<{ ok: true; items: AdminStage[] }>("/api/admin/wheels/stages", csrf, body);
function write<T>(path: string, csrf: string, body: Record<string, unknown>) { return request<T>(path, { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify(body) }); }
async function request<T>(path: string, init: RequestInit = {}) { const response = await fetch(path, { ...init, credentials: "include", cache: "no-store", headers: { Accept: "application/json", ...(init.headers || {}) } }); const payload = await response.json().catch(() => null) as (T & { error?: string; message?: string }) | null; if (!response.ok || !payload) throw new Error(payload?.message || "The Wheels Admin service is unavailable."); return payload; }
