export type PhysicsCurveProfile = "natural-hybrid" | "heavy-flywheel" | "suspense-tail" | "quick-draw" | "mechanical-clicker";
export type WheelCurveProfile = PhysicsCurveProfile | "classic-linear" | "legacy-broadcast-smooth" | "custom-physics" | "custom-shape";
export type WheelPhysics = { quadraticDrag: number; viscousDrag: number; clickerFriction: number; clickerOnsetSpeed: number; clickerBlendWidth: number; captureStartSpeed: number; captureDurationFraction: number };
export type CustomShapePoint = { time: number; speed: number };
export type CustomShape = { interpolation: "monotone-pchip"; points: CustomShapePoint[] };
export type WheelMechanics = { mechanicsVersion: 2; curveProfile: WheelCurveProfile; physics: WheelPhysics; customShape: CustomShape; launchRpsMin: number; launchRpsMax: number; minimumFullTurns: number; maximumFullTurns: number; defaultSpinDurationMs: number; minimumSpinDurationMs: number; maximumSpinDurationMs: number };
export type CompiledWheelMechanics = { kind: "compiled-wheel-mechanics-v2"; mechanics: WheelMechanics; sampleCount: number; velocity: Float64Array; deceleration: Float64Array; progress: Float64Array; area: number; captureStartU: number; captureDerivativeScale: number; physicalStopTime: number | null; odeStep: number | null };
export type NaturalnessDiagnostics = { speedAt25: number; speedAt50: number; speedAt75: number; speedAt90: number; tailDurationFraction: number; terminalSpeed: number; terminalAcceleration: number; peakDeceleration: number; maximumJerk: number; estimatedFinalClickIntervalMs: number; finalTravelPercent: number; captureSpeedRemoved: number; handbrakeRisk: boolean; checks: { monotoneSpeed: boolean; softTerminalStop: boolean; noReverseMotion: boolean; noFinalSnap: boolean; suspenseTailPresent: boolean; frameRateIndependent: boolean } };
export const WHEEL_MECHANICS_VERSION: 2;
export const CANONICAL_SAMPLE_COUNT: 1025;
export const CUSTOM_SHAPE_INTERPOLATION: "monotone-pchip";
export const PHYSICS_PRESETS: Readonly<Record<PhysicsCurveProfile, Readonly<WheelPhysics & { name: string; description: string }>>>;
export const CURVE_PRESETS: Readonly<Record<Exclude<WheelCurveProfile, "custom-physics" | "custom-shape">, Readonly<Partial<WheelPhysics> & { name: string; description: string }>>>;
export const MECHANICS_BOUNDS: Readonly<Record<string, readonly [number, number]>>;
export const DEFAULT_CUSTOM_SHAPE_POINTS: readonly Readonly<CustomShapePoint>[];
export const DEFAULT_WHEEL_MECHANICS: Readonly<WheelMechanics>;
export function normalizeMechanicsConfig(value: unknown, options?: { strict?: boolean }): WheelMechanics;
export function normalizeWheelMechanics(value: unknown, options?: { strict?: boolean }): WheelMechanics;
export function cloneDefaultWheelMechanics(): WheelMechanics;
export function clickerActivation(speed: number, physics?: WheelPhysics): number;
export function smootherstep(value: number): number;
export function smootherstepIntegral(value: number): number;
export function compileVelocityProfile(config?: unknown, options?: { sampleCount?: number; odeStep?: number }): CompiledWheelMechanics;
export function compileCustomShape(points: CustomShapePoint[], options?: { sampleCount?: number; odeStep?: number }): CompiledWheelMechanics;
export function velocityAt(compiled: CompiledWheelMechanics, normalizedTime: number): number;
export function decelerationAt(compiled: CompiledWheelMechanics, normalizedTime: number): number;
export function progressAt(compiled: CompiledWheelMechanics, normalizedTime: number): number;
export function rotationAt(plan: { startRotation: number; totalTravel: number; durationMs: number; mechanics: WheelMechanics; compiledMechanics?: CompiledWheelMechanics }, elapsedMs: number): number;
export function calculateNaturalnessDiagnostics(compiledOrConfig?: CompiledWheelMechanics | WheelMechanics, options?: { durationMs?: number; segmentCount?: number; turns?: number }): NaturalnessDiagnostics;
export function velocityAtNormalizedTime(normalizedTime: number, mechanics?: WheelMechanics): number;
export function curveTotalArea(mechanics?: WheelMechanics): number;
export function progressAtNormalizedTime(normalizedTime: number, mechanics?: WheelMechanics): number;
export function progressAtTime(elapsedMs: number, durationMs: number, mechanics?: WheelMechanics): number;
export function velocityAtTime(elapsedMs: number, durationMs: number, mechanics?: WheelMechanics, totalTravel?: number): number;
export function launchRpsForSample(turnRandom: number, mechanics?: WheelMechanics): number;
export function fullTurnsForMechanics(durationMs: number, turnRandom: number, mechanics?: WheelMechanics, positiveTargetDeltaDegrees?: number): number;
export function estimatedFullTurnRange(durationMs: number, mechanics?: WheelMechanics): { minimum: number; maximum: number };
export function spinRotationAtTime(plan: { startRotation: number; totalTravel: number; durationMs: number; mechanics: WheelMechanics; compiledMechanics?: CompiledWheelMechanics }, elapsedMs: number): number;
export function curveParameters(mechanics?: WheelMechanics): Partial<WheelPhysics> & { holdEnd?: number; tailStart?: number; tailVelocity?: number };

